// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Thu May  8 11:19:41 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 1056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1056" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
numMediumBJets                numMediumBJets                numMediumBJets                numMediumBJets                                                  'I'    [0,3]
MT_of_everything              MT_of_everything              MT_of_everything              MT_of_everything                                                'F'    [139.259521484,1945.45153809]
MT_over_mass_of_everything   MT_of_everything_D_mass_of_everything MT_over_mass_of_everything   MT_over_mass_of_everything                                             'F'    [0.345161795616,0.981012523174]
ttbar_fake_3l_top_mass_lep_blep ttbar_fake_3l_top_mass_lep_blep ttbar_fake_3l_top_mass_lep_blep ttbar_fake_3l_top_mass_lep_blep                                     'F'    [12.5587921143,766.133789062]
ttW_3l_ttbar_MT_mass_ratio_B_b ttW_3l_ttbar_MT_mass_ratio_B_b ttW_3l_ttbar_MT_mass_ratio_B_b ttW_3l_ttbar_MT_mass_ratio_B_b                                    'F'    [0.00101338757668,0.994386911392]
Match_ttbar_fake_3l_B   max_Match_ttbar_fake_3l_B,_M_6_ Match_ttbar_fake_3l_B   Match_ttbar_fake_3l_B                                       'F'    [-6,0.92981171608]
Match_ttbar_fake_3l_b   max_Match_ttbar_fake_3l_b,_M_6_ Match_ttbar_fake_3l_b   Match_ttbar_fake_3l_b                                       'F'    [-6,0.759276270866]
Match_ttW_3l_Bb               Match_ttW_3l_Bb               Match_ttW_3l_Bb               Match_ttW_3l_Bb                                                 'F'    [-6.15538263321,1.43468344212]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "numMediumBJets", "MT_of_everything", "MT_over_mass_of_everything", "ttbar_fake_3l_top_mass_lep_blep", "ttW_3l_ttbar_MT_mass_ratio_B_b", "Match_ttbar_fake_3l_B", "Match_ttbar_fake_3l_b", "Match_ttW_3l_Bb" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 3;
      fVmin[1] = 139.259521484375;
      fVmax[1] = 1945.45153808594;
      fVmin[2] = 0.34516179561615;
      fVmax[2] = 0.981012523174286;
      fVmin[3] = 12.5587921142578;
      fVmax[3] = 766.1337890625;
      fVmin[4] = 0.00101338757667691;
      fVmax[4] = 0.994386911392212;
      fVmin[5] = -6;
      fVmax[5] = 0.929811716079712;
      fVmin[6] = -6;
      fVmax[6] = 0.759276270866394;
      fVmin[7] = -6.15538263320923;
      fVmax[7] = 1.43468344211578;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631488,0.0262976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561644,0.0123288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243976,-0.0512048) , 
7, 0.0294782, 0, 0, 0.341004,-0.158996) , 
1, 397.287, 0, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72093,0.0422554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629787,0.0233444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313462,-0.0350529) , 
1, 483.296, 0, 0, 0.411921,-0.084187) , 
0, 1.14286, 0, 0, 0.5,-5.32118e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631488,0.0221084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507317,0.00213626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216117,-0.04864) , 
7, -0.315369, 0, 0, 0.341004,-0.133319) , 
1, 397.287, 0, 0, 0.5,-4.67967e-06)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72093,0.0367495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510246,0.00374487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23221,-0.0484585) , 
6, -0.850075, 1, 0, 0.411921,-0.0728162) , 
0, 1.14286, 0, 0, 0.5,-2.81259e-05)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631488,0.0193456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507317,0.00123243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216117,-0.0426049) , 
7, -0.315369, 0, 0, 0.341004,-0.116124) , 
1, 397.287, 0, 0, 0.5,-2.92398e-05)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588406,0.0149639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635135,0.0182988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256849,-0.0404931) , 
7, 0.290242, 0, 0, 0.333333,-0.139204) , 
6, -1.17195, 1, 0, 0.5,-5.62081e-05)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72093,0.031287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720721,0.0392685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358696,-0.0215225) , 
3, 120.212, 0, 0, 0.411921,-0.0612199) , 
0, 1.14286, 0, 0, 0.5,-6.94388e-05)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631488,0.0165236) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507317,0.00054684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216117,-0.0367183) , 
7, -0.315369, 0, 0, 0.341004,-0.0982665) , 
1, 397.287, 0, 0, 0.5,-4.79259e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588406,0.012924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420849,-0.0116803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121495,-0.0579997) , 
7, -0.784028, 0, 0, 0.333333,-0.118966) , 
6, -1.17195, 1, 0, 0.5,-7.31597e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733032,0.0329216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689498,0.0214238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349026,-0.0196758) , 
0, 1.14286, 0, 0, 0.438323,-0.0425175) , 
1, 569.305, 0, 0, 0.5,-9.93478e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588406,0.0115086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385621,-0.0141495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0666667,-0.0662961) , 
7, -1.14212, 0, 0, 0.333333,-0.105205) , 
6, -1.17195, 1, 0, 0.5,-7.63972e-05)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72093,0.0245162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720721,0.0325484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358696,-0.0171915) , 
3, 120.212, 0, 0, 0.411921,-0.046712) , 
0, 1.14286, 0, 0, 0.5,-9.90646e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733032,0.0289541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500935,0.0040555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326667,-0.0290044) , 
2, 0.703016, 0, 0, 0.438323,-0.0366316) , 
1, 569.305, 0, 0, 0.5,-7.42981e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555426,0.0069265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534884,8.04894e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185897,-0.0398522) , 
7, 0.11358, 0, 0, 0.261307,-0.141978) , 
1, 311.278, 0, 0, 0.5,-5.8833e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588406,0.009932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635135,0.0127178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256849,-0.0282194) , 
7, 0.290242, 0, 0, 0.333333,-0.0895879) , 
6, -1.17195, 1, 0, 0.5,-8.0446e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536332,0.00631137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604651,0.00247464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253425,-0.0390944) , 
1, 541.576, 0, 0, 0.333333,-0.136464) , 
2, 0.617669, 0, 0, 0.5,-9.11129e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72093,0.0212069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720721,0.0276838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358696,-0.014751) , 
3, 120.212, 0, 0, 0.411921,-0.0395825) , 
0, 1.14286, 0, 0, 0.5,-9.40731e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681081,0.0170226) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68,0.0298184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368249,-0.0143483) , 
3, 113.951, 0, 0, 0.402332,-0.0432063) , 
1, 483.296, 0, 0, 0.5,-7.12631e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559702,0.00944551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679012,0.0120629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321311,-0.0244904) , 
1, 551.376, 0, 0, 0.396373,-0.0765032) , 
2, 0.708505, 0, 0, 0.5,-5.86713e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717949,0.0223813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731034,0.0228595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375185,-0.0126938) , 
3, 120.212, 0, 0, 0.437956,-0.0297178) , 
7, 0.350388, 0, 0, 0.5,-6.0097e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528322,0.00455587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45283,-0.00506158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223529,-0.0488976) , 
5, -0.60871, 0, 0, 0.311594,-0.139794) , 
2, 0.587391, 0, 0, 0.5,-3.97695e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555426,0.00561342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372549,-0.0112614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14433,-0.0426173) , 
5, -0.390152, 0, 0, 0.261307,-0.111997) , 
1, 311.278, 0, 0, 0.5,-4.45696e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564537,0.00691576) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.787234,0.0362756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239669,-0.03049) , 
3, 120.212, 0, 0, 0.32872,-0.0851011) , 
7, -0.733907, 0, 0, 0.5,-6.36059e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587597,0.00853361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711538,0.0234639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311978,-0.0200498) , 
1, 614.876, 0, 0, 0.36253,-0.0624368) , 
6, -2.13756, 1, 0, 0.5,-7.1383e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72093,0.0170866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474747,0.00196376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292308,-0.0245083) , 
2, 0.695183, 0, 0, 0.411921,-0.0308447) , 
0, 1.14286, 0, 0, 0.5,-7.02789e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555426,0.00489805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304965,-0.0140709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155172,-0.0445874) , 
1, 253.754, 0, 0, 0.261307,-0.0965807) , 
1, 311.278, 0, 0, 0.5,-6.39038e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536332,0.00473062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356164,-0.00584584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318966,-0.0326058) , 
4, 0.515684, 1, 0, 0.333333,-0.0985539) , 
2, 0.617669, 0, 0, 0.5,-7.26638e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587597,0.0077108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711538,0.0208194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311978,-0.0181795) , 
1, 614.876, 0, 0, 0.36253,-0.0559114) , 
6, -2.13756, 1, 0, 0.5,-6.79904e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564537,0.00587219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.787234,0.0327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239669,-0.0267629) , 
3, 120.212, 0, 0, 0.32872,-0.0712147) , 
7, -0.733907, 0, 0, 0.5,-6.63668e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717949,0.0175543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715151,0.017205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368341,-0.0107355) , 
1, 569.305, 0, 0, 0.437956,-0.022541) , 
7, 0.350388, 0, 0, 0.5,-7.10397e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528322,0.00361418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45283,-0.00161718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223529,-0.0419834) , 
5, -0.60871, 0, 0, 0.311594,-0.10752) , 
2, 0.587391, 0, 0, 0.5,-5.45888e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555426,0.0042543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304965,-0.0120286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155172,-0.0407743) , 
1, 253.754, 0, 0, 0.261307,-0.0825643) , 
1, 311.278, 0, 0, 0.5,-5.77429e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670061,0.01334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363083,-0.00897453) , 
1, 414.004, 0, 0, 0.51626,0.0104908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.034541) , 
7, -1.8182, 0, 0, 0.5,-6.49976e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587597,0.00666446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711538,0.0166488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311978,-0.0156487) , 
1, 614.876, 0, 0, 0.36253,-0.0474588) , 
6, -2.13756, 1, 0, 0.5,-5.77153e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528322,0.00327453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45283,-0.00152858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223529,-0.0386785) , 
5, -0.60871, 0, 0, 0.311594,-0.096438) , 
2, 0.587391, 0, 0, 0.5,-5.59856e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72093,0.0135862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474747,0.00128842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292308,-0.0193441) , 
2, 0.695183, 0, 0, 0.411921,-0.0236234) , 
0, 1.14286, 0, 0, 0.5,-5.83697e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761261,0.0215178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444882,-0.00341279) , 
1, 551.376, 0, 0, 0.51626,0.00923075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.0310377) , 
7, -1.8182, 0, 0, 0.5,-5.31589e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717949,0.0144308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731034,0.0159628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375185,-0.00840042) , 
3, 120.212, 0, 0, 0.437956,-0.0179632) , 
7, 0.350388, 0, 0, 0.5,-3.84805e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587597,0.00580516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389646,-0.00646009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136364,-0.0443969) , 
2, 0.571043, 0, 0, 0.36253,-0.0407153) , 
6, -2.13756, 1, 0, 0.5,-2.67695e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555426,0.003485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304965,-0.00906647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155172,-0.0367032) , 
1, 253.754, 0, 0, 0.261307,-0.0659121) , 
1, 311.278, 0, 0, 0.5,-3.3181e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559702,0.00541792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463636,-0.00126704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307229,-0.0220286) , 
2, 0.604284, 0, 0, 0.396373,-0.0413097) , 
2, 0.708505, 0, 0, 0.5,-4.0299e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72093,0.0113875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473413,-0.000114796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203488,-0.0219154) , 
6, 0.115536, 1, 0, 0.411921,-0.0193135) , 
0, 1.14286, 0, 0, 0.5,-3.9961e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761261,0.0188939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444882,-0.00290075) , 
1, 551.376, 0, 0, 0.51626,0.00807744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.0279027) , 
7, -1.8182, 0, 0, 0.5,-4.18298e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559702,0.00490597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423977,-0.00558397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181818,-0.0379673) , 
6, 0.401195, 1, 0, 0.396373,-0.0370844) , 
2, 0.708505, 0, 0, 0.5,-3.0502e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555426,0.00303308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321739,-0.00539172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178571,-0.0285875) , 
1, 270.11, 0, 0, 0.261307,-0.0567369) , 
1, 311.278, 0, 0, 0.5,-3.34484e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717949,0.0119667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731034,0.013463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375185,-0.0069832) , 
3, 120.212, 0, 0, 0.437956,-0.0145272) , 
7, 0.350388, 0, 0, 0.5,-3.87832e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670061,0.00945632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363083,-0.00628859) , 
1, 414.004, 0, 0, 0.51626,0.00717467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.0252261) , 
7, -1.8182, 0, 0, 0.5,-2.91617e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528322,0.00237733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438596,0.00155316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222222,-0.0333967) , 
5, -0.925844, 0, 0, 0.311594,-0.0674382) , 
2, 0.587391, 0, 0, 0.5,-2.64614e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587597,0.00464831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408163,-0.00397293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132353,-0.0352414) , 
7, -1.14212, 0, 0, 0.36253,-0.0319124) , 
6, -2.13756, 1, 0, 0.5,-2.95992e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72093,0.0092051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720721,0.0129352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358696,-0.00645551) , 
3, 120.212, 0, 0, 0.411921,-0.0152005) , 
0, 1.14286, 0, 0, 0.5,-3.67801e-05)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
