////////////////////////////////////////////////////////////////
//
//   The purpose of this file is to have all the
//   includes for the kinematic variables
//   in a single location so that every program can easily
//   include them and use them as necessary.
//
////////////////////////////////////////////////////////////////

#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/KinematicVariable.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/GenericObjectMember.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/GenericCollectionMember.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CSVWeights.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CSVWeightsSF.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/PUWeights.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/TopPtWeights.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/LeptonIDAndIsoScaleFactors.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/LeptonTriggerScaleFactors.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CleanEventVars.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CheckTwoLepTrigger.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CERN/LepMVAs.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/LepGenInfos.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CERN/TightCharges.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/GenericCollectionSizeVariable.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MetLD.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/DBCorrectedRelIsoDR04s.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/HiggsDecayType.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/TwoObjectKinematic.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CERN/FinalBDT.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CERN/TightChargeAndLepMVAScaleFactors.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CERN/DataDrivenFR.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/BTagWeights.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/BTagShapeWeights.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/PassZmask.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/TwoJetVariables.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/FinalBDT_OS_2012.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/GenericVariable.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CERN/RecoIDIsoSIPSFs.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CERN/TightChargeAndLepMVAScaleFactorsPerLepton.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CERN/DataDrivenFRPerLepton.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/ThreeObjectKinematic.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/FourObjectKinematic.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/CERN/FinalBDT_3l.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MatchTester_ttZ_3l.h"
//#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MatchTester_ttZ_3l_GP.h"
//#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MatchTesterBDT_ttZ_3l.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MatchTester_ttW_3l.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MatchTester_ttbar_fake_3l.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MatchTester_ttW_SS.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MatchTester_ttbar_fake_SS.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/FinalBDT_ttZ_3l.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/FinalBDT_ttW_3l.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/FinalBDT_ttW_SS.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MatchTester_ttbar_jj.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/LepCuts.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/TightChargeAndLepCutScaleFactors.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/TightChargeAndLepCutScaleFactorsPerLepton.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/DataDrivenFRLepCut.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/NOVa/DataDrivenFRLepCutPerLepton.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/MatchTester_ttbar_ll.h"

