// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Thu May  8 11:23:49 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 692
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "692" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
numMediumBJets                numMediumBJets                numMediumBJets                numMediumBJets                                                  'I'    [0,3]
Match_ttZ_3l_Bb               Match_ttZ_3l_Bb               Match_ttZ_3l_Bb               Match_ttZ_3l_Bb                                                 'F'    [-9.55637741089,1.66458761692]
Match_ttZ_3l_Bq               Match_ttZ_3l_Bq               Match_ttZ_3l_Bq               Match_ttZ_3l_Bq                                                 'F'    [-8.65219974518,1.2857350111]
Match_ttZ_3l_bq               Match_ttZ_3l_bq               Match_ttZ_3l_bq               Match_ttZ_3l_bq                                                 'F'    [-4.86507892609,1.50849235058]
Match_ttZ_3l_Bbq              Match_ttZ_3l_Bbq              Match_ttZ_3l_Bbq              Match_ttZ_3l_Bbq                                                'F'    [-11.0888710022,1.84652841091]
Match_ttZ_3l_Bqq              Match_ttZ_3l_Bqq              Match_ttZ_3l_Bqq              Match_ttZ_3l_Bqq                                                'F'    [-12.1528787613,2.18387889862]
Match_ttZ_3l_bqq              Match_ttZ_3l_bqq              Match_ttZ_3l_bqq              Match_ttZ_3l_bqq                                                'F'    [-12.8378286362,2.00896811485]
ZLike_mass_leplep_SFOS_all    ZLike_mass_leplep_SFOS_all    ZLike_mass_leplep_SFOS_all    ZLike_mass_leplep_SFOS_all                                      'F'    [81.2906265259,101.144287109]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "numMediumBJets", "Match_ttZ_3l_Bb", "Match_ttZ_3l_Bq", "Match_ttZ_3l_bq", "Match_ttZ_3l_Bbq", "Match_ttZ_3l_Bqq", "Match_ttZ_3l_bqq", "ZLike_mass_leplep_SFOS_all" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 3;
      fVmin[1] = -9.55637741088867;
      fVmax[1] = 1.66458761692047;
      fVmin[2] = -8.65219974517822;
      fVmax[2] = 1.28573501110077;
      fVmin[3] = -4.86507892608643;
      fVmax[3] = 1.50849235057831;
      fVmin[4] = -11.0888710021973;
      fVmax[4] = 1.84652841091156;
      fVmin[5] = -12.1528787612915;
      fVmax[5] = 2.18387889862061;
      fVmin[6] = -12.8378286361694;
      fVmax[6] = 2.00896811485291;
      fVmin[7] = 81.2906265258789;
      fVmax[7] = 101.144287109375;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734558,0.0433464) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308838,-0.0343084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0919216,-0.0914134) , 
0, 0.142857, 0, 0, 0.260121,-0.239879) , 
4, -1.23333, 0, 0, 0.398156,-0.101844)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734558,0.0394177) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423301,-0.0104342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216819,-0.0493553) , 
2, 0.182011, 0, 0, 0.260121,-0.216346) , 
4, -1.23333, 0, 0, 0.398156,-0.0914594)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734558,0.0359616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378942,-0.0145924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205232,-0.0484126) , 
4, -2.17668, 0, 0, 0.260121,-0.195876) , 
4, -1.23333, 0, 0, 0.398156,-0.0826557)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.0215974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274888,-0.0303328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0631967,-0.0827816) , 
0, 0.142857, 0, 0, 0.224708,-0.209271) , 
4, -1.8493, 0, 0, 0.398156,-0.0746436)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819605,0.0478658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4637,-0.00523572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202971,-0.0410257) , 
4, -2.14193, 0, 0, 0.305401,-0.136647) , 
4, -0.617357, 0, 0, 0.398156,-0.0669192)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765699,0.0402773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526708,0.00164233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195824,-0.0393422) , 
4, -1.94927, 0, 0, 0.308039,-0.127907) , 
0, 1.14286, 0, 0, 0.398156,-0.060521)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819605,0.0419292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4637,-0.00475266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202971,-0.0349682) , 
4, -2.14193, 0, 0, 0.305401,-0.11364) , 
4, -0.617357, 0, 0, 0.398156,-0.054719)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765699,0.035638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65616,0.0372631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280939,-0.0259409) , 
6, -0.449319, 0, 0, 0.308039,-0.107035) , 
0, 1.14286, 0, 0, 0.398156,-0.0494989)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734558,0.0244497) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308838,-0.0153337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0919216,-0.0595261) , 
0, 0.142857, 0, 0, 0.260121,-0.114582) , 
4, -1.23333, 0, 0, 0.398156,-0.0448293)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728056,0.0264999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543625,0.0208474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259857,-0.0246322) , 
6, -1.06389, 0, 0, 0.287413,-0.0986663) , 
1, -0.472739, 0, 0, 0.398156,-0.0401801)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765699,0.0305313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526708,0.00320548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195824,-0.028764) , 
4, -1.94927, 0, 0, 0.308039,-0.0829011) , 
0, 1.14286, 0, 0, 0.398156,-0.0364322)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819605,0.0325273) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329533,-0.0106899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122549,-0.0442344) , 
7, 96.4172, 1, 0, 0.305401,-0.0739743) , 
4, -0.617357, 0, 0, 0.398156,-0.0329451)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765699,0.0273862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65616,0.0338614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280939,-0.018735) , 
6, -0.449319, 0, 0, 0.308039,-0.0702665) , 
0, 1.14286, 0, 0, 0.398156,-0.0301541)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656244,0.015293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288529,-0.0129115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119221,-0.0382) , 
7, 94.5021, 1, 0, 0.256316,-0.0841004) , 
1, -1.00707, 0, 0, 0.398156,-0.0273171)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.0407918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00986895) , 
0, 1.14286, 0, 0, 0.429169,0.000302728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0439119) , 
7, 96.4172, 1, 0, 0.398156,-0.0248557)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.0379961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00897304) , 
0, 1.14286, 0, 0, 0.429169,0.000355535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0413474) , 
7, 96.4172, 1, 0, 0.398156,-0.0228349)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0502683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.812321,0.0232526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282589,-0.0147967) , 
4, -0.617357, 0, 0, 0.377091,-0.0381721) , 
5, 0.135771, 0, 0, 0.398156,-0.020982)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.0349452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00749754) , 
0, 1.14286, 0, 0, 0.429169,0.00225416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.038931) , 
7, 96.4172, 1, 0, 0.398156,-0.0190763)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0463356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409138,-0.00293606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103895,-0.0416683) , 
7, 96.4172, 1, 0, 0.377091,-0.0332836) , 
5, 0.135771, 0, 0, 0.398156,-0.017555)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.0107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274888,-0.00701783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0631967,-0.0544448) , 
0, 0.142857, 0, 0, 0.224708,-0.064015) , 
4, -1.8493, 0, 0, 0.398156,-0.0162485)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0416781) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390828,-0.00235278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25199,-0.0353368) , 
7, 85.0723, 0, 0, 0.377091,-0.0283132) , 
5, 0.135771, 0, 0, 0.398156,-0.0143077)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.032615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00602534) , 
0, 1.14286, 0, 0, 0.429169,0.00522744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0351055) , 
7, 96.4172, 1, 0, 0.398156,-0.0132523)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.038654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390828,-0.0019087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25199,-0.0332357) , 
7, 85.0723, 0, 0, 0.377091,-0.0251035) , 
5, 0.135771, 0, 0, 0.398156,-0.0122427)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.00614089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.0313285) , 
7, 84.888, 0, 0, 0.429169,0.00585724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0333354) , 
7, 96.4172, 1, 0, 0.398156,-0.0113609)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45508,0.00245307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196367,-0.0201372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0736724) , 
4, -3.24734, 0, 0, 0.114017,-0.12185) , 
0, 0.142857, 0, 0, 0.398156,-0.0108825)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656244,0.0119332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.287111,-0.00600559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.087998,-0.0454432) , 
4, -4.45673, 0, 0, 0.256316,-0.045055) , 
1, -1.00707, 0, 0, 0.398156,-0.00948726)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.0298899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00461152) , 
0, 1.14286, 0, 0, 0.429169,0.00743397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0312835) , 
7, 96.4172, 1, 0, 0.398156,-0.00836608)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0359925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399798,0.0033911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335475,-0.0174693) , 
7, 89.7993, 0, 0, 0.377091,-0.0194056) , 
5, 0.135771, 0, 0, 0.398156,-0.0077828)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.0062263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.0286727) , 
7, 84.888, 0, 0, 0.429169,0.00764539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0299691) , 
7, 96.4172, 1, 0, 0.398156,-0.00725169)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.00948079) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274888,-0.00422853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0631967,-0.047078) , 
0, 0.142857, 0, 0, 0.224708,-0.0432088) , 
4, -1.8493, 0, 0, 0.398156,-0.00709584)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0326844) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596302,0.0129725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310659,-0.00967291) , 
3, 0.294479, 0, 0, 0.377091,-0.016488) , 
5, 0.135771, 0, 0, 0.398156,-0.00610471)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.00616544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.0270686) , 
7, 84.888, 0, 0, 0.429169,0.00826451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0284075) , 
7, 96.4172, 1, 0, 0.398156,-0.00550321)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656244,0.0103705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303179,-0.00261368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127529,-0.0281234) , 
3, -1.23299, 0, 0, 0.256316,-0.0341555) , 
1, -1.00707, 0, 0, 0.398156,-0.00547488)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.00579481) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795419,0.0165995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23961,-0.0197877) , 
1, -0.218181, 0, 0, 0.354676,-0.0580505) , 
7, 89.7993, 0, 0, 0.398156,-0.00488762)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.0267605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00346207) , 
0, 1.14286, 0, 0, 0.429169,0.00820521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0270977) , 
7, 96.4172, 1, 0, 0.398156,-0.00462518)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0307904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399798,0.00345658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335475,-0.0146814) , 
7, 89.7993, 0, 0, 0.377091,-0.0139105) , 
5, 0.135771, 0, 0, 0.398156,-0.00435135)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451178,0.0045335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336712,-0.00276031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159504,-0.0417141) , 
5, -4.99167, 0, 0, 0.270042,-0.0607097) , 
6, -5.76793, 0, 0, 0.398156,-0.00410719)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45508,0.00273905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174117,-0.0142598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0221734,-0.0617472) , 
5, -4.52385, 0, 0, 0.114017,-0.0824568) , 
0, 0.142857, 0, 0, 0.398156,-0.0036899)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.00591729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.0239586) , 
7, 84.888, 0, 0, 0.429169,0.00901084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0258047) , 
7, 96.4172, 1, 0, 0.398156,-0.00311223)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0276306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596302,0.0112524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310659,-0.0077661) , 
3, 0.294479, 0, 0, 0.377091,-0.0116848) , 
5, 0.135771, 0, 0, 0.398156,-0.00324681)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.0252188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00300932) , 
0, 1.14286, 0, 0, 0.429169,0.00824639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0244073) , 
7, 96.4172, 1, 0, 0.398156,-0.00291183)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.00538137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795419,0.0134562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23961,-0.0167468) , 
1, -0.218181, 0, 0, 0.354676,-0.0478563) , 
7, 89.7993, 0, 0, 0.398156,-0.00277524)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900442,0.0328925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372611,-0.00128883) , 
4, 0.235198, 0, 0, 0.424622,0.00631799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0405936) , 
4, -4.92916, 0, 0, 0.398156,-0.00268065)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0257865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409138,0.000260865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103895,-0.0279109) , 
7, 96.4172, 1, 0, 0.377091,-0.0100795) , 
5, 0.135771, 0, 0, 0.398156,-0.00232353)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.00509478) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359807,-0.00434476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335804,-0.0300162) , 
6, -2.05665, 1, 0, 0.354676,-0.0440284) , 
7, 89.7993, 0, 0, 0.398156,-0.00228913)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451178,0.00411821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378206,-0.00253737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0460674,-0.0528839) , 
4, -3.69721, 0, 0, 0.270042,-0.0490665) , 
6, -5.76793, 0, 0, 0.398156,-0.00223415)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45508,0.00261284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228949,-7.5008e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0632304,-0.0421321) , 
5, -2.39468, 0, 0, 0.114017,-0.0671927) , 
0, 0.142857, 0, 0, 0.398156,-0.00184998)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.0054477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.0216662) , 
7, 84.888, 0, 0, 0.429169,0.00846344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0225307) , 
7, 96.4172, 1, 0, 0.398156,-0.00150249)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.00466799) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359807,-0.00353799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335804,-0.0280049) , 
6, -2.05665, 1, 0, 0.354676,-0.0390478) , 
7, 89.7993, 0, 0, 0.398156,-0.00172407)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.023446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409138,0.000302281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103895,-0.0257672) , 
7, 96.4172, 1, 0, 0.377091,-0.00866332) , 
5, 0.135771, 0, 0, 0.398156,-0.00170455)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656244,0.00811627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282549,0.0164295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251595,-0.0090952) , 
2, -2.02691, 1, 0, 0.256316,-0.0215988) , 
1, -1.00707, 0, 0, 0.398156,-0.0017083)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451178,0.00376372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336712,-0.000762533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159504,-0.0355226) , 
5, -4.99167, 0, 0, 0.270042,-0.0427399) , 
6, -5.76793, 0, 0, 0.398156,-0.00152013)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45508,0.00235398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118012,-0.014736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105948,-0.0372704) , 
6, -4.06481, 1, 0, 0.114017,-0.0583751) , 
0, 0.142857, 0, 0, 0.398156,-0.0013712)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.00452686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429349,-0.000594351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210434,-0.0259624) , 
6, -5.37179, 0, 0, 0.354676,-0.0358989) , 
7, 89.7993, 0, 0, 0.398156,-0.0010907)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.0220079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00224827) , 
0, 1.14286, 0, 0, 0.429169,0.00772266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0206675) , 
7, 96.4172, 1, 0, 0.398156,-0.00112655)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900442,0.0300062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372611,-0.000940803) , 
4, 0.235198, 0, 0, 0.424622,0.0060283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0359606) , 
4, -4.92916, 0, 0, 0.398156,-0.00112562)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0215781) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392774,0.000926234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276726,-0.0174173) , 
7, 86.0177, 0, 0, 0.377091,-0.00721086) , 
5, 0.135771, 0, 0, 0.398156,-0.000931706)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465161,0.00821114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350858,-0.00903232) , 
7, 89.6882, 0, 0, 0.423036,0.00628186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123404,-0.0229013) , 
7, 97.3626, 1, 0, 0.398156,-0.000996009)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.00438589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.0181436) , 
7, 84.888, 0, 0, 0.429169,0.00655238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0188583) , 
7, 96.4172, 1, 0, 0.398156,-0.00120104)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0197636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387593,-0.0040069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0193589) , 
2, -2.0748, 0, 0, 0.377091,-0.00709089) , 
5, 0.135771, 0, 0, 0.398156,-0.00137487)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900442,0.0288491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372611,-0.000945228) , 
4, 0.235198, 0, 0, 0.424622,0.00541657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0348554) , 
4, -4.92916, 0, 0, 0.398156,-0.00130016)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45508,0.0020749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228949,0.00380342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0632304,-0.0375752) , 
5, -2.39468, 0, 0, 0.114017,-0.0498418) , 
0, 0.142857, 0, 0, 0.398156,-0.00109244)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75742,0.0126149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28692,-0.00686411) , 
1, -0.360519, 0, 0, 0.410316,-0.00804137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0189914) , 
2, -2.02691, 0, 0, 0.398156,-0.000863345)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427753,-0.00046182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387454,0.0242109) , 
2, -1.74654, 0, 0, 0.424622,0.00540248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.033137) , 
4, -4.92916, 0, 0, 0.398156,-0.000796479)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465161,0.00745033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350858,-0.00821413) , 
7, 89.6882, 0, 0, 0.423036,0.00568137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123404,-0.0210763) , 
7, 97.3626, 1, 0, 0.398156,-0.00073451)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451178,0.00309597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336712,0.000315657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159504,-0.0318398) , 
5, -4.99167, 0, 0, 0.270042,-0.0332629) , 
6, -5.76793, 0, 0, 0.398156,-0.000930038)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0180363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387593,-0.00358409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0177866) , 
2, -2.0748, 0, 0, 0.377091,-0.00597532) , 
5, 0.135771, 0, 0, 0.398156,-0.000847681)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656244,0.00659522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289828,0.00286936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216974,-0.0131978) , 
7, 91.6711, 1, 0, 0.256316,-0.0160404) , 
1, -1.00707, 0, 0, 0.398156,-0.000815806)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608361,0.00827878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476431,0.0123241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298827,-0.00767509) , 
5, -1.22963, 0, 0, 0.335016,-0.0115036) , 
3, 0.294479, 0, 0, 0.398156,-0.000719746)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.0041111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.016811) , 
7, 84.888, 0, 0, 0.429169,0.00613625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0171561) , 
7, 96.4172, 1, 0, 0.398156,-0.000629213)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.00525442) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360065,0.00928162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189154,-0.00985204) , 
2, 0.145269, 0, 0, 0.224708,-0.0169342) , 
4, -1.8493, 0, 0, 0.398156,-0.00082543)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75742,0.0111142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28692,-0.00616222) , 
1, -0.360519, 0, 0, 0.410316,-0.00733369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0176978) , 
2, -2.02691, 0, 0, 0.398156,-0.000660782)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432733,-0.00100913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369655,0.0171673) , 
2, -1.40962, 0, 0, 0.424622,0.00488961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0309088) , 
4, -4.92916, 0, 0, 0.398156,-0.000610134)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.00356826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359807,0.000121152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335804,-0.0283484) , 
6, -2.05665, 1, 0, 0.354676,-0.0264057) , 
7, 89.7993, 0, 0, 0.398156,-0.000569736)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440268,0.00267148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323977,0.0190306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263711,-0.0166773) , 
5, -6.80071, 1, 0, 0.277401,-0.0322481) , 
5, -4.64315, 0, 0, 0.398156,-0.000624002)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.0178514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00173473) , 
0, 1.14286, 0, 0, 0.429169,0.00582802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0166127) , 
7, 96.4172, 1, 0, 0.398156,-0.000614123)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548573,0.0127059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380964,-0.00527217) , 
5, -0.839246, 0, 0, 0.410316,-0.00674746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0161512) , 
2, -2.02691, 0, 0, 0.398156,-0.000627468)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900442,0.0250401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372611,-0.000686135) , 
4, 0.235198, 0, 0, 0.424622,0.00462074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.030044) , 
4, -4.92916, 0, 0, 0.398156,-0.000615132)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548573,0.0115182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380964,-0.00491678) , 
5, -0.839246, 0, 0, 0.410316,-0.00646392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0158193) , 
2, -2.02691, 0, 0, 0.398156,-0.000488646)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.0033695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359807,0.000393932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335804,-0.0276522) , 
6, -2.05665, 1, 0, 0.354676,-0.024607) , 
7, 89.7993, 0, 0, 0.398156,-0.000486995)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.00370649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.0150728) , 
7, 84.888, 0, 0, 0.429169,0.00554576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.015944) , 
7, 96.4172, 1, 0, 0.398156,-0.000542503)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.00483377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360065,0.00838348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189154,-0.00906063) , 
2, 0.145269, 0, 0, 0.224708,-0.015239) , 
4, -1.8493, 0, 0, 0.398156,-0.000717547)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900442,0.0235096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355092,-0.00371701) , 
4, 0.239617, 0, 0, 0.410316,-0.00633363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0151988) , 
2, -2.02691, 0, 0, 0.398156,-0.000569254)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432733,-0.000881681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369655,0.0152466) , 
2, -1.40962, 0, 0, 0.424622,0.00446564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0292316) , 
4, -4.92916, 0, 0, 0.398156,-0.000534922)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440268,0.00252415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418619,-0.0237171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221389,0.000186852) , 
1, -1.24507, 0, 0, 0.277401,-0.029682) , 
5, -4.64315, 0, 0, 0.398156,-0.000498784)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465161,0.00606974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350858,-0.00683087) , 
7, 89.6882, 0, 0, 0.423036,0.00439694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123404,-0.0177008) , 
7, 97.3626, 1, 0, 0.398156,-0.000556602)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.00447821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360065,0.00780931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189154,-0.00850984) , 
2, 0.145269, 0, 0, 0.224708,-0.0141238) , 
4, -1.8493, 0, 0, 0.398156,-0.000711425)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635401,0.00500886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238378,-0.0072614) , 
1, -1.11993, 0, 0, 0.410316,-0.00616759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0148273) , 
2, -2.02691, 0, 0, 0.398156,-0.000568123)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440268,0.00232319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418619,-0.0222212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221389,0.000346897) , 
1, -1.24507, 0, 0, 0.277401,-0.0273033) , 
5, -4.64315, 0, 0, 0.398156,-0.000497892)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432733,-0.000843988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369655,0.0139124) , 
2, -1.40962, 0, 0, 0.424622,0.00398523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.02745) , 
4, -4.92916, 0, 0, 0.398156,-0.000549198)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548573,0.0103491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380964,-0.00442184) , 
5, -0.839246, 0, 0, 0.410316,-0.00562929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0134985) , 
2, -2.02691, 0, 0, 0.398156,-0.000511313)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453208,0.0016714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317023,0.0175382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0393017,-0.0504091) , 
3, -0.951399, 0, 0, 0.141087,-0.0338299) , 
4, -3.69721, 0, 0, 0.398156,-0.000500817)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.00340087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.0140027) , 
7, 84.888, 0, 0, 0.429169,0.00491504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.014105) , 
7, 96.4172, 1, 0, 0.398156,-0.000282961)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440268,0.00211328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323977,0.017289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263711,-0.0138648) , 
5, -6.80071, 1, 0, 0.277401,-0.0247785) , 
5, -4.64315, 0, 0, 0.398156,-0.000456991)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656244,0.00486364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289828,0.00402721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216974,-0.0120528) , 
7, 91.6711, 1, 0, 0.256316,-0.0111569) , 
1, -1.00707, 0, 0, 0.398156,-0.000456173)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.00288378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359807,0.00143591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335804,-0.0270667) , 
6, -2.05665, 1, 0, 0.354676,-0.0206386) , 
7, 89.7993, 0, 0, 0.398156,-0.000405086)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900442,0.0219736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355092,-0.00327745) , 
4, 0.239617, 0, 0, 0.410316,-0.00531676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0128299) , 
2, -2.02691, 0, 0, 0.398156,-0.000455435)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0136509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556311,-0.0162677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363596,0.000267182) , 
2, 0.744082, 0, 0, 0.377091,-0.00414131) , 
5, 0.135771, 0, 0, 0.398156,-0.000425084)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663851,0.00598176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253036,-0.00291704) , 
4, -1.6984, 0, 0, 0.424622,0.00377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0262251) , 
4, -4.92916, 0, 0, 0.398156,-0.000429007)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548573,0.00930714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380964,-0.00403173) , 
5, -0.839246, 0, 0, 0.410316,-0.00511259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0127339) , 
2, -2.02691, 0, 0, 0.398156,-0.000316052)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465161,0.00548009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350858,-0.00613898) , 
7, 89.6882, 0, 0, 0.423036,0.00396259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123404,-0.0160235) , 
7, 97.3626, 1, 0, 0.398156,-0.000320273)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900442,0.0207135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372611,-0.000531228) , 
4, 0.235198, 0, 0, 0.424622,0.00346653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0251472) , 
4, -4.92916, 0, 0, 0.398156,-0.000470546)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635401,0.00437405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238378,-0.00625383) , 
1, -1.11993, 0, 0, 0.410316,-0.00508152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0125315) , 
2, -2.02691, 0, 0, 0.398156,-0.000372967)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440268,0.00206137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418619,-0.0204083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221389,0.00101111) , 
1, -1.24507, 0, 0, 0.277401,-0.0233761) , 
5, -4.64315, 0, 0, 0.398156,-0.000320324)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448517,0.00301414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258031,-0.0126929) , 
7, 84.888, 0, 0, 0.429169,0.00420426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0129339) , 
7, 96.4172, 1, 0, 0.398156,-0.000381988)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45508,0.00137339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114187,0.00184667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.113746,-0.0312837) , 
6, -4.59037, 1, 0, 0.114017,-0.0302798) , 
0, 0.142857, 0, 0, 0.398156,-0.000523603)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453208,0.00144325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317023,0.0155291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0393017,-0.0479444) , 
3, -0.951399, 0, 0, 0.141087,-0.0285631) , 
4, -3.69721, 0, 0, 0.398156,-0.000394318)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548573,0.0083751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380964,-0.00363418) , 
5, -0.839246, 0, 0, 0.410316,-0.00452458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0115051) , 
2, -2.02691, 0, 0, 0.398156,-0.000205954)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440268,0.00195688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418619,-0.0186137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221389,0.000694709) , 
1, -1.24507, 0, 0, 0.277401,-0.0217549) , 
5, -4.64315, 0, 0, 0.398156,-0.000216148)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472272,-0.0063365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504641,0.0281847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368345,-0.000760472) , 
5, -0.911892, 0, 0, 0.378363,0.00638113) , 
6, -2.23297, 0, 0, 0.398156,-0.000278)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42593,-0.00293125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422669,0.00694489) , 
5, -3.53155, 0, 0, 0.424622,0.00331192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0237782) , 
4, -4.92916, 0, 0, 0.398156,-0.000302831)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431464,0.001519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274709,-0.0166376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189646,0.0159818) , 
2, -0.721176, 0, 0, 0.245361,-0.0270447) , 
7, 94.5264, 1, 0, 0.398156,-0.000249315)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.00366161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23622,-0.00777026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20282,0.00923669) , 
6, -5.98046, 0, 0, 0.224708,-0.01083) , 
4, -1.8493, 0, 0, 0.398156,-0.000302531)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595679,-0.0109358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423432,0.00280407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0825259,-0.0283268) , 
4, -4.40311, 0, 0, 0.384675,0.00295156) , 
2, 0.8125, 0, 0, 0.398156,-0.000277838)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75742,0.00769895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28692,-0.00417004) , 
1, -0.360519, 0, 0, 0.410316,-0.00475602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0123084) , 
2, -2.02691, 0, 0, 0.398156,-0.000200508)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.00249078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359807,0.00225541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335804,-0.0262711) , 
6, -2.05665, 1, 0, 0.354676,-0.017042) , 
7, 89.7993, 0, 0, 0.398156,-0.000183191)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440268,0.00192132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323977,0.0162759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263711,-0.012457) , 
5, -6.80071, 1, 0, 0.277401,-0.0213846) , 
5, -4.64315, 0, 0, 0.398156,-0.000241457)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451178,0.00199748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545794,-0.0228809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188111,0.00216866) , 
4, -1.8493, 0, 0, 0.270042,-0.0193002) , 
6, -5.76793, 0, 0, 0.398156,-0.000257182)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431464,0.00144106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274709,-0.0158367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189646,0.0142362) , 
2, -0.721176, 0, 0, 0.245361,-0.0260703) , 
7, 94.5264, 1, 0, 0.398156,-0.000325114)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608361,0.00534113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354602,-0.0132022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327021,0.00295408) , 
6, -3.39675, 0, 0, 0.335016,-0.00695282) , 
3, 0.294479, 0, 0, 0.398156,-0.000366872)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0117858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556311,-0.0157779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363596,0.000425485) , 
2, 0.744082, 0, 0, 0.377091,-0.00343186) , 
5, 0.135771, 0, 0, 0.398156,-0.000293687)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.0035605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239971,-0.0107145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215966,0.00273403) , 
1, -1.65788, 0, 0, 0.224708,-0.0105101) , 
4, -1.8493, 0, 0, 0.398156,-0.000307895)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426199,0.00133341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330091,0.0167059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195281,-0.0239438) , 
5, -6.9549, 1, 0, 0.24539,-0.028859) , 
5, -5.32585, 0, 0, 0.398156,-0.000321387)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42593,-0.00264286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422669,0.00628278) , 
5, -3.53155, 0, 0, 0.424622,0.00303383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0225472) , 
4, -4.92916, 0, 0, 0.398156,-0.000329574)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440268,0.00180485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418619,-0.0174593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221389,0.000674343) , 
1, -1.24507, 0, 0, 0.277401,-0.0202443) , 
5, -4.64315, 0, 0, 0.398156,-0.000275386)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656244,0.00409801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291358,-0.00932798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223621,0.0060638) , 
1, -1.8234, 0, 0, 0.256316,-0.00908571) , 
1, -1.00707, 0, 0, 0.398156,-0.000326713)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846808,0.0139453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326511,-0.00146088) , 
0, 1.14286, 0, 0, 0.429169,0.00370041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137614,-0.0115286) , 
7, 96.4172, 1, 0, 0.398156,-0.000308559)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0111775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556311,-0.0151883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363596,0.000413347) , 
2, 0.744082, 0, 0, 0.377091,-0.00327851) , 
5, 0.135771, 0, 0, 0.398156,-0.000315731)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451178,0.0018538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545794,-0.0214419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188111,0.0020213) , 
4, -1.8493, 0, 0, 0.270042,-0.0180963) , 
6, -5.76793, 0, 0, 0.398156,-0.000326053)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453208,0.00128513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317023,0.0140596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0393017,-0.0461764) , 
3, -0.951399, 0, 0, 0.141087,-0.0253986) , 
4, -3.69721, 0, 0, 0.398156,-0.000381497)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900442,0.0190577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355092,-0.00261523) , 
4, 0.239617, 0, 0, 0.410316,-0.00403774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.0102785) , 
2, -2.02691, 0, 0, 0.398156,-0.000210059)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440268,0.00180771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418619,-0.0164979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221389,0.00022395) , 
1, -1.24507, 0, 0, 0.277401,-0.0198343) , 
5, -4.64315, 0, 0, 0.398156,-0.00019578)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417966,-0.00290663) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49523,0.0138602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286545,-0.00508536) , 
5, -4.56129, 0, 0, 0.377428,0.0110805) , 
5, -3.27774, 0, 0, 0.398156,-0.000248386)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.0022139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359807,0.00243259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335804,-0.0251113) , 
6, -2.05665, 1, 0, 0.354676,-0.0153379) , 
7, 89.7993, 0, 0, 0.398156,-0.000264713)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.00332938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23622,-0.00724388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20282,0.0088277) , 
6, -5.98046, 0, 0, 0.224708,-0.00976151) , 
4, -1.8493, 0, 0, 0.398156,-0.000308747)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431464,0.00135363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274709,-0.0148818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189646,0.0130172) , 
2, -0.721176, 0, 0, 0.245361,-0.0241141) , 
7, 94.5264, 1, 0, 0.398156,-0.000281238)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724731,0.0107876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556311,-0.0144717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363596,0.00037949) , 
2, 0.744082, 0, 0, 0.377091,-0.003167) , 
5, 0.135771, 0, 0, 0.398156,-0.000320828)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642597,0.00740079) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423931,0.00474358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320113,-0.00637576) , 
5, -2.59504, 0, 0, 0.363144,-0.00451715) , 
3, 0.597982, 0, 0, 0.398156,-0.000328874)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548573,0.00782748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380964,-0.00333211) , 
5, -0.839246, 0, 0, 0.410316,-0.00396051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.00989134) , 
2, -2.02691, 0, 0, 0.398156,-0.000263597)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656244,0.00387206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289828,0.00452153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216974,-0.0111664) , 
7, 91.6711, 1, 0, 0.256316,-0.0084224) , 
1, -1.00707, 0, 0, 0.398156,-0.000264089)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.0023229) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359807,0.00194795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335804,-0.0243529) , 
6, -2.05665, 1, 0, 0.354676,-0.0158893) , 
7, 89.7993, 0, 0, 0.398156,-0.000238204)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42593,-0.00249447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422669,0.00585321) , 
5, -3.53155, 0, 0, 0.424622,0.00276212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769236,-0.0211089) , 
4, -4.92916, 0, 0, 0.398156,-0.00028504)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548573,0.00781056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380964,-0.00329688) , 
5, -0.839246, 0, 0, 0.410316,-0.00385118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.00972756) , 
2, -2.02691, 0, 0, 0.398156,-0.00023745)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426199,0.00120309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27657,0.00719758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202309,-0.0305382) , 
7, 91.558, 1, 0, 0.24539,-0.0254362) , 
5, -5.32585, 0, 0, 0.398156,-0.000240131)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421229,0.00223615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359807,0.00162499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335804,-0.0227589) , 
6, -2.05665, 1, 0, 0.354676,-0.015273) , 
7, 89.7993, 0, 0, 0.398156,-0.00022742)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643954,0.00321888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23622,-0.00690454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20282,0.00818679) , 
6, -5.98046, 0, 0, 0.224708,-0.00935764) , 
4, -1.8493, 0, 0, 0.398156,-0.000270947)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451178,0.00188358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545794,-0.0201223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188111,0.0014538) , 
4, -1.8493, 0, 0, 0.270042,-0.0179058) , 
6, -5.76793, 0, 0, 0.398156,-0.000245949)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45508,0.00113759) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114187,0.00320792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.113746,-0.0282) , 
6, -4.59037, 1, 0, 0.114017,-0.0238968) , 
0, 0.142857, 0, 0, 0.398156,-0.000302328)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451178,0.00178795) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456109,0.00687011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.131047,-0.0210871) , 
2, -0.216972, 0, 0, 0.270042,-0.016894) , 
6, -5.76793, 0, 0, 0.398156,-0.000208458)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900442,0.0180921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355092,-0.00244976) , 
4, 0.239617, 0, 0, 0.410316,-0.00379234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289904,0.00983961) , 
2, -2.02691, 0, 0, 0.398156,-0.000161133)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
