// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Wed May  7 16:11:42 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 1509
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1509" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
ttbar_fake_SS_top_mass_blep_qq ttbar_fake_SS_top_mass_blep_qq ttbar_fake_SS_top_mass_blep_qq ttbar_fake_SS_top_mass_blep_qq                                    'F'    [61.0708503723,1876.36328125]
Match_ttW_SS_Bbq              Match_ttW_SS_Bbq              Match_ttW_SS_Bbq              Match_ttW_SS_Bbq                                                'F'    [-10.8003396988,2.10265040398]
Match_ttbar_fake_SS_Bqq       Match_ttbar_fake_SS_Bqq       Match_ttbar_fake_SS_Bqq       Match_ttbar_fake_SS_Bqq                                         'F'    [-15.7892742157,2.14845848083]
met_ld                        met_ld                        met_ld                        met_ld                                                          'F'    [0.0467127002776,2.72799015045]
jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex                                         'F'    [-1,0.999995946884]
MT_of_everything              MT_of_everything              MT_of_everything              MT_of_everything                                                'F'    [159.436035156,1627.85742188]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "ttbar_fake_SS_top_mass_blep_qq", "Match_ttW_SS_Bbq", "Match_ttbar_fake_SS_Bqq", "met_ld", "jets_by_CSV_2_btagCombinedSecVertex", "MT_of_everything" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 61.0708503723145;
      fVmax[0] = 1876.36328125;
      fVmin[1] = -10.8003396987915;
      fVmax[1] = 2.10265040397644;
      fVmin[2] = -15.7892742156982;
      fVmax[2] = 2.14845848083496;
      fVmin[3] = 0.0467127002775669;
      fVmax[3] = 2.72799015045166;
      fVmin[4] = -1;
      fVmax[4] = 0.999995946884155;
      fVmin[5] = 159.43603515625;
      fVmax[5] = 1627.857421875;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.0358839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601093,0.0202186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228873,-0.0542254) , 
1, -0.377237, 0, 0, 0.319574,-0.180426) , 
5, 369.211, 0, 0, 0.500331,0.000331345)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64938,0.0284912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39738,-0.0187786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223919,-0.0531798) , 
2, -0.696789, 1, 0, 0.287781,-0.202126) , 
2, -2.12243, 1, 0, 0.500331,0.000292251)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.0311312) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601093,0.0180562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228873,-0.0473838) , 
1, -0.377237, 0, 0, 0.319574,-0.156084) , 
5, 369.211, 0, 0, 0.500331,0.000253692)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713344,0.0362338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675439,0.0308534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310914,-0.0324407) , 
1, 0.126811, 0, 0, 0.356984,-0.120589) , 
2, -3.83079, 1, 0, 0.500331,0.000206748)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763092,0.0454846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682432,0.0272806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304187,-0.0324902) , 
5, 439.135, 0, 0, 0.405235,-0.0810236) , 
4, 0.619044, 0, 0, 0.500331,0.000190369)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620352,0.0181681) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3213,-0.0258268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152381,-0.0550989) , 
1, -1.47201, 0, 0, 0.24846,-0.186581) , 
2, -1.26825, 1, 0, 0.500331,0.000180872)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.0248992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477143,-0.00099481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182045,-0.0470446) , 
1, -1.13754, 0, 0, 0.319574,-0.122728) , 
5, 369.211, 0, 0, 0.500331,0.000127383)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730126,0.0348601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699552,0.0258107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309406,-0.0279751) , 
0, 233.956, 0, 0, 0.393792,-0.078291) , 
4, 0.523806, 0, 0, 0.500331,7.79327e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713344,0.0272561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522059,0.00707976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0296339) , 
0, 152.459, 0, 0, 0.356984,-0.0878592) , 
2, -3.83079, 1, 0, 0.500331,7.86943e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763092,0.0357543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490931,-0.00115237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153025,-0.0486806) , 
5, 299.286, 0, 0, 0.405235,-0.0614647) , 
4, 0.619044, 0, 0, 0.500331,6.92121e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.0199755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.854167,0.0527605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283073,-0.0257558) , 
1, 0.763217, 0, 0, 0.319574,-0.0960546) , 
5, 369.211, 0, 0, 0.500331,4.24446e-05)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815884,0.0416377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729927,0.024916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343424,-0.0190613) , 
0, 233.956, 0, 0, 0.429383,-0.0433263) , 
4, 0.80952, 0, 0, 0.500331,3.59212e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.0264025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558091,0.00675261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272374,-0.0333792) , 
1, -1.15663, 0, 0, 0.410643,-0.0631207) , 
3, 0.557432, 0, 0, 0.500331,6.76342e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620352,0.0126476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44,0.00419618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226545,-0.031293) , 
0, 155.293, 0, 0, 0.24846,-0.123364) , 
2, -1.26825, 1, 0, 0.500331,4.7687e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00939822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277551,-0.0242783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0625,-0.0592542) , 
1, -1.90738, 0, 0, 0.217009,-0.148587) , 
5, 299.286, 0, 0, 0.500331,1.62182e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730126,0.0252411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,0.0175419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32375,-0.0204492) , 
3, 0.671565, 0, 0, 0.393792,-0.0532026) , 
4, 0.523806, 0, 0, 0.500331,-2.74545e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620352,0.0110561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355556,-0.00281782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224181,-0.0293545) , 
2, -0.775933, 1, 0, 0.24846,-0.106357) , 
2, -1.26825, 1, 0, 0.500331,-1.68911e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.0220514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484012,-5.13591e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246753,-0.0378043) , 
1, -1.69379, 0, 0, 0.410643,-0.0512587) , 
3, 0.557432, 0, 0, 0.500331,-3.77051e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815884,0.0335602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729927,0.0199307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343424,-0.0151073) , 
0, 233.956, 0, 0, 0.429383,-0.0326816) , 
4, 0.80952, 0, 0, 0.500331,-4.26013e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00784403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347826,-0.00300835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183824,-0.035819) , 
5, 285.464, 0, 0, 0.217009,-0.120792) , 
5, 299.286, 0, 0, 0.500331,-9.41964e-06)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610422,0.0133151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864407,0.0424834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329193,-0.0206362) , 
1, 0.794071, 0, 0, 0.374111,-0.0675614) , 
3, 0.429752, 0, 0, 0.500331,-3.66164e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713344,0.0170189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782609,0.0399923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334112,-0.014381) , 
0, 223.017, 0, 0, 0.356984,-0.0500624) , 
2, -3.83079, 1, 0, 0.500331,-2.87367e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691901,0.0177345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875,0.0460839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358343,-0.0137571) , 
3, 1.16998, 0, 0, 0.384697,-0.0465607) , 
4, 0.428569, 0, 0, 0.500331,-1.71454e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0432974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565753,0.00711459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337008,-0.0176033) , 
3, 0.422359, 0, 0, 0.459341,-0.0182674) , 
4, 0.904758, 0, 0, 0.500331,-8.02382e-07)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.0103156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819277,0.032588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323529,-0.0241221) , 
3, 0.941695, 0, 0, 0.392917,-0.0689575) , 
1, -1.58392, 0, 0, 0.500331,2.2135e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.0194035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56681,0.00767298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266223,-0.0209043) , 
1, -1.03687, 0, 0, 0.397183,-0.0343104) , 
5, 439.135, 0, 0, 0.500331,2.00268e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620352,0.00808762) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291667,-0.0360498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240964,-0.0143184) , 
5, 411.229, 0, 0, 0.24846,-0.0734264) , 
2, -1.26825, 1, 0, 0.500331,1.44007e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00621558) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233333,-0.0393542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208145,-0.0135145) , 
2, -2.03418, 1, 0, 0.217009,-0.0919207) , 
5, 299.286, 0, 0, 0.500331,5.50149e-06)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.00913793) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819277,0.0284051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323529,-0.0213895) , 
3, 0.941695, 0, 0, 0.392917,-0.0602381) , 
1, -1.58392, 0, 0, 0.500331,-8.12265e-06)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.0064628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641026,0.00770763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.028496) , 
0, 185.272, 0, 0, 0.332432,-0.0837672) , 
3, 0.302072, 0, 0, 0.500331,-7.73244e-06)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0574976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616333,0.0105566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363752,-0.0136706) , 
1, -1.13066, 0, 0, 0.477747,-0.0103957) , 
2, -9.81003, 1, 0, 0.500331,-2.09941e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580372,0.00563243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291892,-0.0119757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105634,-0.0382381) , 
1, -1.46449, 0, 0, 0.211009,-0.0858623) , 
2, -0.414075, 1, 0, 0.500331,6.29953e-06)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.015125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44898,-0.001514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214724,-0.0409743) , 
1, -2.23094, 0, 0, 0.410643,-0.0322236) , 
3, 0.557432, 0, 0, 0.500331,-1.8206e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0368053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748366,0.0157178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375826,-0.00879741) , 
0, 233.956, 0, 0, 0.459341,-0.013998) , 
4, 0.904758, 0, 0, 0.500331,-2.27239e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00566871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641026,0.00620196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0251627) , 
0, 185.272, 0, 0, 0.332432,-0.0718341) , 
3, 0.302072, 0, 0, 0.500331,6.5742e-06)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0535966) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510526,0.00345934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352349,-0.0239855) , 
1, -2.20843, 0, 0, 0.477747,-0.0087342) , 
2, -9.81003, 1, 0, 0.500331,-5.67788e-06)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.0149613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808696,0.0278913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347368,-0.0100402) , 
1, 0.514706, 0, 0, 0.397183,-0.0247617) , 
5, 439.135, 0, 0, 0.500331,1.63884e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.0129173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44898,-0.00110669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214724,-0.0362373) , 
1, -2.23094, 0, 0, 0.410643,-0.0266927) , 
3, 0.557432, 0, 0, 0.500331,2.76858e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580372,0.00475146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,-0.0319293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197674,-0.0143373) , 
4, 0.408754, 0, 0, 0.211009,-0.0703061) , 
2, -0.414075, 1, 0, 0.500331,1.84307e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00467914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233333,-0.0348515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208145,-0.00720663) , 
2, -2.03418, 1, 0, 0.217009,-0.0660918) , 
5, 299.286, 0, 0, 0.500331,8.21629e-06)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0329103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748366,0.0127836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375826,-0.00724592) , 
0, 233.956, 0, 0, 0.459341,-0.0115922) , 
4, 0.904758, 0, 0, 0.500331,-2.11231e-06)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.0070374) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819277,0.0206443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323529,-0.016273) , 
3, 0.941695, 0, 0, 0.392917,-0.0441387) , 
1, -1.58392, 0, 0, 0.500331,1.89928e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00484638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641026,0.00518771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0217599) , 
0, 185.272, 0, 0, 0.332432,-0.0595747) , 
3, 0.302072, 0, 0, 0.500331,1.6002e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.00645073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.895833,0.0325278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348624,-0.0138051) , 
3, 1.19688, 0, 0, 0.392917,-0.0403358) , 
1, -1.58392, 0, 0, 0.500331,5.37013e-06)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713344,0.0101426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641304,0.0228116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324691,-0.0101955) , 
0, 175.978, 0, 0, 0.356984,-0.0262796) , 
2, -3.83079, 1, 0, 0.500331,7.91533e-06)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610422,0.00729185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864407,0.0311297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329193,-0.0118568) , 
1, 0.794071, 0, 0, 0.374111,-0.0329745) , 
3, 0.429752, 0, 0, 0.500331,8.51167e-06)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0490549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510526,0.00293918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352349,-0.0201634) , 
1, -2.20843, 0, 0, 0.477747,-0.00677272) , 
2, -9.81003, 1, 0, 0.500331,1.13136e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580372,0.00391656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,-0.0286145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197674,-0.0110357) , 
4, 0.408754, 0, 0, 0.211009,-0.0560747) , 
2, -0.414075, 1, 0, 0.500331,2.6944e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00413778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511111,-0.0398753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315113,-0.00940336) , 
0, 307.411, 0, 0, 0.339888,-0.0519352) , 
4, 0.142855, 0, 0, 0.500331,1.82431e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00420213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460784,-0.00455461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174699,-0.0269929) , 
1, -1.31676, 0, 0, 0.332432,-0.0507016) , 
3, 0.302072, 0, 0, 0.500331,2.06102e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0283259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475887,0.001235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390977,-0.0178605) , 
1, -2.34313, 0, 0, 0.459341,-0.00912734) , 
4, 0.904758, 0, 0, 0.500331,8.526e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774566,0.0140857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896552,0.0361675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393665,-0.00572936) , 
1, 0.933771, 0, 0, 0.418745,-0.0154196) , 
0, 233.956, 0, 0, 0.500331,2.01203e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.00982571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44898,-0.000765646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214724,-0.0284661) , 
1, -2.23094, 0, 0, 0.410643,-0.0192253) , 
3, 0.557432, 0, 0, 0.500331,3.21962e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00360633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233333,-0.0318769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208145,-0.00253976) , 
2, -2.03418, 1, 0, 0.217009,-0.0487635) , 
5, 299.286, 0, 0, 0.500331,2.39622e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.046499) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756364,0.0156299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411866,-0.00537877) , 
1, -0.0528887, 0, 0, 0.477747,-0.00580634) , 
2, -9.81003, 1, 0, 0.500331,1.39088e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580372,0.00341742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,-0.026917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197674,-0.00888507) , 
4, 0.408754, 0, 0, 0.211009,-0.047787) , 
2, -0.414075, 1, 0, 0.500331,3.36514e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00366435) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641026,0.00502248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0172735) , 
0, 185.272, 0, 0, 0.332432,-0.043329) , 
3, 0.302072, 0, 0, 0.500331,2.55398e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863248,0.0258073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825581,0.0205537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419672,-0.00454144) , 
1, 0.428912, 0, 0, 0.469828,-0.00693768) , 
5, 648.91, 0, 0, 0.500331,1.71811e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.00484675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.895833,0.026613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348624,-0.0103406) , 
3, 1.19688, 0, 0, 0.392917,-0.0289099) , 
1, -1.58392, 0, 0, 0.500331,3.05042e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774566,0.011838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609836,0.00864762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350816,-0.0077975) , 
0, 159.775, 0, 0, 0.418745,-0.0124586) , 
0, 233.956, 0, 0, 0.500331,2.9432e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525467,0.00312954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613497,0.00135581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214286,-0.0253693) , 
3, 0.558918, 0, 0, 0.410876,-0.0421488) , 
1, -2.19835, 0, 0, 0.500331,2.92994e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610422,0.00543403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864407,0.0227935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329193,-0.00864925) , 
1, 0.794071, 0, 0, 0.374111,-0.0235163) , 
3, 0.429752, 0, 0, 0.500331,1.99465e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0433447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948276,0.0440778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457971,-0.00262638) , 
1, 1.02488, 0, 0, 0.477747,-0.00479242) , 
2, -9.81003, 1, 0, 0.500331,1.98738e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00317628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511111,-0.0383318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315113,-0.00584584) , 
0, 307.411, 0, 0, 0.339888,-0.0379827) , 
4, 0.142855, 0, 0, 0.500331,4.36789e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774566,0.0111987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710744,0.016419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384837,-0.00533204) , 
0, 184.451, 0, 0, 0.418745,-0.0115488) , 
0, 233.956, 0, 0, 0.500331,4.31378e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00313783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.0278288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307453,-0.00736623) , 
2, -7.42889, 1, 0, 0.332432,-0.0362055) , 
3, 0.302072, 0, 0, 0.500331,4.35753e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525467,0.00285868) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613497,0.000379412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214286,-0.0225046) , 
3, 0.558918, 0, 0, 0.410876,-0.038001) , 
1, -2.19835, 0, 0, 0.500331,3.99415e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774566,0.0106341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489385,0.000623714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182836,-0.0176977) , 
5, 284.507, 0, 0, 0.418745,-0.0108608) , 
0, 233.956, 0, 0, 0.500331,3.06796e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0227032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475887,0.00111254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390977,-0.0143772) , 
1, -2.34313, 0, 0, 0.459341,-0.00643392) , 
4, 0.904758, 0, 0, 0.500331,2.35947e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580372,0.0026551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,-0.0242253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197674,-0.00565612) , 
4, 0.408754, 0, 0, 0.211009,-0.0358353) , 
2, -0.414075, 1, 0, 0.500331,2.83106e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0409699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948276,0.0413059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457971,-0.00228847) , 
1, 1.02488, 0, 0, 0.477747,-0.0041335) , 
2, -9.81003, 1, 0, 0.500331,2.22427e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863248,0.021289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650919,0.00730763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401583,-0.00480296) , 
3, 0.587151, 0, 0, 0.469828,-0.00520056) , 
5, 648.91, 0, 0, 0.500331,4.16604e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00276703) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511111,-0.0364773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315113,-0.00451475) , 
0, 307.411, 0, 0, 0.339888,-0.0323773) , 
4, 0.142855, 0, 0, 0.500331,4.31025e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774566,0.00955311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609836,0.00700891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350816,-0.00619651) , 
0, 159.775, 0, 0, 0.418745,-0.00952523) , 
0, 233.956, 0, 0, 0.500331,4.20537e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00267935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.0264457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307453,-0.00581893) , 
2, -7.42889, 1, 0, 0.332432,-0.0303228) , 
3, 0.302072, 0, 0, 0.500331,3.95542e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.00373733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393782,0.0046536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3925,-0.0115203) , 
1, -2.02435, 0, 0, 0.392917,-0.0214937) , 
1, -1.58392, 0, 0, 0.500331,3.63367e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774566,0.0091277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734177,0.0187061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395756,-0.00402698) , 
3, 0.894547, 0, 0, 0.418745,-0.00904565) , 
0, 233.956, 0, 0, 0.500331,3.16833e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0200315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475887,0.00104727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390977,-0.0127034) , 
1, -2.34313, 0, 0, 0.459341,-0.0053612) , 
4, 0.904758, 0, 0, 0.500331,3.22267e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0386683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756364,0.0107603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411866,-0.00351348) , 
1, -0.0528887, 0, 0, 0.477747,-0.00354398) , 
2, -9.81003, 1, 0, 0.500331,3.42035e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00247184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.0243281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307453,-0.00536912) , 
2, -7.42889, 1, 0, 0.332432,-0.027701) , 
3, 0.302072, 0, 0, 0.500331,4.21295e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913043,0.0284704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698864,0.00654914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354167,-0.00535068) , 
5, 399.168, 0, 0, 0.480556,-0.00336641) , 
5, 788.759, 0, 0, 0.500331,3.83916e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.0226867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771635,0.0131212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386473,-0.00367498) , 
0, 185.272, 0, 0, 0.496899,0.00308379) , 
1, -4.04163, 1, 0, 0.500331,4.0461e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.00324336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595122,-0.0144839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286082,-2.52235e-05) , 
2, -5.64344, 1, 0, 0.392917,-0.018345) , 
1, -1.58392, 0, 0, 0.500331,4.32529e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580372,0.00209743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272727,0.0152898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198529,-0.0130463) , 
2, 1.17421, 0, 0, 0.211009,-0.0274702) , 
2, -0.414075, 1, 0, 0.500331,4.11915e-05)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913043,0.0270095) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766551,0.0103312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409367,-0.00335137) , 
1, -0.0528887, 0, 0, 0.480556,-0.00309949) , 
5, 788.759, 0, 0, 0.500331,3.15793e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610422,0.00362013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525926,-0.0170622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338028,-0.000812974) , 
2, -5.97756, 1, 0, 0.374111,-0.0148636) , 
3, 0.429752, 0, 0, 0.500331,3.54652e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.002184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511111,-0.0338264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315113,-0.0026773) , 
0, 307.411, 0, 0, 0.339888,-0.0249155) , 
4, 0.142855, 0, 0, 0.500331,3.33908e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00206336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233766,-0.0239756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203209,0.00857182) , 
2, -1.43964, 1, 0, 0.217009,-0.0259272) , 
5, 299.286, 0, 0, 0.500331,3.26462e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0365791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948276,0.0376015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457971,-0.00182241) , 
1, 1.02488, 0, 0, 0.477747,-0.00306504) , 
2, -9.81003, 1, 0, 0.500331,2.182e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580372,0.00196749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261905,-0.0257342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203509,-0.0040925) , 
5, 430.777, 0, 0, 0.211009,-0.0255511) , 
2, -0.414075, 1, 0, 0.500331,3.54282e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774566,0.00742385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423077,-0.00397223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382114,0.0167403) , 
0, 110.423, 0, 0, 0.418745,-0.0070673) , 
0, 233.956, 0, 0, 0.500331,2.97692e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.0197382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771635,0.0116244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386473,-0.00320806) , 
0, 185.272, 0, 0, 0.496899,0.00266133) , 
1, -4.04163, 1, 0, 0.500331,2.60553e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525467,0.00190432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,-0.0219748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316742,0.000343292) , 
2, -7.33441, 1, 0, 0.410876,-0.0241611) , 
1, -2.19835, 0, 0, 0.500331,2.8593e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863248,0.0167428) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472453,-0.00208801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41791,0.0213978) , 
0, 104.43, 0, 0, 0.469828,-0.00372368) , 
5, 648.91, 0, 0, 0.500331,2.83739e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0165443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475887,0.00086032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390977,-0.0101433) , 
1, -2.34313, 0, 0, 0.459341,-0.004116) , 
4, 0.904758, 0, 0, 0.500331,2.69993e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00205715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625,-0.0198837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251724,-0.00273333) , 
4, 0.720444, 0, 0, 0.332432,-0.0225911) , 
3, 0.302072, 0, 0, 0.500331,2.75614e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0134948) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0323591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441968,-0.00210367) , 
1, 0.991979, 0, 0, 0.465201,-0.00398148) , 
3, 0.940472, 0, 0, 0.500331,2.69315e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0344543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573206,0.00171735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223919,-0.00808597) , 
2, -0.69653, 1, 0, 0.477747,-0.00266861) , 
2, -9.81003, 1, 0, 0.500331,3.30335e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00176259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233333,-0.0257809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208145,0.00554353) , 
2, -2.03418, 1, 0, 0.217009,-0.021762) , 
5, 299.286, 0, 0, 0.500331,3.388e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.00261497) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595122,-0.0133172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286082,0.000967894) , 
2, -5.64344, 1, 0, 0.392917,-0.0144885) , 
1, -1.58392, 0, 0, 0.500331,2.44478e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713344,0.0043238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641304,0.0174908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324691,-0.00506731) , 
0, 175.978, 0, 0, 0.356984,-0.00947994) , 
2, -3.83079, 1, 0, 0.500331,2.36667e-05)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00181707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511111,-0.0310618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315113,-0.00169587) , 
0, 307.411, 0, 0, 0.339888,-0.0203495) , 
4, 0.142855, 0, 0, 0.500331,2.1849e-05)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913043,0.023921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698864,0.00532334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354167,-0.00425707) , 
5, 399.168, 0, 0, 0.480556,-0.00252297) , 
5, 788.759, 0, 0, 0.500331,2.16101e-05)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0149071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475887,0.00081551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390977,-0.00919387) , 
1, -2.34313, 0, 0, 0.459341,-0.00357336) , 
4, 0.904758, 0, 0, 0.500331,2.32368e-05)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610422,0.00292173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53211,-0.0178041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345118,-0.000485702) , 
2, -6.70323, 1, 0, 0.374111,-0.0117141) , 
3, 0.429752, 0, 0, 0.500331,2.34211e-05)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0328234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948276,0.0335342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457971,-0.00145199) , 
1, 1.02488, 0, 0, 0.477747,-0.00238997) , 
2, -9.81003, 1, 0, 0.500331,2.23043e-05)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774566,0.00616351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423077,-0.0033768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382114,0.0147252) , 
0, 110.423, 0, 0, 0.418745,-0.00564778) , 
0, 233.956, 0, 0, 0.500331,3.14734e-05)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.0160225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771635,0.00983736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386473,-0.00267208) , 
0, 185.272, 0, 0, 0.496899,0.00213804) , 
1, -4.04163, 1, 0, 0.500331,2.76148e-05)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.0292516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525186,0.00126791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298805,-0.0102056) , 
3, 0.24732, 0, 0, 0.48632,-0.00180489) , 
5, 858.684, 0, 0, 0.500331,2.82619e-05)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.0023275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.0145746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37234,0.00202632) , 
4, 0.238088, 0, 0, 0.392917,-0.0127051) , 
1, -1.58392, 0, 0, 0.500331,2.75022e-05)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00163588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511111,-0.0296125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315113,-0.00124112) , 
0, 307.411, 0, 0, 0.339888,-0.0180778) , 
4, 0.142855, 0, 0, 0.500331,2.42352e-05)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925926,0.0250825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667464,0.00552249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4108,-0.00300503) , 
3, 0.586258, 0, 0, 0.484536,-0.00190297) , 
3, 1.32351, 0, 0, 0.500331,2.34254e-05)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0131191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475887,0.00076169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390977,-0.00819936) , 
1, -2.34313, 0, 0, 0.459341,-0.00303416) , 
4, 0.904758, 0, 0, 0.500331,2.44794e-05)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913043,0.0209088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698864,0.00462225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354167,-0.00363034) , 
5, 399.168, 0, 0, 0.480556,-0.00203847) , 
5, 788.759, 0, 0, 0.500331,2.38743e-05)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.0143159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771635,0.0088423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386473,-0.0023781) , 
0, 185.272, 0, 0, 0.496899,0.00189004) , 
1, -4.04163, 1, 0, 0.500331,2.42022e-05)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0300965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658333,-0.00989478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441569,0.00122972) , 
2, -6.9555, 1, 0, 0.477747,-0.00199005) , 
2, -9.81003, 1, 0, 0.500331,2.44644e-05)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00141955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511111,-0.0267646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315113,-0.00088489) , 
0, 307.411, 0, 0, 0.339888,-0.01554) , 
4, 0.142855, 0, 0, 0.500331,2.76752e-05)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.865385,0.0134807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443209,-0.00199423) , 
4, 0.86399, 0, 0, 0.503067,-0.00147069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404762,0.0156556) , 
4, 0.0476169, 0, 0, 0.500331,2.6057e-05)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00144874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631579,-0.0203996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255102,-0.000256017) , 
4, 0.767036, 0, 0, 0.332432,-0.0154438) , 
3, 0.302072, 0, 0, 0.500331,2.61889e-05)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.0269123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561691,0.00135376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19802,-0.00895747) , 
5, 292.097, 0, 0, 0.48632,-0.00154209) , 
5, 858.684, 0, 0, 0.500331,2.57069e-05)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579258,0.00144474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205036,-0.0099396) , 
5, 296.188, 0, 0, 0.508197,-0.00146892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244444,0.0170807) , 
5, 229.361, 0, 0, 0.500331,2.37653e-05)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.00196249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.0139167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37234,0.00253635) , 
4, 0.238088, 0, 0, 0.392917,-0.0106014) , 
1, -1.58392, 0, 0, 0.500331,1.78713e-05)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00142773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492537,-0.0200613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304498,-0.000139619) , 
2, -6.39332, 1, 0, 0.339888,-0.0155966) , 
4, 0.142855, 0, 0, 0.500331,1.55152e-05)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580372,0.00131085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,-0.0196625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197674,0.000262312) , 
4, 0.408754, 0, 0, 0.211009,-0.0164136) , 
2, -0.414075, 1, 0, 0.500331,1.45598e-05)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925926,0.0225345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768166,0.00740928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414237,-0.00215251) , 
1, -0.0528887, 0, 0, 0.484536,-0.00161832) , 
3, 1.32351, 0, 0, 0.500331,1.1248e-05)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713344,0.00312825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782609,0.0236099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334112,-0.00326874) , 
0, 223.017, 0, 0, 0.356984,-0.00658772) , 
2, -3.83079, 1, 0, 0.500331,1.34602e-05)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.0124172) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979167,0.0476597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480399,-0.00033397) , 
5, 788.759, 0, 0, 0.496899,0.00161749) , 
1, -4.04163, 1, 0, 0.500331,1.40252e-05)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579258,0.00126252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205036,-0.00890081) , 
5, 296.188, 0, 0, 0.508197,-0.00136071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244444,0.0156663) , 
5, 229.361, 0, 0, 0.500331,2.15669e-05)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.865385,0.0122609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443209,-0.00178694) , 
4, 0.86399, 0, 0, 0.503067,-0.00130377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404762,0.0137868) , 
4, 0.0476169, 0, 0, 0.500331,1.65525e-05)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00128472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511111,-0.0251433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315113,-0.000628575) , 
0, 307.411, 0, 0, 0.339888,-0.0138952) , 
4, 0.142855, 0, 0, 0.500331,1.71346e-05)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0276921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658333,-0.00913163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441569,0.00118133) , 
2, -6.9555, 1, 0, 0.477747,-0.00168809) , 
2, -9.81003, 1, 0, 0.500331,1.63457e-05)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00127102) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631579,-0.0198159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255102,0.000383658) , 
4, 0.767036, 0, 0, 0.332432,-0.0134197) , 
3, 0.302072, 0, 0, 0.500331,1.91659e-05)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.894118,0.0145174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517949,0.00173837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387528,-0.00608501) , 
1, -1.9074, 0, 0, 0.476826,-0.00186742) , 
1, 0.873794, 0, 0, 0.500331,1.92026e-05)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.865385,0.0111566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443209,-0.00164212) , 
4, 0.86399, 0, 0, 0.503067,-0.00130195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404762,0.0137138) , 
4, 0.0476169, 0, 0, 0.500331,1.84084e-05)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774566,0.00479685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423077,-0.00292377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382114,0.0143185) , 
0, 110.423, 0, 0, 0.418745,-0.00420964) , 
0, 233.956, 0, 0, 0.500331,1.83243e-05)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.00881699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0262416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441968,-0.00138635) , 
1, 0.991979, 0, 0, 0.465201,-0.00238117) , 
3, 0.940472, 0, 0, 0.500331,1.55117e-05)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863248,0.0105389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472453,-0.00149331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41791,0.0182477) , 
0, 104.43, 0, 0, 0.469828,-0.00204134) , 
5, 648.91, 0, 0, 0.500331,1.86068e-05)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00184323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427711,0.0125378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364211,-0.00117875) , 
4, 0.178714, 0, 0, 0.380655,0.00826885) , 
4, 0.238093, 0, 0, 0.500331,1.66784e-05)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616368,0.00260262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373723,-0.00375047) , 
3, 0.429752, 0, 0, 0.503067,-0.00117745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404762,0.0123678) , 
4, 0.0476169, 0, 0, 0.500331,1.39356e-05)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.0112067) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771635,0.00754399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386473,-0.0020464) , 
0, 185.272, 0, 0, 0.496899,0.001445) , 
1, -4.04163, 1, 0, 0.500331,1.20227e-05)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579258,0.00110335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205036,-0.00788386) , 
5, 296.188, 0, 0, 0.508197,-0.00121235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244444,0.0136216) , 
5, 229.361, 0, 0, 0.500331,1.25953e-05)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569869,0.00163035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.0128062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37234,0.00274728) , 
4, 0.238088, 0, 0, 0.392917,-0.00867232) , 
1, -1.58392, 0, 0, 0.500331,9.1225e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00118592) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511111,-0.0238574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315113,-0.00048721) , 
0, 307.411, 0, 0, 0.339888,-0.0127641) , 
4, 0.142855, 0, 0, 0.500331,7.64218e-06)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.0237276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525186,0.000993834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298805,-0.00779081) , 
3, 0.24732, 0, 0, 0.48632,-0.00124785) , 
5, 858.684, 0, 0, 0.500331,7.64028e-06)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957747,0.0257695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658333,-0.00886854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441569,0.00119718) , 
2, -6.9555, 1, 0, 0.477747,-0.00147771) , 
2, -9.81003, 1, 0, 0.500331,7.98176e-06)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713344,0.00272325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511628,-0.0256156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349243,-0.00017662) , 
5, 523.137, 0, 0, 0.356984,-0.0056259) , 
2, -3.83079, 1, 0, 0.500331,1.09181e-05)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.939394,0.0258129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482513,-0.000947476) , 
5, 788.759, 0, 0, 0.503067,-0.00112168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404762,0.0117054) , 
4, 0.0476169, 0, 0, 0.500331,1.15259e-05)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.0105976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771635,0.00695982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386473,-0.00186283) , 
0, 185.272, 0, 0, 0.496899,0.00135139) , 
1, -4.04163, 1, 0, 0.500331,1.3425e-05)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760684,-0.00851271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681481,0.00618414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349765,-0.00294353) , 
0, 159.227, 0, 0, 0.478448,0.00193889) , 
0, 406.841, 0, 0, 0.500331,1.35786e-05)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614723,0.0016997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240476,-0.00559125) , 
2, -1.14768, 1, 0, 0.507503,-0.00111882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255814,0.0123298) , 
2, 1.29428, 1, 0, 0.500331,1.33899e-05)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
