// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Thu May  8 11:17:55 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 156
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "156" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
Match_ttbar_fake_3l_B   max_Match_ttbar_fake_3l_B,_M_6_ Match_ttbar_fake_3l_B   Match_ttbar_fake_3l_B                                       'F'    [-6,0.807759106159]
Match_ttbar_fake_3l_b   max_Match_ttbar_fake_3l_b,_M_6_ Match_ttbar_fake_3l_b   Match_ttbar_fake_3l_b                                       'F'    [-6,0.655405879021]
Match_ttW_3l_B                Match_ttW_3l_B                Match_ttW_3l_B                Match_ttW_3l_B                                                  'F'    [-4.74065256119,0.734057068825]
Match_ttW_3l_b                Match_ttW_3l_b                Match_ttW_3l_b                Match_ttW_3l_b                                                  'F'    [-4.99441862106,0.686377048492]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Match_ttbar_fake_3l_B", "Match_ttbar_fake_3l_b", "Match_ttW_3l_B", "Match_ttW_3l_b" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -6;
      fVmax[0] = 0.80775910615921;
      fVmin[1] = -6;
      fVmax[1] = 0.655405879020691;
      fVmin[2] = -4.74065256118774;
      fVmax[2] = 0.734057068824768;
      fVmin[3] = -4.99441862106323;
      fVmax[3] = 0.686377048492432;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.0510204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,0.0118644) , 
0, -0.164778, 1, 0, 0.648148,0.148148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0666667) , 
1, -0.929215, 1, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.0460424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,0.0106795) , 
0, -0.164778, 1, 0, 0.648148,0.133344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.060277) , 
1, -0.929215, 1, 0, 0.5,-8.107e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.0417352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,0.00961528) , 
0, -0.164778, 1, 0, 0.648148,0.120041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0549156) , 
1, -0.929215, 1, 0, 0.5,-3.29885e-05)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744681,0.0386126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57377,0.00898754) , 
2, -0.0288291, 1, 0, 0.648148,0.108081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0503064) , 
1, -0.929215, 1, 0, 0.5,-6.48747e-05)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.0353351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,0.0071186) , 
0, -0.164778, 1, 0, 0.648148,0.0973128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0462652) , 
1, -0.929215, 1, 0, 0.5,-0.000104108)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744681,0.0327185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57377,0.00673002) , 
2, -0.0288291, 1, 0, 0.648148,0.087631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0426653) , 
1, -0.929215, 1, 0, 0.5,-0.00013459)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.0301138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,0.00517974) , 
0, -0.164778, 1, 0, 0.648148,0.0789099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.039417) , 
1, -0.929215, 1, 0, 0.5,-0.000165289)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0271336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,0.00412141) , 
3, 0.1087, 0, 0, 0.648148,0.0710648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.036456) , 
1, -0.929215, 1, 0, 0.5,-0.000186002)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.0260394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,0.00340702) , 
0, -0.164778, 1, 0, 0.648148,0.0639891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0337351) , 
1, -0.929215, 1, 0, 0.5,-0.000209676)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744681,0.0245591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57377,0.00295661) , 
2, -0.0288291, 1, 0, 0.648148,0.0576297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0312195) , 
1, -0.929215, 1, 0, 0.5,-0.000218963)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0219516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,0.00171281) , 
3, 0.1087, 0, 0, 0.648148,0.0518993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0288832) , 
1, -0.929215, 1, 0, 0.5,-0.000226019)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.0211558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,0.00139269) , 
0, -0.164778, 1, 0, 0.648148,0.046734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0267064) , 
1, -0.929215, 1, 0, 0.5,-0.000231834)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0189417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,0.000733404) , 
3, 0.1087, 0, 0, 0.648148,0.0420902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0246742) , 
1, -0.929215, 1, 0, 0.5,-0.000228058)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744681,0.0187626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57377,0.000590713) , 
2, -0.0288291, 1, 0, 0.648148,0.0379013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0227748) , 
1, -0.929215, 1, 0, 0.5,-0.000225957)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.017258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,6.26448e-05) , 
0, -0.164778, 1, 0, 0.648148,0.0341331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0209989) , 
1, -0.929215, 1, 0, 0.5,-0.0002181)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0154487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.000485406) , 
3, 0.1087, 0, 0, 0.648148,0.030741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0193388) , 
1, -0.929215, 1, 0, 0.5,-0.000207295)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744681,0.0152129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57377,-0.000330149) , 
2, -0.0288291, 1, 0, 0.648148,0.0276816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0177883) , 
1, -0.929215, 1, 0, 0.5,-0.000198378)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.0141144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,-0.000778347) , 
0, -0.164778, 1, 0, 0.648148,0.0249288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0163416) , 
1, -0.929215, 1, 0, 0.5,-0.000186499)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0126551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.00125048) , 
3, 0.1087, 0, 0, 0.648148,0.0224509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0149936) , 
1, -0.929215, 1, 0, 0.5,-0.000173309)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755102,0.0122824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559322,-0.00108401) , 
0, -0.164778, 1, 0, 0.648148,0.0202162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0137396) , 
1, -0.929215, 1, 0, 0.5,-0.000162048)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622222,0.018884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439394,-0.00577133) , 
2, 0.0895532, 1, 0, 0.513514,0.0176534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.0117301) , 
2, -0.308745, 0, 0, 0.5,-0.000148997)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0108386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.00151187) , 
3, 0.1087, 0, 0, 0.648148,0.0178282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0123376) , 
1, -0.929215, 1, 0, 0.5,-0.000127946)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.0289127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,-0.0142545) , 
0, -0.164778, 1, 0, 0.535714,0.0241087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458333,-0.00734314) , 
3, 0.145349, 1, 0, 0.5,-0.000118628)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622222,0.0170236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439394,-0.00489097) , 
2, 0.0895532, 1, 0, 0.513514,0.0163659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.0109584) , 
2, -0.308745, 0, 0, 0.5,-0.000101916)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0102189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.00140685) , 
3, 0.1087, 0, 0, 0.648148,0.0167871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0116916) , 
1, -0.929215, 1, 0, 0.5,-8.62852e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.0267324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,-0.012786) , 
0, -0.164778, 1, 0, 0.535714,0.0226651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458333,-0.00695218) , 
3, 0.145349, 1, 0, 0.5,-8.0761e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.00973888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.00126748) , 
3, 0.1087, 0, 0, 0.648148,0.0161155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0112794) , 
1, -0.929215, 1, 0, 0.5,-6.82196e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622222,0.01527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439394,-0.00402626) , 
2, 0.0895532, 1, 0, 0.513514,0.0152289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.0103606) , 
2, -0.308745, 0, 0, 0.5,-6.43594e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.0247479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,-0.0115045) , 
0, -0.164778, 1, 0, 0.535714,0.0212827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458333,-0.00657597) , 
3, 0.145349, 1, 0, 0.5,-5.31227e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76087,0.0176813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,-0.00685801) , 
2, 0.0207912, 1, 0, 0.639175,0.0180163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271186,-0.00893702) , 
1, -2.51383, 1, 0, 0.5,-4.37658e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622222,0.0133173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439394,-0.00277119) , 
2, 0.0895532, 1, 0, 0.513514,0.0148636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.0102038) , 
2, -0.308745, 0, 0, 0.5,-2.81339e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.0225989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,-0.0101857) , 
0, -0.164778, 1, 0, 0.535714,0.0197119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458333,-0.00612262) , 
3, 0.145349, 1, 0, 0.5,-2.12419e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76087,0.0158843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,-0.00554204) , 
2, 0.0207912, 1, 0, 0.639175,0.017239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271186,-0.00857648) , 
1, -2.51383, 1, 0, 0.5,-1.559e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622222,0.0116146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439394,-0.0017793) , 
2, 0.0895532, 1, 0, 0.513514,0.0143488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.00994127) , 
2, -0.308745, 0, 0, 0.5,-5.24865e-06)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520833,-0.00244224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,0.0151867) , 
0, -0.164778, 0, 0, 0.5,0.0184453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.00658095) , 
2, -0.0480443, 0, 0, 0.5,-1.29487e-06)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.00861082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.00127215) , 
3, 0.1087, 0, 0, 0.648148,0.0137506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.00980092) , 
1, -0.929215, 1, 0, 0.5,-2.60694e-06)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.0205059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,-0.00876958) , 
0, -0.164778, 1, 0, 0.535714,0.0185344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458333,-0.00583052) , 
3, 0.145349, 1, 0, 0.5,-4.33719e-06)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76087,0.0142619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,-0.00473809) , 
2, 0.0207912, 1, 0, 0.639175,0.0156857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271186,-0.00788056) , 
1, -2.51383, 1, 0, 0.5,-8.88147e-07)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520833,-0.0013723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,0.0135257) , 
0, -0.164778, 0, 0, 0.5,0.0184282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.00667901) , 
2, -0.0480443, 0, 0, 0.5,6.28017e-06)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.00791111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.00114723) , 
3, 0.1087, 0, 0, 0.648148,0.0126025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.00908184) , 
1, -0.929215, 1, 0, 0.5,4.76961e-06)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520833,-0.00137703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,0.0125764) , 
0, -0.164778, 0, 0, 0.5,0.0167863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.00611676) , 
2, -0.0480443, 0, 0, 0.5,2.58373e-06)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.0181116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,-0.00731988) , 
0, -0.164778, 1, 0, 0.535714,0.0170975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458333,-0.00543823) , 
3, 0.145349, 1, 0, 0.5,1.59041e-06)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76087,0.0133186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,-0.00427423) , 
2, 0.0207912, 1, 0, 0.639175,0.014809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271186,-0.00747839) , 
1, -2.51383, 1, 0, 0.5,3.8828e-06)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520833,-0.000402279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,0.0108327) , 
0, -0.164778, 0, 0, 0.5,0.016544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.00607712) , 
2, -0.0480443, 0, 0, 0.5,9.62166e-06)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.00745441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.00104439) , 
3, 0.1087, 0, 0, 0.648148,0.0119159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.00865936) , 
1, -0.929215, 1, 0, 0.5,8.31456e-06)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533333,0.00824493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490196,-0.00467959) , 
3, 0.0294661, 1, 0, 0.513514,0.0111666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.00802651) , 
2, -0.308745, 0, 0, 0.5,5.91032e-06)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533333,0.00741997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490196,-0.004209) , 
3, 0.0294661, 1, 0, 0.513514,0.0100501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.00721296) , 
2, -0.308745, 0, 0, 0.5,6.01443e-06)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.00780649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,-0.00200538) , 
3, 0.1087, 0, 0, 0.648148,0.0103241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.00762324) , 
1, -0.929215, 1, 0, 0.5,6.01835e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.016533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,-0.00738397) , 
0, -0.164778, 1, 0, 0.535714,0.0136131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458333,-0.00440771) , 
3, 0.145349, 1, 0, 0.5,5.15848e-06)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76087,0.0123268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,-0.0046159) , 
2, 0.0207912, 1, 0, 0.639175,0.0118571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271186,-0.00610733) , 
1, -2.51383, 1, 0, 0.5,6.77506e-06)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
