// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Thu May  8 11:05:00 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 626
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "626" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
Match_ttW_SS_Bb               Match_ttW_SS_Bb               Match_ttW_SS_Bb               Match_ttW_SS_Bb                                                 'F'    [-9.72762298584,1.62780928612]
Match_ttW_SS_Bq               Match_ttW_SS_Bq               Match_ttW_SS_Bq               Match_ttW_SS_Bq                                                 'F'    [-8.75408744812,1.30624377728]
Match_ttW_SS_bq               Match_ttW_SS_bq               Match_ttW_SS_bq               Match_ttW_SS_bq                                                 'F'    [-6.89080190659,1.34444963932]
Match_ttbar_fake_SS_Bq        Match_ttbar_fake_SS_Bq        Match_ttbar_fake_SS_Bq        Match_ttbar_fake_SS_Bq                                          'F'    [-9.78224086761,1.71891319752]
met_ld                        met_ld                        met_ld                        met_ld                                                          'F'    [0.0385484620929,1.9282476902]
jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex                                         'F'    [-10,0.999883413315]
MT_of_everything              MT_of_everything              MT_of_everything              MT_of_everything                                                'F'    [113.493812561,1571.76660156]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Match_ttW_SS_Bb", "Match_ttW_SS_Bq", "Match_ttW_SS_bq", "Match_ttbar_fake_SS_Bq", "met_ld", "jets_by_CSV_2_btagCombinedSecVertex", "MT_of_everything" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -9.72762298583984;
      fVmax[0] = 1.62780928611755;
      fVmin[1] = -8.75408744812012;
      fVmax[1] = 1.30624377727509;
      fVmin[2] = -6.89080190658569;
      fVmax[2] = 1.34444963932037;
      fVmin[3] = -9.78224086761475;
      fVmax[3] = 1.7189131975174;
      fVmin[4] = 0.0385484620928764;
      fVmax[4] = 1.92824769020081;
      fVmin[5] = -10;
      fVmax[5] = 0.999883413314819;
      fVmin[6] = 113.493812561035;
      fVmax[6] = 1571.7666015625;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741525,0.0483051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437209,-0.0125581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251429,-0.0497143) , 
6, 272.843, 0, 0, 0.353846,-0.146154) , 
3, -1.01946, 1, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784211,0.0521368) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586667,0.0186657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33241,-0.0312901) , 
5, 0.46529, 0, 0, 0.376147,-0.113334) , 
3, -1.56713, 1, 0, 0.5,1.24494e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784211,0.0473056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47907,-0.00157381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276018,-0.0389148) , 
6, 283.005, 0, 0, 0.376147,-0.102015) , 
3, -1.56713, 1, 0, 0.5,1.85854e-05)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741525,0.0368294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550725,0.0137049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311526,-0.0297614) , 
5, 0.419332, 0, 0, 0.353846,-0.109421) , 
3, -1.01946, 1, 0, 0.5,3.59346e-05)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778443,0.0445043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716981,0.0384058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357143,-0.0231435) , 
0, 0.247803, 0, 0, 0.398693,-0.0788795) , 
6, 391.26, 0, 0, 0.5,4.47334e-05)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807229,0.0424246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469751,-0.00171017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26257,-0.0357143) , 
6, 264.901, 0, 0, 0.38913,-0.0730513) , 
3, -2.1148, 1, 0, 0.5,6.79507e-05)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674576,0.0242518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551724,0.00795414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300366,-0.0276763) , 
5, 0.469965, 0, 0, 0.344411,-0.103965) , 
6, 321.818, 0, 0, 0.5,8.71915e-05)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807229,0.0374849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686275,0.0302848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352078,-0.0182803) , 
0, 0.324611, 0, 0, 0.38913,-0.0626327) , 
3, -2.1148, 1, 0, 0.5,7.19284e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778443,0.0346135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643678,0.0205742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341398,-0.0197632) , 
5, 0.475007, 0, 0, 0.398693,-0.0581399) , 
6, 391.26, 0, 0, 0.5,0.000102468)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741525,0.0251526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595238,0.0218191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324713,-0.0190084) , 
4, 0.737907, 0, 0, 0.353846,-0.069745) , 
3, -1.01946, 1, 0, 0.5,0.000115409)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0511077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698276,0.0253147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372093,-0.0155401) , 
5, 0.476079, 0, 0, 0.441392,-0.0325343) , 
3, -3.75783, 1, 0, 0.5,0.000114685)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674576,0.0182329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43871,-0.00264512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261364,-0.0276577) , 
6, 261.843, 0, 0, 0.344411,-0.074329) , 
6, 321.818, 0, 0, 0.5,0.000155815)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0469168) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698276,0.022919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372093,-0.0138193) , 
5, 0.476079, 0, 0, 0.441392,-0.0283233) , 
3, -3.75783, 1, 0, 0.5,0.000130146)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778443,0.0263514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716981,0.0255532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357143,-0.0132474) , 
0, 0.247803, 0, 0, 0.398693,-0.0410348) , 
6, 391.26, 0, 0, 0.5,0.000165803)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677741,0.0152775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522727,0.019731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30605,-0.0186003) , 
1, -0.430371, 1, 0, 0.335385,-0.0620862) , 
3, -0.471783, 1, 0, 0.5,0.000170952)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0420113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698276,0.0193394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372093,-0.0116167) , 
5, 0.476079, 0, 0, 0.441392,-0.0235106) , 
3, -3.75783, 1, 0, 0.5,0.000146851)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674576,0.0140172) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43871,-0.000145804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261364,-0.022778) , 
6, 261.843, 0, 0, 0.344411,-0.0544921) , 
6, 321.818, 0, 0, 0.5,0.000173827)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0387569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698276,0.0175267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372093,-0.0103464) , 
5, 0.476079, 0, 0, 0.441392,-0.0205228) , 
3, -3.75783, 1, 0, 0.5,0.0001469)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.025611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62381,0.00767924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306397,-0.0146363) , 
3, -0.433864, 1, 0, 0.43787,-0.0250198) , 
4, 0.758434, 0, 0, 0.5,0.000168696)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742647,0.0211583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65,0.0392062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413333,-0.00969746) , 
2, 0.679071, 0, 0, 0.432653,-0.025064) , 
5, 0.476079, 0, 0, 0.5,0.000156486)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.0233196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770833,0.0256614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40305,-0.00819761) , 
0, 0.57692, 0, 0, 0.43787,-0.0223865) , 
4, 0.758434, 0, 0, 0.5,0.000147018)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0349511) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758621,0.0236213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403689,-0.00699955) , 
0, 0.44185, 0, 0, 0.441392,-0.0172227) , 
3, -3.75783, 1, 0, 0.5,0.00014896)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674576,0.0107235) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43871,0.00148902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261364,-0.0188583) , 
6, 261.843, 0, 0, 0.344411,-0.0398973) , 
6, 321.818, 0, 0, 0.5,0.000168079)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0322223) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758621,0.0215916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403689,-0.00623006) , 
0, 0.44185, 0, 0, 0.441392,-0.015071) , 
3, -3.75783, 1, 0, 0.5,0.00014299)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.0198853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62381,0.00621578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306397,-0.0113223) , 
3, -0.433864, 1, 0, 0.43787,-0.0183092) , 
4, 0.758434, 0, 0, 0.5,0.000157744)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0253161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748031,0.01716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412698,-0.00803928) , 
5, 0.476079, 0, 0, 0.487676,-0.0110413) , 
2, 0.56014, 0, 0, 0.5,0.000144993)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0294053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519789,0.00198335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263473,-0.0150196) , 
6, 258.002, 0, 0, 0.441392,-0.0130039) , 
3, -3.75783, 1, 0, 0.5,0.000135803)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.0174208) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581395,0.0203594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424569,-0.00597272) , 
2, 0.616939, 0, 0, 0.43787,-0.015645) , 
4, 0.758434, 0, 0, 0.5,0.000134453)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742647,0.0145426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65,0.0323606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413333,-0.00708002) , 
2, 0.679071, 0, 0, 0.432653,-0.016063) , 
5, 0.476079, 0, 0, 0.5,0.000126795)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0271064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475771,0.000651591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271739,-0.0188065) , 
3, 0.683845, 1, 0, 0.441392,-0.0114464) , 
3, -3.75783, 1, 0, 0.5,0.000117676)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778443,0.0130289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642857,0.0183026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374101,-0.00625351) , 
6, 363.607, 0, 0, 0.398693,-0.0170097) , 
6, 391.26, 0, 0, 0.5,0.000116798)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742647,0.0130687) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65,0.0294787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413333,-0.00638823) , 
2, 0.679071, 0, 0, 0.432653,-0.0141971) , 
5, 0.476079, 0, 0, 0.5,0.000110596)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.0145532) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62381,0.00473638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306397,-0.00827953) , 
3, -0.433864, 1, 0, 0.43787,-0.0126457) , 
4, 0.758434, 0, 0, 0.5,0.000102734)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0240579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492021,0.00200522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329412,-0.0118001) , 
4, 0.328345, 0, 0, 0.441392,-0.00955884) , 
3, -3.75783, 1, 0, 0.5,9.40944e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742647,0.0116462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65,0.0268367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413333,-0.00573352) , 
2, 0.679071, 0, 0, 0.432653,-0.0124529) , 
5, 0.476079, 0, 0, 0.5,9.42385e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0223893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475771,0.000735797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271739,-0.0157316) , 
3, 0.683845, 1, 0, 0.441392,-0.00860528) , 
3, -3.75783, 1, 0, 0.5,8.76039e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.0123118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770833,0.0159268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40305,-0.00431812) , 
0, 0.57692, 0, 0, 0.43787,-0.0104059) , 
4, 0.758434, 0, 0, 0.5,8.54394e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0158646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670412,0.00538103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325581,-0.00758592) , 
6, 321.818, 0, 0, 0.487676,-0.00670994) , 
2, 0.56014, 0, 0, 0.5,8.26437e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742647,0.00991196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65,0.0230034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413333,-0.0048881) , 
2, 0.679071, 0, 0, 0.432653,-0.0104043) , 
5, 0.476079, 0, 0, 0.5,7.28385e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.020197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492021,0.00186918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329412,-0.0100211) , 
4, 0.328345, 0, 0, 0.441392,-0.00743576) , 
3, -3.75783, 1, 0, 0.5,6.7885e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575693,0.00262459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46,0.0191006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186916,-0.0219754) , 
0, -0.874406, 0, 0, 0.273885,-0.0313399) , 
6, 252.377, 0, 0, 0.5,6.7329e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.018553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475771,0.00084517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271739,-0.0137821) , 
3, 0.683845, 1, 0, 0.441392,-0.00664109) , 
3, -3.75783, 1, 0, 0.5,4.41043e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0129555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748031,0.00939203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412698,-0.00425803) , 
5, 0.476079, 0, 0, 0.487676,-0.00544279) , 
2, 0.56014, 0, 0, 0.5,4.34716e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.0096829) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770833,0.0125442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40305,-0.00336076) , 
0, 0.57692, 0, 0, 0.43787,-0.00796378) , 
4, 0.758434, 0, 0, 0.5,4.11649e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0118272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498077,0.000359311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.0181886) , 
2, 0.204434, 1, 0, 0.487676,-0.00495266) , 
2, 0.56014, 0, 0, 0.5,4.06624e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575693,0.00226443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46,0.0170133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186916,-0.0197233) , 
0, -0.874406, 0, 0, 0.273885,-0.0268589) , 
6, 252.377, 0, 0, 0.5,3.57301e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0168395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763889,0.0121988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392405,-0.00329308) , 
3, -2.42136, 1, 0, 0.441392,-0.00585089) , 
3, -3.75783, 1, 0, 0.5,1.88975e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0108078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498077,0.000326708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.0166794) , 
2, 0.204434, 1, 0, 0.487676,-0.00451254) , 
2, 0.56014, 0, 0, 0.5,2.50959e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.00843613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486842,-0.0111734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429234,-4.56166e-05) , 
0, -2.0503, 1, 0, 0.43787,-0.00684896) , 
4, 0.758434, 0, 0, 0.5,2.18043e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00383916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743243,0.0289988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308943,-0.00422051) , 
3, -0.677702, 1, 0, 0.409375,0.0138552) , 
1, -0.130946, 1, 0, 0.5,2.14332e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767442,0.00874887) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436482,0.00332588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421053,-0.0101947) , 
2, -0.984376, 0, 0, 0.430584,-0.00732376) , 
1, -1.08907, 1, 0, 0.5,2.7254e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.0034671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.028656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.0015871) , 
3, -2.01632, 1, 0, 0.461017,-0.0150063) , 
2, -0.616325, 1, 0, 0.5,2.48323e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0159778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475771,0.000780166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271739,-0.01193) , 
3, 0.683845, 1, 0, 0.441392,-0.00543658) , 
3, -3.75783, 1, 0, 0.5,3.62034e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00381283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743243,0.0269237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308943,-0.00359313) , 
3, -0.677702, 1, 0, 0.409375,0.0137595) , 
1, -0.130946, 1, 0, 0.5,3.51396e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767442,0.0080024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436482,0.00317658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421053,-0.00955547) , 
2, -0.984376, 0, 0, 0.430584,-0.00664039) , 
1, -1.08907, 1, 0, 0.5,3.9074e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00347706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.0275875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.00142967) , 
3, -2.01632, 1, 0, 0.461017,-0.0149351) , 
2, -0.616325, 1, 0, 0.5,3.52972e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0152228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492021,0.00176245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329412,-0.00813859) , 
4, 0.328345, 0, 0, 0.441392,-0.005096) , 
3, -3.75783, 1, 0, 0.5,4.458e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00369324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743243,0.0252784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308943,-0.00320488) , 
3, -0.677702, 1, 0, 0.409375,0.0133135) , 
1, -0.130946, 1, 0, 0.5,4.31197e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00318802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481172,0.00121275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.0237956) , 
2, -0.331997, 0, 0, 0.461017,-0.0136116) , 
2, -0.616325, 1, 0, 0.5,4.5723e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00338866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44898,0.00904447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28,-0.0170844) , 
5, 0.0853964, 0, 0, 0.409375,0.012223) , 
1, -0.130946, 1, 0, 0.5,3.93328e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575693,0.00184429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46,0.015488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186916,-0.01738) , 
0, -0.874406, 0, 0, 0.273885,-0.0215559) , 
6, 252.377, 0, 0, 0.5,2.94036e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0141979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51087,-0.0109617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427313,0.000846035) , 
2, -2.96925, 1, 0, 0.441392,-0.00469311) , 
3, -3.75783, 1, 0, 0.5,1.61114e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00308403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.0260062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.00168923) , 
3, -2.01632, 1, 0, 0.461017,-0.0131854) , 
2, -0.616325, 1, 0, 0.5,1.91354e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778443,0.00651838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401961,0.000469119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372549,-0.0198831) , 
2, -2.96925, 0, 0, 0.398693,-0.00771423) , 
6, 391.26, 0, 0, 0.5,2.84413e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693878,0.0204413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502959,-0.000817259) , 
2, 0.56014, 0, 0, 0.519784,0.00430652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342857,-0.00849247) , 
4, 0.21852, 0, 0, 0.5,2.58216e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.0030961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560386,0.00265086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227273,-0.0185722) , 
6, 260.354, 0, 0, 0.461017,-0.0131945) , 
2, -0.616325, 1, 0, 0.5,2.44583e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00751135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504608,0.00449825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0142018) , 
5, 0.047558, 0, 0, 0.476834,0.00563217) , 
0, -2.15733, 1, 0, 0.5,1.52651e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767442,0.00726962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436482,0.00305101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421053,-0.00897935) , 
2, -0.984376, 0, 0, 0.430584,-0.00599015) , 
1, -1.08907, 1, 0, 0.5,1.15716e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00322845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.0244076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.00122222) , 
3, -2.01632, 1, 0, 0.461017,-0.0137506) , 
2, -0.616325, 1, 0, 0.5,1.03785e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0138944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763889,0.0112283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392405,-0.00281232) , 
3, -2.42136, 1, 0, 0.441392,-0.00455474) , 
3, -3.75783, 1, 0, 0.5,1.91614e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00323747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743243,0.0233209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308943,-0.00312568) , 
3, -0.677702, 1, 0, 0.409375,0.0115294) , 
1, -0.130946, 1, 0, 0.5,2.29846e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00295428) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.0236223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.0014796) , 
3, -2.01632, 1, 0, 0.461017,-0.0124873) , 
2, -0.616325, 1, 0, 0.5,2.66995e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.013622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475771,0.000809645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271739,-0.0107082) , 
3, 0.683845, 1, 0, 0.441392,-0.00442395) , 
3, -3.75783, 1, 0, 0.5,3.32263e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00704631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504608,0.00411962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0128647) , 
5, 0.047558, 0, 0, 0.476834,0.00529178) , 
0, -2.15733, 1, 0, 0.5,3.14075e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778443,0.00569294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631579,-0.0185805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365672,0.000605256) , 
3, -1.85609, 1, 0, 0.398693,-0.0066476) , 
6, 391.26, 0, 0, 0.5,2.64384e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693878,0.0184869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502959,-0.000727287) , 
2, 0.56014, 0, 0, 0.519784,0.00391328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342857,-0.00777701) , 
4, 0.21852, 0, 0, 0.5,2.90959e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00286427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560386,0.00245635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227273,-0.0173421) , 
6, 260.354, 0, 0, 0.461017,-0.0120689) , 
2, -0.616325, 1, 0, 0.5,2.7314e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00301236) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743243,0.0217524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308943,-0.00288495) , 
3, -0.677702, 1, 0, 0.409375,0.0106919) , 
1, -0.130946, 1, 0, 0.5,1.86763e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767442,0.00674449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436482,0.0031231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421053,-0.00882599) , 
2, -0.984376, 0, 0, 0.430584,-0.00549434) , 
1, -1.08907, 1, 0, 0.5,2.21719e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00297641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.0230123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.0013443) , 
3, -2.01632, 1, 0, 0.461017,-0.0125194) , 
2, -0.616325, 1, 0, 0.5,1.97235e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0131602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763889,0.0103948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392405,-0.0026017) , 
3, -2.42136, 1, 0, 0.441392,-0.00423175) , 
3, -3.75783, 1, 0, 0.5,2.6374e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00680927) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830986,0.0194077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420582,-0.0011365) , 
5, 0.809418, 0, 0, 0.476834,0.00508743) , 
0, -2.15733, 1, 0, 0.5,2.87362e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00298797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507692,0.0211514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384314,-0.00205805) , 
1, 0.0773967, 1, 0, 0.409375,0.0105762) , 
1, -0.130946, 1, 0, 0.5,3.31169e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00265117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761905,0.0109575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341232,-0.00767033) , 
6, 362.903, 0, 0, 0.461017,-0.0110694) , 
2, -0.616325, 1, 0, 0.5,2.72727e-05)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00643246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504608,0.0037125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.011487) , 
5, 0.047558, 0, 0, 0.476834,0.00480688) , 
0, -2.15733, 1, 0, 0.5,2.47881e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.012399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51087,-0.00958053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427313,0.000751141) , 
2, -2.96925, 1, 0, 0.441392,-0.00393397) , 
3, -3.75783, 1, 0, 0.5,2.08079e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00262133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.0225655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.00174887) , 
3, -2.01632, 1, 0, 0.461017,-0.0109377) , 
2, -0.616325, 1, 0, 0.5,2.20554e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0121316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763889,0.00980832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392405,-0.00240097) , 
3, -2.42136, 1, 0, 0.441392,-0.00381918) , 
3, -3.75783, 1, 0, 0.5,2.80251e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00278769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44898,0.0074293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28,-0.0144629) , 
5, 0.0853964, 0, 0, 0.409375,0.00980551) , 
1, -0.130946, 1, 0, 0.5,2.94903e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693878,0.0169443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502959,-0.000707996) , 
2, 0.56014, 0, 0, 0.519784,0.00341394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342857,-0.00688371) , 
4, 0.21852, 0, 0, 0.5,2.2326e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00253562) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.0211172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.00158606) , 
3, -2.01632, 1, 0, 0.461017,-0.0105497) , 
2, -0.616325, 1, 0, 0.5,2.11452e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0120083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475771,0.000834105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271739,-0.00994682) , 
3, 0.683845, 1, 0, 0.441392,-0.00376963) , 
3, -3.75783, 1, 0, 0.5,2.61223e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00596708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830986,0.0175308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420582,-0.00101797) , 
5, 0.809418, 0, 0, 0.476834,0.00444568) , 
0, -2.15733, 1, 0, 0.5,2.43932e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00276265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743243,0.0198241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308943,-0.00257121) , 
3, -0.677702, 1, 0, 0.409375,0.00968577) , 
1, -0.130946, 1, 0, 0.5,2.78435e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767442,0.00591507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436482,0.00317946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421053,-0.00847373) , 
2, -0.984376, 0, 0, 0.430584,-0.00470783) , 
1, -1.08907, 1, 0, 0.5,2.96128e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00257805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560386,0.00243644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227273,-0.0163333) , 
6, 260.354, 0, 0, 0.461017,-0.0106347) , 
2, -0.616325, 1, 0, 0.5,2.61693e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00270762) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507692,0.0199234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384314,-0.00207366) , 
1, 0.0773967, 1, 0, 0.409375,0.00945448) , 
1, -0.130946, 1, 0, 0.5,1.83453e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00235113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.0204412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.00172125) , 
3, -2.01632, 1, 0, 0.461017,-0.00972443) , 
2, -0.616325, 1, 0, 0.5,1.43599e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0117525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763889,0.00929696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392405,-0.00228875) , 
3, -2.42136, 1, 0, 0.441392,-0.00367353) , 
3, -3.75783, 1, 0, 0.5,1.95323e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00565872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513889,0.0139786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470852,-0.00108546) , 
0, -1.77902, 1, 0, 0.476834,0.00420629) , 
0, -2.15733, 1, 0, 0.5,2.14792e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0109346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651163,-0.0148679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423459,0.000289322) , 
3, -2.93889, 1, 0, 0.441392,-0.00336927) , 
3, -3.75783, 1, 0, 0.5,1.86639e-05)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00251227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530303,-0.014162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377953,0.00656985) , 
5, 0.356745, 0, 0, 0.409375,0.00876892) , 
1, -0.130946, 1, 0, 0.5,2.11618e-05)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693878,0.0157285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502959,-0.000665351) , 
2, 0.56014, 0, 0, 0.519784,0.00312498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342857,-0.00635302) , 
4, 0.21852, 0, 0, 0.5,1.82858e-05)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500982,0.00120147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6875,0.0144987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362319,-0.0178558) , 
2, 0.673047, 0, 0, 0.495726,-0.019521) , 
2, 0.167985, 1, 0, 0.5,1.74318e-05)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.00541571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,-0.012344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43662,0.00120033) , 
2, 0.253183, 0, 0, 0.43787,-0.00419587) , 
4, 0.758434, 0, 0, 0.5,1.49271e-05)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00540278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830986,0.0165958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420582,-0.000997582) , 
5, 0.809418, 0, 0, 0.476834,0.0040004) , 
0, -2.15733, 1, 0, 0.5,1.38457e-05)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00250567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44898,0.0067949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28,-0.013586) , 
5, 0.0853964, 0, 0, 0.409375,0.0087046) , 
1, -0.130946, 1, 0, 0.5,1.76714e-05)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767442,0.00538394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436482,0.00320332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421053,-0.00821807) , 
2, -0.984376, 0, 0, 0.430584,-0.00425569) , 
1, -1.08907, 1, 0, 0.5,1.22358e-05)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00235117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481172,0.00136219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.0192142) , 
2, -0.331997, 0, 0, 0.461017,-0.00968085) , 
2, -0.616325, 1, 0, 0.5,1.0417e-05)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00235405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743243,0.0180044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308943,-0.00248701) , 
3, -0.677702, 1, 0, 0.409375,0.00815057) , 
1, -0.130946, 1, 0, 0.5,8.00358e-06)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.0021644) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761905,0.010831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341232,-0.00696662) , 
6, 362.903, 0, 0, 0.461017,-0.00889979) , 
2, -0.616325, 1, 0, 0.5,1.10003e-05)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808511,-0.0120124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705882,0.0126926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425577,-0.00168851) , 
1, -0.868565, 1, 0, 0.474957,0.00244683) , 
1, -2.52626, 1, 0, 0.5,1.03988e-05)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00248013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507692,0.0185132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384314,-0.00198189) , 
1, 0.0773967, 1, 0, 0.409375,0.00858037) , 
1, -0.130946, 1, 0, 0.5,1.27971e-05)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00528407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488506,-0.00258846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452941,0.00794896) , 
0, -1.42041, 0, 0, 0.476834,0.00390592) , 
0, -2.15733, 1, 0, 0.5,9.75141e-06)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0102468) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651163,-0.0143393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423459,0.000312945) , 
3, -2.93889, 1, 0, 0.441392,-0.00312486) , 
3, -3.75783, 1, 0, 0.5,7.88384e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540117,0.0021321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288889,-0.0144376) , 
1, 0.82718, 1, 0, 0.519784,0.00283616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342857,-0.00581811) , 
4, 0.21852, 0, 0, 0.5,1.09773e-05)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00240193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,-0.0191141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382143,0.00517381) , 
5, 0.537645, 0, 0, 0.409375,0.00830035) , 
1, -0.130946, 1, 0, 0.5,7.73645e-06)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00497925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830986,0.015732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420582,-0.000957628) , 
5, 0.809418, 0, 0, 0.476834,0.0036746) , 
0, -2.15733, 1, 0, 0.5,8.40195e-06)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00223819) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44898,0.00639125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28,-0.0133289) , 
5, 0.0853964, 0, 0, 0.409375,0.00773081) , 
1, -0.130946, 1, 0, 0.5,1.22097e-05)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0097288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763889,0.00904933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392405,-0.0020467) , 
3, -2.42136, 1, 0, 0.441392,-0.00293914) , 
3, -3.75783, 1, 0, 0.5,7.53955e-06)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808511,-0.0110313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705882,0.0119412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425577,-0.00157998) , 
1, -0.868565, 1, 0, 0.474957,0.00226494) , 
1, -2.52626, 1, 0, 0.5,9.73828e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00230523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530303,-0.0129983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377953,0.00603207) , 
5, 0.356745, 0, 0, 0.409375,0.00793855) , 
1, -0.130946, 1, 0, 0.5,1.17205e-05)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00475191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791667,0.0124481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405213,-0.00120997) , 
6, 402.509, 0, 0, 0.476834,0.00350635) , 
0, -2.15733, 1, 0, 0.5,9.85437e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500982,0.000979697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6875,0.0135091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362319,-0.0157613) , 
2, 0.673047, 0, 0, 0.495726,-0.0157899) , 
2, 0.167985, 1, 0, 0.5,1.19422e-05)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00209742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507692,0.0166869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384314,-0.00196794) , 
1, 0.0773967, 1, 0, 0.409375,0.00721182) , 
1, -0.130946, 1, 0, 0.5,1.01512e-05)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.00460958) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,-0.0113915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43662,0.00119253) , 
2, 0.253183, 0, 0, 0.43787,-0.00353753) , 
4, 0.758434, 0, 0, 0.5,7.74841e-06)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.00917629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651163,-0.0140201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423459,0.000387748) , 
3, -2.93889, 1, 0, 0.441392,-0.00274195) , 
3, -3.75783, 1, 0, 0.5,7.18651e-06)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.0045315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504608,0.00285796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.00941357) , 
5, 0.047558, 0, 0, 0.476834,0.00334027) , 
0, -2.15733, 1, 0, 0.5,9.80255e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540117,0.00201408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288889,-0.0139146) , 
1, 0.82718, 1, 0, 0.519784,0.00258707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342857,-0.00531999) , 
4, 0.21852, 0, 0, 0.5,7.67526e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564644,-0.00155976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531915,0.0223687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37,-0.00271717) , 
4, 0.346849, 0, 0, 0.40081,0.00891729) , 
4, 0.398491, 0, 0, 0.5,4.92712e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536957,-0.00122083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39823,-0.00793448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396226,0.0280245) , 
6, 228.496, 0, 0, 0.39759,0.012717) , 
4, 0.308506, 0, 0, 0.5,2.65708e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808511,-0.00948022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705882,0.0111977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425577,-0.00152125) , 
1, -0.868565, 1, 0, 0.474957,0.00195529) , 
1, -2.52626, 1, 0, 0.5,-7.06232e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.0021227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44898,0.00593629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28,-0.0124535) , 
5, 0.0853964, 0, 0, 0.409375,0.00725207) , 
1, -0.130946, 1, 0, 0.5,-3.95757e-06)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536957,-0.00112884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39823,-0.0070383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396226,0.0246961) , 
6, 228.496, 0, 0, 0.39759,0.0117231) , 
4, 0.308506, 0, 0, 0.5,-6.57914e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575693,0.0012661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46,0.0143151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186916,-0.0143056) , 
0, -0.874406, 0, 0, 0.273885,-0.0144068) , 
6, 252.377, 0, 0, 0.5,-1.30701e-05)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575693,0.00113966) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46,0.0128174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186916,-0.0130728) , 
0, -0.874406, 0, 0, 0.273885,-0.0129946) , 
6, 252.377, 0, 0, 0.5,-1.88845e-05)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708333,-0.00529097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550201,-0.00332764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384342,0.00439809) , 
1, -0.130946, 1, 0, 0.462264,0.00338296) , 
0, 0.00560468, 0, 0, 0.5,-2.28758e-05)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708333,-0.00474232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501272,-0.00139241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350365,0.00727531) , 
4, 0.308506, 0, 0, 0.462264,0.00304373) , 
0, 0.00560468, 0, 0, 0.5,-2.08124e-05)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540117,0.00200033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288889,-0.013437) , 
1, 0.82718, 1, 0, 0.519784,0.0026924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342857,-0.00558096) , 
4, 0.21852, 0, 0, 0.5,-1.97118e-05)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575693,0.00109359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46,0.0116909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186916,-0.0123543) , 
0, -0.874406, 0, 0, 0.273885,-0.0124949) , 
6, 252.377, 0, 0, 0.5,-1.96321e-05)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708333,-0.00465889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501272,-0.00133106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350365,0.00702999) , 
4, 0.308506, 0, 0, 0.462264,0.00298964) , 
0, 0.00560468, 0, 0, 0.5,-2.2844e-05)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693878,0.0141063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502959,-0.000623092) , 
2, 0.56014, 0, 0, 0.519784,0.00261538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342857,-0.0054349) , 
4, 0.21852, 0, 0, 0.5,-2.14527e-05)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00182338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,-0.0200413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390351,0.00231241) , 
3, -2.01632, 1, 0, 0.461017,-0.00752435) , 
2, -0.616325, 1, 0, 0.5,-1.84798e-05)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.00978916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763889,0.00963013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392405,-0.00213979) , 
3, -2.42136, 1, 0, 0.441392,-0.00297222) , 
3, -3.75783, 1, 0, 0.5,-1.05757e-05)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.00894335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456221,-0.00520948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431611,0.00222491) , 
2, -1.00848, 1, 0, 0.441392,-0.00267354) , 
3, -3.75783, 1, 0, 0.5,-6.41981e-06)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534743,0.00189312) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560386,0.00303359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227273,-0.015558) , 
6, 260.354, 0, 0, 0.461017,-0.00775071) , 
2, -0.616325, 1, 0, 0.5,-4.65825e-06)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500982,0.000881164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6875,0.0118399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362319,-0.0139538) , 
2, 0.673047, 0, 0, 0.495726,-0.0142388) , 
2, 0.167985, 1, 0, 0.5,-8.74458e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,-0.00415742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488506,-0.00269144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452941,0.00751571) , 
0, -1.42041, 0, 0, 0.476834,0.00302923) , 
0, -2.15733, 1, 0, 0.5,-8.38156e-06)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764706,0.00420969) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,-0.0110106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43662,0.00119055) , 
2, 0.253183, 0, 0, 0.43787,-0.00323576) , 
4, 0.758434, 0, 0, 0.5,-8.40034e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594771,-0.00189824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530303,-0.0125593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377953,0.00546649) , 
5, 0.356745, 0, 0, 0.409375,0.00644845) , 
1, -0.130946, 1, 0, 0.5,-7.41898e-06)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
