#include "variables.h"
#include <iostream>
#include "TSystem.h"
#include <vector>
#include "TH1.h"
#include "TChain.h"
#include <string>
#include "TString.h"
#include "TH1D.h"
#include "TFile.h"
#include <cmath>

//#include "Math/LorentzVector.h"
//#include "ttH-13TeVMultiLeptons/TemplateMakers/interface/objectClasses.h"
#include "ttH-13TeVMultiLeptons/TemplateMakers/src/LinkDef.h" // generated by Charlie
// #include "FWCore/FWLite/interface/AutoLibraryLoader.h"

// typedef std::vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > > vecTLV;
// typedef ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > TLV;


void addvarstotree(TString infiles, TString outfile)
{
    

    //TFile *file = new TFile("ttH125.root");
    //TTree *newchain = (TTree*)file->Get("summaryTree");   

    TChain *chain = new TChain("OSTwoLepAna/summaryTree"); //"summaryTree");
    
    
    //newchain->Add("ttH125.root"); 
    chain->Add(infiles);
    
    
    int chainentries = chain->GetEntries();   
    cout << chainentries << endl;  

    TFile *copiedfile = new TFile( outfile, "UPDATE"); //"UPDATE"); // #, 'test' ) // "RECREATE");

    
    // TTree *newtree = (TTree*)chain->CloneTree(0);
    TTree *newtree = new TTree("summaryTree","summaryTree");
    
    
    Int_t cachesize = 100000000;   //100 MBytes
    chain->SetCacheSize(cachesize);   //<<<
    chain->SetCacheLearnEntries(20); 
    
    //vector<ttH::Lepton> *preselLeps_intree=0; // have to do this
    
    double mcwgt_intree = -999.;
    double wgt_intree = -999.;
    double wallTimePerEvent_intree = -99.;

    int eventnum_intree = -999;
    int higgs_decay_intree = -9999;

    int lumiBlock_intree = -999;
    int runNumber_intree = -999;
    
    vector<ttH::Lepton> *preselected_leptons_intree=0;
    vector<ttH::Lepton> *loose_leptons_intree=0;
    vector<ttH::Lepton> *cutBased_leptons_intree=0;
    vector<ttH::Lepton> *looseMvaBased_leptons_intree=0;
    vector<ttH::Lepton> *tightMvaBased_leptons_intree=0;

    vector<ttH::Electron> *raw_electrons_intree=0;               
    vector<ttH::Electron> *preselected_electrons_intree=0;
    vector<ttH::Electron> *loose_electrons_intree=0;
    vector<ttH::Electron> *cutBased_electrons_intree=0;
    vector<ttH::Electron> *looseMvaBased_electrons_intree=0;
    vector<ttH::Electron> *tightMvaBased_electrons_intree=0;

    vector<ttH::Muon> *raw_muons_intree=0;
    vector<ttH::Muon> *preselected_muons_intree=0;
    vector<ttH::Muon> *loose_muons_intree=0;
    vector<ttH::Muon> *cutBased_muons_intree=0;
    vector<ttH::Muon> *looseMvaBased_muons_intree=0;
    vector<ttH::Muon> *tightMvaBased_muons_intree=0;        
    
    vector<ttH::Jet> *preselected_jets_intree=0;
    vector<ttH::Jet> *loose_bJets_intree=0;
    vector<ttH::Jet> *tight_bJets_intree=0;

    vector<ttH::MET> *met_intree=0;

    vector<ttH::GenParticle> *pruned_genParticles_intree=0;

    vector<ttH::Lepton> *tight_leptons_intree=0;
    vector<ttH::Electron> *tight_electrons_intree=0;
    vector<ttH::Muon> *tight_muons_intree=0;

    double numLooseBJets_handle = -99.; //n.zeros(1,dtype=float)
    double numMediumBJets_handle = -99.; //n.zeros(1,dtype=float)
    double deltaR_boosted_daughters_handle = 0.; //n.zeros(1,dtype=float)
    double SumPt_handle = 0.; //n.zeros(1,dtype=float)
    double MHT_handle = 0.; //n.zeros(1,dtype=float)
    double SumJetMass_handle = 0.; //n.zeros(1,dtype=float)
    double SumNonTaggedJetMass_handle = 0.; //n.zeros(1,dtype=float)
    double SumJetPt_handle = 0.; //n.zeros(1,dtype=float)
    double AvgBtagDiscNonBtags_handle = 0.; //n.zeros(1,dtype=float)
    double AvgBtagDiscBtags_handle = 0.; //n.zeros(1,dtype=float)
    double MinDrJets_handle = 0.; //n.zeros(1,dtype=float)
    double NumHiggsLikeDijet15_handle = 0.; //n.zeros(1,dtype=float)
    double HiggsLikeDijetMass2_handle = 0.; //n.zeros(1,dtype=float)
    double HiggsLikeDijetMass_handle = 0.; //n.zeros(1,dtype=float)
    double GenHiggsDijetMass_handle = 0.; //n.zeros(1,dtype=float)
    double DeltaPhiMetLepLep_handle = 0.; //n.zeros(1,dtype=float)
    double DeltaRMetLepLep_handle = 0.; //n.zeros(1,dtype=float)
    double MTMetLepLep_handle = 0.; //n.zeros(1,dtype=float)
    double MassMetLepLep_handle = 0.; //n.zeros(1,dtype=float)
    double MaxDeltaPhiMetJet_fromHiggs_handle = 0.; //n.zeros(1,dtype=float)
    double MinDeltaPhiMetJet_fromHiggs_handle = 0.; //n.zeros(1,dtype=float)
    double MaxDeltaPhiMetJet_handle = 0.; //n.zeros(1,dtype=float)
    double MinDeltaPhiMetJet_handle = 0.; //n.zeros(1,dtype=float)
    double DeltaPhiMetLep2_handle = 0.; //n.zeros(1,dtype=float)
    double DeltaPhiMetLep1_handle = 0.; //n.zeros(1,dtype=float)
    double DeltaRJets_FromHiggs_handle = 0.; //n.zeros(1,dtype=float)
    double DeltaPhiJets_FromHiggs_handle = 0.; //n.zeros(1,dtype=float)
    double WLikeDijetMass81_handle = 0.; //n.zeros(1,dtype=float)
    double DeltaPhiLepLep_handle = 0.; //n.zeros(1,dtype=float)
    double DeltaRLepLep_handle = 0.; //n.zeros(1,dtype=float)
    double vetoZmass_handle = 0.; //n.zeros(1,dtype=float)
    double vetoZmassSFOS_handle = 0.; //n.zeros(1,dtype=float)
    double minMassLepLep_handle = 0.; //n.zeros(1,dtype=float)
    double metLD_handle = 0.; //n.zeros(1,dtype=float)

    int num_preselected_leptons_handle = -99;
    double preselected_leptons_1_pt_handle = -99.;
    double preselected_leptons_2_pt_handle = -99.;
    int num_tightMvaBased_electrons_handle = -99;
    int num_tightMvaBased_muons_handle = -99;
    int num_tightMvaBased_leptons_handle = -99;
    int num_looseMvaBased_electrons_handle = -99;
    int num_looseMvaBased_muons_handle = -99;
    int num_looseMvaBased_leptons_handle = -99;
    int tightMvaBased_leptons_1_charge_handle = -99;
    int tightMvaBased_leptons_2_charge_handle = -99;    
    int preselected_leptons_1_charge_handle = -99;
    int preselected_leptons_2_charge_handle = -99;
    int preselected_leptons_3_charge_handle = -99;
    int preselected_leptons_4_charge_handle = -99;
    double tightMvaBased_leptons_1_pt_handle = -99.;
    double tightMvaBased_leptons_2_pt_handle = -99.;
    bool tightMvaBased_electrons_1_isGsfCtfScPixChargeConsistent_handle = false;
    bool tightMvaBased_electrons_2_isGsfCtfScPixChargeConsistent_handle = false;
    double tightMvaBased_muons_1_chargeFlip_handle = 99.;
    double tightMvaBased_muons_2_chargeFlip_handle = 99.;
    double met_pt_handle = -99.;
    int num_preselected_jets_handle = -99;
    int num_loose_bjets_charlie_handle = -99;
    int num_tight_bjets_charlie_handle = -99;

    chain->SetBranchAddress("mcwgt", &mcwgt_intree);
    chain->SetBranchAddress("wgt", &wgt_intree);
    chain->SetBranchAddress("wallTimePerEvent", &wallTimePerEvent_intree);

    chain->SetBranchAddress("eventnum", &eventnum_intree);
    chain->SetBranchAddress("lumiBlock", &lumiBlock_intree);
    chain->SetBranchAddress("runNumber", &runNumber_intree);
    chain->SetBranchAddress("higgs_decay", &higgs_decay_intree);

    chain->SetBranchAddress("preselected_leptons", &preselected_leptons_intree);
    chain->SetBranchAddress("preselected_electrons", &preselected_electrons_intree);
    chain->SetBranchAddress("preselected_muons", &preselected_muons_intree);
    
    chain->SetBranchAddress("looseMvaBased_leptons", &loose_leptons_intree);
    chain->SetBranchAddress("looseMvaBased_electrons", &loose_electrons_intree);
    chain->SetBranchAddress("looseMvaBased_muons", &loose_muons_intree);
    
    chain->SetBranchAddress("tightMvaBased_leptons", &tight_leptons_intree);
    chain->SetBranchAddress("tightMvaBased_electrons", &tight_electrons_intree);
    chain->SetBranchAddress("tightMvaBased_muons", &tight_muons_intree);
    
    //chain->SetBranchAddress("raw_electrons", &raw_electrons_intree);
    //chain->SetBranchAddress("raw_muons", &raw_muons_intree);
    
    //vector<ttH::Lepton> *cutBased_leptons_intree=0;
    //vector<ttH::Electron> *cutBased_electrons_intree=0;
    //vector<ttH::Muon> *cutBased_muons_intree=0;
    
    chain->SetBranchAddress("preselected_jets", &preselected_jets_intree);
    chain->SetBranchAddress("loose_bJets", &loose_bJets_intree);
    chain->SetBranchAddress("tight_bJets", &tight_bJets_intree);
    chain->SetBranchAddress("met", &met_intree);
    chain->SetBranchAddress("pruned_genParticles", &pruned_genParticles_intree);   
    
    newtree->Branch("mcwgt", &mcwgt_intree, "mcwgt/D");
    newtree->Branch("wgt", &wgt_intree, "wgt/D");
        
    newtree->Branch("num_preselected_leptons", &num_preselected_leptons_handle,"num_preselected_leptons/I");
    newtree->Branch("preselected_leptons_1_pt", &preselected_leptons_1_pt_handle,"preselected_leptons_1_pt/D");
    newtree->Branch("preselected_leptons_2_pt", &preselected_leptons_2_pt_handle,"preselected_leptons_2_pt/D");
    newtree->Branch("num_tightMvaBased_electrons", &num_tightMvaBased_electrons_handle,"num_tightMvaBased_electrons/I");
    newtree->Branch("num_tightMvaBased_muons", &num_tightMvaBased_muons_handle,"num_tightMvaBased_muons/I");
    newtree->Branch("num_tightMvaBased_leptons", &num_tightMvaBased_leptons_handle,"num_tightMvaBased_leptons/I");
    
    newtree->Branch("num_looseMvaBased_electrons", &num_looseMvaBased_electrons_handle,"num_looseMvaBased_electrons/I");
    newtree->Branch("num_looseMvaBased_muons", &num_looseMvaBased_muons_handle,"num_looseMvaBased_muons/I");
    newtree->Branch("num_looseMvaBased_leptons", &num_looseMvaBased_leptons_handle,"num_looseMvaBased_leptons/I");
    
    newtree->Branch("tightMvaBased_leptons_1_charge", &tightMvaBased_leptons_1_charge_handle,"tightMvaBased_leptons_1_charge/I");
    newtree->Branch("tightMvaBased_leptons_2_charge", &tightMvaBased_leptons_2_charge_handle,"tightMvaBased_leptons_2_charge/I");    
    newtree->Branch("preselected_leptons_1_charge", &preselected_leptons_1_charge_handle,"preselected_leptons_1_charge/I");
    newtree->Branch("preselected_leptons_2_charge", &preselected_leptons_2_charge_handle,"preselected_leptons_2_charge/I");
    newtree->Branch("preselected_leptons_3_charge", &preselected_leptons_3_charge_handle,"preselected_leptons_3_charge/I");
    newtree->Branch("preselected_leptons_4_charge", &preselected_leptons_4_charge_handle,"preselected_leptons_4_charge/I");
    newtree->Branch("tightMvaBased_leptons_1_pt", &tightMvaBased_leptons_1_pt_handle,"tightMvaBased_leptons_1_pt/D");
    newtree->Branch("tightMvaBased_leptons_2_pt", &tightMvaBased_leptons_2_pt_handle,"tightMvaBased_leptons_2_pt/D");
    newtree->Branch("tightMvaBased_electrons_1_isGsfCtfScPixChargeConsistent", &tightMvaBased_electrons_1_isGsfCtfScPixChargeConsistent_handle,"tightMvaBased_electrons_1_isGsfCtfScPixChargeConsistent/B");
    newtree->Branch("tightMvaBased_electrons_2_isGsfCtfScPixChargeConsistent", &tightMvaBased_electrons_2_isGsfCtfScPixChargeConsistent_handle,"tightMvaBased_electrons_2_isGsfCtfScPixChargeConsistent/B");
    newtree->Branch("tightMvaBased_muons_1_chargeFlip", &tightMvaBased_muons_1_chargeFlip_handle,"tightMvaBased_muons_1_chargeFlip/D");
    newtree->Branch("tightMvaBased_muons_2_chargeFlip", &tightMvaBased_muons_2_chargeFlip_handle,"tightMvaBased_muons_2_chargeFlip/D");
    newtree->Branch("num_preselected_jets", &num_preselected_jets_handle,"num_preselected_jets/I");    
    newtree->Branch("num_loose_bjets_charlie", &num_loose_bjets_charlie_handle,"num_loose_bjets_charlie/I");
    newtree->Branch("num_tight_bjets_charlie", &num_tight_bjets_charlie_handle,"num_tight_bjets_charlie/I");
    
    
    newtree->Branch("SumJetMass", &SumJetMass_handle,"SumJetMass/D");
    newtree->Branch("SumPt", &SumPt_handle,"SumPt/D");
    newtree->Branch("SumJetPt", &SumJetPt_handle,"SumJetPt/D");
    newtree->Branch("DeltaPhiMetLepLep", &DeltaPhiMetLepLep_handle,"DeltaPhiMetLepLep/D");
    newtree->Branch("DeltaRMetLepLep", &DeltaRMetLepLep_handle,"DeltaRMetLepLep/D");
    newtree->Branch("MTMetLepLep", &MTMetLepLep_handle,"MTMetLepLep/D");
    newtree->Branch("MassMetLepLep", &MassMetLepLep_handle,"MassMetLepLep/D");
    newtree->Branch("MaxDeltaPhiMetJet", &MaxDeltaPhiMetJet_handle,"MaxDeltaPhiMetJet/D");
    newtree->Branch("MinDeltaPhiMetJet", &MinDeltaPhiMetJet_handle,"MinDeltaPhiMetJet/D");
    newtree->Branch("DeltaPhiMetLep2", &DeltaPhiMetLep2_handle,"DeltaPhiMetLep2/D");
    newtree->Branch("DeltaPhiMetLep1", &DeltaPhiMetLep1_handle,"DeltaPhiMetLep1/D");
    newtree->Branch("DeltaRJets_FromHiggs", &DeltaRJets_FromHiggs_handle,"DeltaRJets_FromHiggs/D");
    newtree->Branch("DeltaPhiJets_FromHiggs", &DeltaPhiJets_FromHiggs_handle,"DeltaPhiJets_FromHiggs/D");
    newtree->Branch("WLikeDijetMass81", &WLikeDijetMass81_handle,"WLikeDijetMass81/D");
    newtree->Branch("DeltaPhiLepLep", &DeltaPhiLepLep_handle,"DeltaPhiLepLep/D");
    newtree->Branch("DeltaRLepLep", &DeltaRLepLep_handle,"DeltaRLepLep/D");

    newtree->Branch("AvgBtagDiscNonBtags", &AvgBtagDiscNonBtags_handle,"AvgBtagDiscNonBtags/D");
    newtree->Branch("AvgBtagDiscBtags", &AvgBtagDiscBtags_handle,"AvgBtagDiscBtags/D");
    newtree->Branch("SumNonTaggedJetMass", &SumNonTaggedJetMass_handle,"SumNonTaggedJetMass/D");
    newtree->Branch("MinDrJets", &MinDrJets_handle,"MinDrJets/D");
    newtree->Branch("NumHiggsLikeDijet15", &NumHiggsLikeDijet15_handle,"NumHiggsLikeDijet15/D");
    newtree->Branch("HiggsLikeDijetMass", &HiggsLikeDijetMass_handle,"HiggsLikeDijetMass/D");
    newtree->Branch("HiggsLikeDijetMass2", &HiggsLikeDijetMass2_handle,"HiggsLikeDijetMass2/D");

    newtree->Branch("vetoZmass", &vetoZmass_handle,"vetoZmass/D");
    newtree->Branch("vetoZmassSFOS", &vetoZmassSFOS_handle,"vetoZmassSFOS/D");
    newtree->Branch("MHT", &MHT_handle,"MHT/D");
    newtree->Branch("metLD", &metLD_handle,"metLD/D");
    newtree->Branch("minMassLepLep", &minMassLepLep_handle,"minMassLepLep/D");
    newtree->Branch("numLooseBJets", &numLooseBJets_handle, "numLooseBJets/D");
    newtree->Branch("numMediumBJets", &numMediumBJets_handle, "numMediumBJets/D");
    newtree->Branch("deltaR_boostedDaughters",&deltaR_boosted_daughters_handle,"deltaR_boostedDaughters/D");  

    // basic kinematics
    newtree->Branch("met_pt", &met_pt_handle,"met_pt/D");

    
    
    TH1D *leppt = new TH1D("leppt","leppt",100,0,400);
    
    //int count=0;
    double starttime = get_wall_time();
    for (int i=0; i<chainentries; i++)
    {
        chain->GetEntry(i);
        
        //if ((i % 5000)==0)
        //{
        //    cout << i << endl;
        //} 


        //cout << i << endl;
      
        //continue;
        
        //if ( ((*tight_leptons_intree).size()<2) && ((*preselected_leptons_intree).size()<4) ) continue;

/// need to fix this part:
//         vector<ttH::GenParticle> top_daughters;
//         vector<ttH::GenParticle> higgs_daughters;
//         
//         int gensize = (*pruned_genParticles_intree).size();
//          
//         for (auto genit = (*pruned_genParticles_intree).begin(); genit != (*pruned_genParticles_intree).end(); ++genit)
//         {
//   	    if (abs((*genit).grandmother_pdgID)==6) top_daughters.push_back(*genit);
//             
//             else if (abs(genParticle.grandmother_pdgID)==25)
//             {
//                 higgs_daughters.push_back(*genit);
//             }          
//            if len(higgs_daughters) > 0 and len(top_daughters) >0:
// //           {    
// //                  higgs_gChild = higgs_daughters[0]
// //               top_gChild = top_daughters[0]
// //               deltaPhi = higgs_gChild.obj.Phi() - top_gChild.obj.Phi()
// //               deltaEta = higgs_gChild.obj.Eta() - top_gChild.obj.Eta()
// //               deltaR_boosted_daughters_handle[0] = math.sqrt(math.pow(deltaPhi,2)+math.pow(deltaEta,2))
//          
        
        // this part ok:
        
        SumJetPt_handle = getsumpt(*preselected_jets_intree);	// A.K.A. 'HT'
        AvgBtagDiscNonBtags_handle = getAvgCSV(*preselected_jets_intree,"M",false);   			
        AvgBtagDiscBtags_handle = getAvgCSV(*preselected_jets_intree,"M",true);				
        MinDrJets_handle = getTwoObjKineExtreme(*preselected_jets_intree,"min","dR");
        SumPt_handle = getsumpt(*preselected_jets_intree, *preselected_electrons_intree, *preselected_muons_intree);	

        // calculate MHT
        auto objs_for_mht = getsumTLV(*preselected_leptons_intree,*preselected_jets_intree);
        MHT_handle = objs_for_mht.Pt();
        metLD_handle = 0.00397*((*met_intree)[0].obj.Pt()) + 0.00265*MHT_handle;

        auto taggedjets = keepTagged(*preselected_jets_intree,"M");
        auto nontaggedjets = keepUnTagged(*preselected_jets_intree,"M");
        numMediumBJets_handle = taggedjets.size();
        auto loosetaggedjets = keepTagged(*preselected_jets_intree,"L");
        numLooseBJets_handle = loosetaggedjets.size();

        SumNonTaggedJetMass_handle = (getsumTLV(nontaggedjets)).M(); // is this what this was at 8 TeV?
        HiggsLikeDijetMass2_handle = pickFromSortedTwoObjKine(*preselected_jets_intree,"mass", 2, 125.);
        HiggsLikeDijetMass_handle = pickFromSortedTwoObjKine(*preselected_jets_intree,"mass", 1, 125.);
        NumHiggsLikeDijet15_handle = getNumTwoObjKineInRange(*preselected_jets_intree,"mass",125.,15.);

        MaxDeltaPhiMetJet_handle = 	getTwoObjKineExtreme(*met_intree,*preselected_jets_intree,"max","dPhi");
        MinDeltaPhiMetJet_handle = 	getTwoObjKineExtreme(*met_intree,*preselected_jets_intree,"min","dPhi");
        //DeltaPhiMetLep2_handle = 	pickFromSortedTwoObjKine(*met_intree,*preselected_leptons_intree, "dPhi", 2, 0.0); // probably wrong
        //DeltaPhiMetLep1_handle = 	pickFromSortedTwoObjKine(*met_intree,*preselected_leptons_intree, "dPhi", 1, 0.0); // probably wrong

        WLikeDijetMass81_handle = 	pickFromSortedTwoObjKine(*preselected_jets_intree,"mass",1,81.);
        DeltaPhiLepLep_handle = 	getTwoObjKineExtreme(*preselected_leptons_intree,"min","dPhi");
        DeltaRLepLep_handle = 	getTwoObjKineExtreme(*preselected_leptons_intree,"min","dR");

        vetoZmass_handle = 	pickFromSortedTwoObjKine(*preselected_leptons_intree,"mass",1,91.2);
        vetoZmassSFOS_handle =   pickFromSortedTwoObjKine(*preselected_leptons_intree,"massSFOS",1,91.2);
        minMassLepLep_handle = 	getTwoObjKineExtreme(*preselected_leptons_intree,"min","mass");
              
        
        num_preselected_leptons_handle =                (*preselected_leptons_intree).size();
        preselected_leptons_1_pt_handle =               (*preselected_leptons_intree)[0].obj.Pt();
        preselected_leptons_2_pt_handle =               (*preselected_leptons_intree)[1].obj.Pt();
        num_tightMvaBased_electrons_handle =            (*tight_electrons_intree).size();
        num_tightMvaBased_muons_handle =                (*tight_muons_intree).size();
        num_tightMvaBased_leptons_handle =              (*tight_leptons_intree).size();
        num_looseMvaBased_electrons_handle =            (*loose_electrons_intree).size();
        num_looseMvaBased_muons_handle =                (*loose_muons_intree).size();
        num_looseMvaBased_leptons_handle =              (*loose_leptons_intree).size();
        
        
        tightMvaBased_electrons_1_isGsfCtfScPixChargeConsistent_handle = false;
        tightMvaBased_electrons_2_isGsfCtfScPixChargeConsistent_handle = false;
        tightMvaBased_muons_1_chargeFlip_handle = 99.;
        tightMvaBased_muons_2_chargeFlip_handle = 99.;
        preselected_leptons_1_charge_handle = -99;
        preselected_leptons_2_charge_handle = -99;
        preselected_leptons_3_charge_handle = -99;
        preselected_leptons_4_charge_handle = -99;        
                
        if (num_tightMvaBased_leptons_handle>0) tightMvaBased_leptons_1_charge_handle = (*tight_leptons_intree)[0].charge;
        if (num_tightMvaBased_leptons_handle>1) tightMvaBased_leptons_2_charge_handle = (*tight_leptons_intree)[1].charge;
        if (num_preselected_leptons_handle>0) preselected_leptons_1_charge_handle = (*preselected_leptons_intree)[0].charge;
        if (num_preselected_leptons_handle>1) preselected_leptons_2_charge_handle = (*preselected_leptons_intree)[1].charge;
        if (num_preselected_leptons_handle>2) preselected_leptons_3_charge_handle = (*preselected_leptons_intree)[2].charge;
        if (num_preselected_leptons_handle>3) preselected_leptons_4_charge_handle = (*preselected_leptons_intree)[3].charge;
        if (num_tightMvaBased_leptons_handle>0) tightMvaBased_leptons_1_pt_handle = (*tight_leptons_intree)[0].obj.Pt();
        if (num_tightMvaBased_leptons_handle>1) tightMvaBased_leptons_2_pt_handle = (*tight_leptons_intree)[1].obj.Pt();
        if (num_tightMvaBased_electrons_handle>0) tightMvaBased_electrons_1_isGsfCtfScPixChargeConsistent_handle = (*tight_electrons_intree)[0].isGsfCtfScPixChargeConsistent;
        if (num_tightMvaBased_electrons_handle>1) tightMvaBased_electrons_2_isGsfCtfScPixChargeConsistent_handle = (*tight_electrons_intree)[1].isGsfCtfScPixChargeConsistent;
        if (num_tightMvaBased_muons_handle>0) tightMvaBased_muons_1_chargeFlip_handle = (*tight_muons_intree)[0].chargeFlip;
        if (num_tightMvaBased_muons_handle>1) tightMvaBased_muons_2_chargeFlip_handle = (*tight_muons_intree)[1].chargeFlip;
        met_pt_handle = (*met_intree)[0].obj.Pt();
        num_preselected_jets_handle = (*preselected_jets_intree).size();
        num_loose_bjets_charlie_handle = (*loose_bJets_intree).size();
        num_tight_bjets_charlie_handle = (*tight_bJets_intree).size();
        
        newtree->Fill();
    }
    
    //leppt->Write();
    
    double endtime = get_wall_time();
    
    cout << " " << endl;
    cout << "took " << endtime - starttime << " seconds, " << endl;
    if (chainentries>0) cout << "an average of " << (endtime - starttime) / chainentries << " per event." << endl;
    cout << " " << endl;
    
    newtree->Write();
    copiedfile->Close();
    //delete chain;
    //delete newtree;
    //delete copiedfile;
}
