// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Wed May  7 17:02:47 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 1509
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1509" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 3
met_ld                        met_ld                        met_ld                        met_ld                                                          'F'    [0.0467127002776,2.72799015045]
jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex                                         'F'    [-1,0.999995946884]
MT_of_everything              MT_of_everything              MT_of_everything              MT_of_everything                                                'F'    [159.436035156,1627.85742188]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 3 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "met_ld", "jets_by_CSV_2_btagCombinedSecVertex", "MT_of_everything" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.0467127002775669;
      fVmax[0] = 2.72799015045166;
      fVmin[1] = -1;
      fVmax[1] = 0.999995946884155;
      fVmin[2] = 159.43603515625;
      fVmax[2] = 1627.857421875;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[3];
   double fVmax[3];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[3];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.0358839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572864,0.0145729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228261,-0.0543478) , 
1, 0.523285, 0, 0, 0.319574,-0.180426) , 
2, 369.211, 0, 0, 0.500331,0.000331345)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.0323387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696078,0.0377665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260401,-0.0436305) , 
1, 0.808901, 0, 0, 0.319574,-0.162403) , 
2, 369.211, 0, 0, 0.500331,0.000292369)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.0292077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572864,0.0133327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228261,-0.0450106) , 
1, 0.523285, 0, 0, 0.319574,-0.146208) , 
2, 369.211, 0, 0, 0.500331,0.000252843)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763092,0.0455965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682432,0.0270291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304187,-0.0325779) , 
2, 439.135, 0, 0, 0.405235,-0.0816685) , 
1, 0.619044, 0, 0, 0.500331,0.000203176)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.0249647) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696078,0.0284843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260401,-0.0339718) , 
1, 0.808901, 0, 0, 0.319574,-0.123879) , 
2, 369.211, 0, 0, 0.500331,0.000191786)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763092,0.0399245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682432,0.0221414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304187,-0.0280066) , 
2, 439.135, 0, 0, 0.405235,-0.0704662) , 
1, 0.619044, 0, 0, 0.500331,0.000156243)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.0121804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492958,-0.0101162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144444,-0.0509004) , 
1, 0.579117, 0, 0, 0.217009,-0.201178) , 
2, 299.286, 0, 0, 0.500331,0.000152557)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730126,0.0317571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.0171793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291391,-0.0267353) , 
2, 439.135, 0, 0, 0.393792,-0.0709927) , 
1, 0.523806, 0, 0, 0.500331,8.71618e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.0107178) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347826,-0.0114747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183824,-0.0447876) , 
2, 285.464, 0, 0, 0.217009,-0.175595) , 
2, 299.286, 0, 0, 0.500331,7.99628e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691901,0.0253698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633333,0.0173269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313269,-0.0251173) , 
0, 0.671565, 0, 0, 0.384697,-0.0727968) , 
1, 0.428569, 0, 0, 0.500331,3.66562e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815884,0.0397543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742991,0.0276426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363458,-0.0165663) , 
2, 509.06, 0, 0, 0.429383,-0.0415428) , 
1, 0.80952, 0, 0, 0.500331,3.25402e-05)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.0172298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.82,0.0398761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28388,-0.0222445) , 
1, 0.904106, 0, 0, 0.319574,-0.0824327) , 
2, 369.211, 0, 0, 0.500331,6.79067e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.0233857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579812,0.00742364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284211,-0.0270776) , 
1, 0.333331, 0, 0, 0.410643,-0.0559472) , 
0, 0.557432, 0, 0, 0.500331,5.78625e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00859798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347826,-0.00612546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183824,-0.038232) , 
2, 285.464, 0, 0, 0.217009,-0.13705) , 
2, 299.286, 0, 0, 0.500331,4.19777e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815884,0.0343264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831579,0.0408143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395778,-0.0115182) , 
2, 648.91, 0, 0, 0.429383,-0.0343746) , 
1, 0.80952, 0, 0, 0.500331,6.14151e-06)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691901,0.0192808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.00150081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251716,-0.0275093) , 
0, 0.422359, 0, 0, 0.384697,-0.052697) , 
1, 0.428569, 0, 0, 0.500331,4.75905e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.0221261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569231,0.00585388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268852,-0.0209697) , 
1, 0.333331, 0, 0, 0.397183,-0.0416932) , 
2, 439.135, 0, 0, 0.500331,3.25523e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0453104) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565753,0.00721206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337008,-0.0183308) , 
0, 0.422359, 0, 0, 0.459341,-0.0200765) , 
1, 0.904758, 0, 0, 0.500331,2.82402e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00715253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347826,-0.00331987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183824,-0.0335149) , 
2, 285.464, 0, 0, 0.217009,-0.110851) , 
2, 299.286, 0, 0, 0.500331,5.01521e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.0175618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579812,0.00459168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284211,-0.0198939) , 
1, 0.333331, 0, 0, 0.410643,-0.0403044) , 
0, 0.557432, 0, 0, 0.500331,1.87152e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0416368) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808917,0.0295662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413907,-0.00820991) , 
2, 578.985, 0, 0, 0.459341,-0.0175559) , 
1, 0.904758, 0, 0, 0.500331,1.06786e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00621105) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347826,-0.00175055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183824,-0.030195) , 
2, 285.464, 0, 0, 0.217009,-0.0949571) , 
2, 299.286, 0, 0, 0.500331,5.15991e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00657738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0105217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.0261477) , 
2, 542.184, 0, 0, 0.339888,-0.0919467) , 
1, 0.142855, 0, 0, 0.500331,2.40804e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0384857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.903226,0.047319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438219,-0.00580767) , 
2, 788.759, 0, 0, 0.459341,-0.0154647) , 
1, 0.904758, 0, 0, 0.500331,1.13545e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.0147484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579812,0.00344583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284211,-0.0163776) , 
1, 0.333331, 0, 0, 0.410643,-0.0328463) , 
0, 0.557432, 0, 0, 0.500331,5.16235e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.0054552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347826,-0.000532241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183824,-0.0274474) , 
2, 285.464, 0, 0, 0.217009,-0.0822173) , 
2, 299.286, 0, 0, 0.500331,4.21395e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00577365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.00759502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.022827) , 
2, 542.184, 0, 0, 0.339888,-0.0794136) , 
1, 0.142855, 0, 0, 0.500331,1.90768e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00564411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441964,-0.00868243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164384,-0.0341409) , 
1, 0.207933, 0, 0, 0.332432,-0.0745998) , 
0, 0.302072, 0, 0, 0.500331,8.36669e-06)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.0151341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649351,0.0140645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354555,-0.0100997) , 
2, 398.891, 0, 0, 0.397183,-0.0266383) , 
2, 439.135, 0, 0, 0.500331,-8.22559e-06)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730126,0.0144099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0419396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367992,-0.00881619) , 
2, 788.759, 0, 0, 0.393792,-0.0278138) , 
1, 0.523806, 0, 0, 0.500331,-6.00184e-07)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0339389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.853933,0.0316896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431818,-0.0051754) , 
0, 1.04538, 0, 0, 0.459341,-0.0126182) , 
1, 0.904758, 0, 0, 0.500331,1.55336e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00490928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.00388616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.0191093) , 
2, 542.184, 0, 0, 0.339888,-0.0660471) , 
1, 0.142855, 0, 0, 0.500331,4.46109e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00495336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406015,-0.00993554) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144231,-0.0338601) , 
1, 0.161341, 0, 0, 0.332432,-0.064065) , 
0, 0.302072, 0, 0, 0.500331,3.32681e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00448396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347826,0.00169631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183824,-0.0238673) , 
2, 285.464, 0, 0, 0.217009,-0.0658499) , 
2, 299.286, 0, 0, 0.500331,1.77254e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0312874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.903226,0.0382687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438219,-0.0042758) , 
2, 788.759, 0, 0, 0.459341,-0.0111069) , 
1, 0.904758, 0, 0, 0.500331,1.61414e-06)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00431885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.00201914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.0167487) , 
2, 542.184, 0, 0, 0.339888,-0.0574927) , 
1, 0.142855, 0, 0, 0.500331,3.00587e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.0040315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347826,0.00185021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183824,-0.0219359) , 
2, 285.464, 0, 0, 0.217009,-0.0587096) , 
2, 299.286, 0, 0, 0.500331,2.15419e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815884,0.0178805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.892857,0.0328956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407313,-0.0048917) , 
2, 788.759, 0, 0, 0.429383,-0.0146088) , 
1, 0.80952, 0, 0, 0.500331,7.18857e-06)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00422129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441964,-0.00706122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164384,-0.0262346) , 
1, 0.207933, 0, 0, 0.332432,-0.0536522) , 
0, 0.302072, 0, 0, 0.500331,2.35175e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0244649) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.873016,0.0234386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423729,-0.00432502) , 
1, 0.904758, 0, 0, 0.465201,-0.00951904) , 
0, 0.940472, 0, 0, 0.500331,1.13446e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00378709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417004,-0.00865362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165138,-0.0230613) , 
0, 0.332624, 0, 0, 0.339888,-0.0496097) , 
1, 0.142855, 0, 0, 0.500331,2.80099e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00350912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263736,-0.0211031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163522,-0.00449088) , 
1, 0.252299, 0, 0, 0.217009,-0.0504007) , 
2, 299.286, 0, 0, 0.500331,1.91196e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691901,0.0086055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875,0.0305808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358343,-0.00675973) , 
0, 1.16998, 0, 0, 0.384697,-0.0206551) , 
1, 0.428569, 0, 0, 0.500331,1.16769e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.0036205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494737,-0.0211136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276364,-0.00826691) , 
2, 379.615, 0, 0, 0.332432,-0.0454602) , 
0, 0.302072, 0, 0, 0.500331,1.70199e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.00997046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649351,0.0124248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354555,-0.00722142) , 
2, 398.891, 0, 0, 0.397183,-0.0163454) , 
2, 439.135, 0, 0, 0.500331,1.5829e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0251911) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,0.0364574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442673,-0.00302531) , 
0, 1.29458, 0, 0, 0.459341,-0.00796569) , 
1, 0.904758, 0, 0, 0.500331,1.72747e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00334827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,-0.00146107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.0125906) , 
2, 542.184, 0, 0, 0.339888,-0.0430953) , 
1, 0.142855, 0, 0, 0.500331,3.44647e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00296733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263736,-0.0191023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163522,-0.00197453) , 
1, 0.252299, 0, 0, 0.217009,-0.0419334) , 
2, 299.286, 0, 0, 0.500331,2.77732e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730126,0.0086703) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0292319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367992,-0.00509489) , 
2, 788.759, 0, 0, 0.393792,-0.0153757) , 
1, 0.523806, 0, 0, 0.500331,2.05381e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00312138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494737,-0.0201591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276364,-0.00623996) , 
2, 379.615, 0, 0, 0.332432,-0.0385339) , 
0, 0.302072, 0, 0, 0.500331,2.57072e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00300069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417004,-0.00722184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165138,-0.0178209) , 
0, 0.332624, 0, 0, 0.339888,-0.0383593) , 
1, 0.142855, 0, 0, 0.500331,2.39065e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0224584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.928571,0.0367787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,-0.00253722) , 
2, 858.684, 0, 0, 0.459341,-0.00674444) , 
1, 0.904758, 0, 0, 0.500331,1.77716e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0185001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547852,0.000865706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217009,-0.0112484) , 
2, 299.286, 0, 0, 0.465201,-0.00653967) , 
0, 0.940472, 0, 0, 0.500331,3.14699e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00271656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397849,-0.00960277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12987,-0.00530132) , 
2, 301.294, 0, 0, 0.339888,-0.0344382) , 
1, 0.142855, 0, 0, 0.500331,2.98478e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.00681607) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445466,-0.000692972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297872,-0.0137216) , 
0, 0.241223, 0, 0, 0.410643,-0.0135839) , 
0, 0.557432, 0, 0, 0.500331,2.59751e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.020575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,0.0311999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442673,-0.00230863) , 
0, 1.29458, 0, 0, 0.459341,-0.00595362) , 
1, 0.904758, 0, 0, 0.500331,2.24431e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.00726944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649351,0.0113204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354555,-0.0056571) , 
2, 398.891, 0, 0, 0.397183,-0.0114032) , 
2, 439.135, 0, 0, 0.500331,3.28716e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691901,0.00592476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875,0.0208265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358343,-0.00445319) , 
0, 1.16998, 0, 0, 0.384697,-0.0135658) , 
1, 0.428569, 0, 0, 0.500331,3.12423e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00220743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263736,-0.0165588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163522,0.0022133) , 
1, 0.252299, 0, 0, 0.217009,-0.0304144) , 
2, 299.286, 0, 0, 0.500331,3.10917e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00241999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.0140904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.00630062) , 
0, 0.700929, 0, 0, 0.339888,-0.0302672) , 
1, 0.142855, 0, 0, 0.500331,2.44566e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863248,0.0185406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52292,0.000921426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17757,-0.0164381) , 
2, 275.82, 0, 0, 0.469828,-0.00467608) , 
2, 648.91, 0, 0, 0.500331,2.21521e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0184729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.928571,0.0317704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,-0.00196328) , 
2, 858.684, 0, 0, 0.459341,-0.00512983) , 
1, 0.904758, 0, 0, 0.500331,1.90122e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00225864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494737,-0.0187204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276364,-0.00263941) , 
2, 379.615, 0, 0, 0.332432,-0.0271083) , 
0, 0.302072, 0, 0, 0.500331,2.75374e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00220789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.0135172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.00554743) , 
0, 0.700929, 0, 0, 0.339888,-0.027419) , 
1, 0.142855, 0, 0, 0.500331,2.57478e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730126,0.00584832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.88,0.0192182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369011,-0.0033232) , 
0, 1.16998, 0, 0, 0.393792,-0.00990735) , 
1, 0.523806, 0, 0, 0.500331,2.33835e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00206176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494737,-0.0169057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276364,-0.00247041) , 
2, 379.615, 0, 0, 0.332432,-0.0246665) , 
0, 0.302072, 0, 0, 0.500331,2.40339e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67942,0.00346748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418367,0.00244375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256018,-0.00853963) , 
2, 319.245, 0, 0, 0.319574,-0.0138417) , 
2, 369.211, 0, 0, 0.500331,2.23135e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0165136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.928571,0.0294559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,-0.00170979) , 
2, 858.684, 0, 0, 0.459341,-0.00442258) , 
1, 0.904758, 0, 0, 0.500331,1.79334e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00194116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.0127753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.00459938) , 
0, 0.700929, 0, 0, 0.339888,-0.023898) , 
1, 0.142855, 0, 0, 0.500331,2.45444e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0130509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63344,0.00407772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41556,-0.00268959) , 
0, 0.597935, 0, 0, 0.465201,-0.00420443) , 
0, 0.940472, 0, 0, 0.500331,2.23739e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691901,0.00430718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414498,0.000193886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344913,-0.00626682) , 
1, 0.156319, 0, 0, 0.384697,-0.00960249) , 
1, 0.428569, 0, 0, 0.500331,2.27808e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.030098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525186,0.00143728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298805,-0.0116225) , 
0, 0.24732, 0, 0, 0.48632,-0.00215855) , 
2, 858.684, 0, 0, 0.500331,2.04691e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.014701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,0.0234392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442673,-0.00149991) , 
0, 1.29458, 0, 0, 0.459341,-0.00380479) , 
1, 0.904758, 0, 0, 0.500331,2.11599e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.00483777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649351,0.0102539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354555,-0.00426787) , 
2, 398.891, 0, 0, 0.397183,-0.00727615) , 
2, 439.135, 0, 0, 0.500331,2.53301e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763092,0.00524655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44051,0.000505041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343284,-0.00576202) , 
1, 0.155867, 0, 0, 0.405235,-0.00648231) , 
1, 0.619044, 0, 0, 0.500331,2.36394e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00146027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263736,-0.0140142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163522,0.00651841) , 
1, 0.252299, 0, 0, 0.217009,-0.0196256) , 
2, 299.286, 0, 0, 0.500331,2.16599e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.027594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525186,0.00128685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298805,-0.0103615) , 
0, 0.24732, 0, 0, 0.48632,-0.00185509) , 
2, 858.684, 0, 0, 0.500331,1.61883e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691901,0.00365058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671642,-0.0113738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337051,-0.000650408) , 
0, 0.796169, 0, 0, 0.384697,-0.00802538) , 
1, 0.428569, 0, 0, 0.500331,1.67841e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0107881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652778,-0.011047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454756,-0.00030392) , 
0, 0.809944, 0, 0, 0.465201,-0.00334398) , 
0, 0.940472, 0, 0, 0.500331,1.70334e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0128672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,0.0205619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442673,-0.00126594) , 
0, 1.29458, 0, 0, 0.459341,-0.00321842) , 
1, 0.904758, 0, 0, 0.500331,1.78046e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00142639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.0122451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.00253286) , 
0, 0.700929, 0, 0, 0.339888,-0.0172641) , 
1, 0.142855, 0, 0, 0.500331,2.07148e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863248,0.0121888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52292,0.000952877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17757,-0.0130959) , 
2, 275.82, 0, 0, 0.469828,-0.00272583) , 
2, 648.91, 0, 0, 0.500331,1.91225e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0116873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.928571,0.0220204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,-0.00110998) , 
2, 858.684, 0, 0, 0.459341,-0.00286312) , 
1, 0.904758, 0, 0, 0.500331,1.55871e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00130162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.011414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.0022276) , 
0, 0.700929, 0, 0, 0.339888,-0.015688) , 
1, 0.142855, 0, 0, 0.500331,1.8127e-05)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674464,0.00343219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418605,-0.0200794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410283,-0.000810971) , 
0, 0.532988, 0, 0, 0.410643,-0.00642146) , 
0, 0.557432, 0, 0, 0.500331,1.67204e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.00912569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652778,-0.0103709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454756,-0.000176739) , 
0, 0.809944, 0, 0, 0.465201,-0.00274298) , 
0, 0.940472, 0, 0, 0.500331,1.52703e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00127081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494737,-0.0154561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276364,0.000849521) , 
2, 379.615, 0, 0, 0.332432,-0.0148205) , 
0, 0.302072, 0, 0, 0.500331,1.55911e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.00365668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649351,0.00953152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354555,-0.00356172) , 
2, 398.891, 0, 0, 0.397183,-0.00539397) , 
2, 439.135, 0, 0, 0.500331,1.45342e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00122616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.0114324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.00190669) , 
0, 0.700929, 0, 0, 0.339888,-0.014749) , 
1, 0.142855, 0, 0, 0.500331,1.36583e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815884,0.00561746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598456,0.0031113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384378,-0.00217361) , 
1, 0.461026, 0, 0, 0.429383,-0.00374813) , 
1, 0.80952, 0, 0, 0.500331,1.27249e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.0232322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525186,0.0011463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298805,-0.00887438) , 
0, 0.24732, 0, 0, 0.48632,-0.00139806) , 
2, 858.684, 0, 0, 0.500331,1.22733e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.00105462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219048,-0.0125216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21374,0.0112213) , 
0, 0.272603, 0, 0, 0.217009,-0.0139979) , 
2, 299.286, 0, 0, 0.500331,1.23824e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0100622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,0.0168258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442673,-0.000956491) , 
0, 1.29458, 0, 0, 0.459341,-0.0024009) , 
1, 0.904758, 0, 0, 0.500331,6.71092e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554873,0.00107136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640625,-0.0199669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267974,0.000218945) , 
1, 0.813628, 0, 0, 0.332432,-0.0124153) , 
0, 0.302072, 0, 0, 0.500331,8.90252e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815884,0.00526881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598456,0.00287964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384378,-0.00202189) , 
1, 0.461026, 0, 0, 0.429383,-0.00348608) , 
1, 0.80952, 0, 0, 0.500331,1.04155e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.0212693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525186,0.00106925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298805,-0.00810943) , 
0, 0.24732, 0, 0, 0.48632,-0.00122147) , 
2, 858.684, 0, 0, 0.500331,1.00856e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00101973) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.0106506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.0012361) , 
0, 0.700929, 0, 0, 0.339888,-0.0121836) , 
1, 0.142855, 0, 0, 0.500331,1.01213e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.00294805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649351,0.00862771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354555,-0.00304979) , 
2, 398.891, 0, 0, 0.397183,-0.00430023) , 
2, 439.135, 0, 0, 0.500331,9.49467e-06)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0090686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634568,0.00183221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385417,-0.00162946) , 
1, 0.450065, 0, 0, 0.459341,-0.00212069) , 
1, 0.904758, 0, 0, 0.500331,8.98373e-06)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925926,0.0177125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667464,0.00377231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4108,-0.00200873) , 
0, 0.586258, 0, 0, 0.484536,-0.00122651) , 
0, 1.32351, 0, 0, 0.500331,9.28775e-06)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.0192583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525186,0.000944721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298805,-0.00715839) , 
0, 0.24732, 0, 0, 0.48632,-0.00105332) , 
2, 858.684, 0, 0, 0.500331,1.01617e-05)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.000905336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.0104332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.000798257) , 
0, 0.700929, 0, 0, 0.339888,-0.0107522) , 
1, 0.142855, 0, 0, 0.500331,9.97994e-06)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.00819104) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470912,-0.000965727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301075,0.00703667) , 
0, 0.173152, 0, 0, 0.459341,-0.00188509) , 
1, 0.904758, 0, 0, 0.500331,9.35931e-06)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583048,0.000816246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219048,-0.0113892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21374,0.011906) , 
0, 0.272603, 0, 0, 0.217009,-0.0107366) , 
2, 299.286, 0, 0, 0.500331,9.08038e-06)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.00645813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652778,-0.011169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454756,0.000106562) , 
0, 0.809944, 0, 0, 0.465201,-0.00185832) , 
0, 0.940472, 0, 0, 0.500331,4.04843e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933333,0.0179969) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67426,0.00423917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406829,-0.00218695) , 
0, 0.578011, 0, 0, 0.487022,-0.000952051) , 
0, 1.45119, 0, 0, 0.500331,4.94979e-06)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.000830816) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.0101126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.000574578) , 
0, 0.700929, 0, 0, 0.339888,-0.00985558) , 
1, 0.142855, 0, 0, 0.500331,6.04122e-06)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00127633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538206,0.0066205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241176,-0.00372217) , 
0, 0.455392, 0, 0, 0.380655,0.00624846) , 
1, 0.238093, 0, 0, 0.500331,5.78779e-06)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815884,0.00396196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590047,-0.00413376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345679,0.00122111) , 
0, 0.546962, 0, 0, 0.429383,-0.00257038) , 
1, 0.80952, 0, 0, 0.500331,4.8659e-06)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.0175636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525186,0.000965745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298805,-0.00703792) , 
0, 0.24732, 0, 0, 0.48632,-0.000927299) , 
2, 858.684, 0, 0, 0.500331,5.0326e-06)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00078683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361022,-0.00401739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186047,0.0128164) , 
0, 0.209856, 0, 0, 0.339888,-0.00932496) , 
1, 0.142855, 0, 0, 0.500331,5.08707e-06)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.0012755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62234,0.00858556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280353,-0.00164803) , 
0, 0.57816, 0, 0, 0.380655,0.00623261) , 
1, 0.238093, 0, 0, 0.500331,3.62607e-06)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.0007703) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.0100072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.000347276) , 
0, 0.700929, 0, 0, 0.339888,-0.00913217) , 
1, 0.142855, 0, 0, 0.500331,3.66889e-06)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00122482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538206,0.00601476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241176,-0.00321542) , 
0, 0.455392, 0, 0, 0.380655,0.00598611) , 
1, 0.238093, 0, 0, 0.500331,3.64473e-06)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654247,0.00161173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675439,-0.0131974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33011,0.000513379) , 
0, 0.801018, 0, 0, 0.377088,-0.00462408) , 
1, 0.333331, 0, 0, 0.500331,3.0433e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.00590401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652778,-0.0101729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454756,0.000104052) , 
0, 0.809944, 0, 0, 0.465201,-0.00167757) , 
0, 0.940472, 0, 0, 0.500331,4.33294e-06)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00119281) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686275,-0.00944345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32282,0.00365542) , 
2, 509.06, 0, 0, 0.380655,0.00583387) , 
1, 0.238093, 0, 0, 0.500331,4.96716e-06)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.00236606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54902,-0.0178725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389546,6.82662e-05) , 
2, 425.497, 0, 0, 0.397183,-0.00341554) , 
2, 439.135, 0, 0, 0.500331,4.80313e-06)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863248,0.00721865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52292,0.000923976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17757,-0.0104039) , 
2, 275.82, 0, 0, 0.469828,-0.00147766) , 
2, 648.91, 0, 0, 0.500331,5.45367e-06)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.947368,0.0261977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490405,-0.000752421) , 
2, 828.856, 0, 0, 0.508197,-0.000945903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244444,0.00999157) , 
2, 229.361, 0, 0, 0.500331,3.34229e-06)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654247,0.00162198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675439,-0.0120551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33011,0.000344372) , 
0, 0.801018, 0, 0, 0.377088,-0.00463936) , 
1, 0.333331, 0, 0, 0.500331,5.95147e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.00573567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644444,-0.0111174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459091,-5.64484e-05) , 
0, 0.852345, 0, 0, 0.465201,-0.00161576) , 
0, 0.940472, 0, 0, 0.500331,6.66801e-06)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.000743404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608696,-0.00774994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246212,-0.000152282) , 
2, 445.828, 0, 0, 0.339888,-0.00878589) , 
1, 0.142855, 0, 0, 0.500331,6.86844e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00121305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62234,0.00839248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280353,-0.00168749) , 
0, 0.57816, 0, 0, 0.380655,0.00592202) , 
1, 0.238093, 0, 0, 0.500331,6.52432e-06)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888889,0.0070453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470912,-0.000870071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301075,0.00674485) , 
0, 0.173152, 0, 0, 0.459341,-0.00158921) , 
1, 0.904758, 0, 0, 0.500331,6.24909e-06)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579258,0.000935925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205036,-0.00675821) , 
2, 296.188, 0, 0, 0.508197,-0.000837078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244444,0.00878129) , 
2, 229.361, 0, 0, 0.500331,6.03719e-06)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.000719665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361022,-0.00367436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186047,0.0115749) , 
0, 0.209856, 0, 0, 0.339888,-0.00850257) , 
1, 0.142855, 0, 0, 0.500331,3.98925e-06)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00119321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62234,0.00777746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280353,-0.00143038) , 
0, 0.57816, 0, 0, 0.380655,0.00580814) , 
1, 0.238093, 0, 0, 0.500331,2.80642e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654247,0.00150779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675439,-0.0118196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33011,0.000415013) , 
0, 0.801018, 0, 0, 0.377088,-0.00430854) , 
1, 0.333331, 0, 0, 0.500331,2.88042e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00116645) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686275,-0.00877906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32282,0.00348622) , 
2, 509.06, 0, 0, 0.380655,0.00568121) , 
1, 0.238093, 0, 0, 0.500331,3.83403e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.00566392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646465,-0.00717564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451027,0.000112382) , 
0, 0.767542, 0, 0, 0.465201,-0.00159765) , 
0, 0.940472, 0, 0, 0.500331,3.70769e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.00216031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649351,0.00807322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354555,-0.00257313) , 
2, 398.891, 0, 0, 0.397183,-0.00310303) , 
2, 439.135, 0, 0, 0.500331,4.11001e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.00072661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583333,-0.00853193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.000563424) , 
0, 0.700929, 0, 0, 0.339888,-0.00857708) , 
1, 0.142855, 0, 0, 0.500331,4.04008e-06)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00110091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62234,0.00761883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280353,-0.001542) , 
0, 0.57816, 0, 0, 0.380655,0.0053551) , 
1, 0.238093, 0, 0, 0.500331,3.86825e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654247,0.00152592) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675439,-0.0108316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33011,0.000263686) , 
0, 0.801018, 0, 0, 0.377088,-0.00435289) , 
1, 0.333331, 0, 0, 0.500331,3.81072e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.00545654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57041,-0.00243269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391791,0.00110752) , 
0, 0.47073, 0, 0, 0.465201,-0.00153191) , 
0, 0.940472, 0, 0, 0.500331,4.47899e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.0010818) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538206,0.00548482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241176,-0.00305937) , 
0, 0.455392, 0, 0, 0.380655,0.00526392) , 
1, 0.238093, 0, 0, 0.500331,4.48059e-06)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654247,0.0014832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675439,-0.010364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33011,0.000235181) , 
0, 0.801018, 0, 0, 0.377088,-0.00423016) , 
1, 0.333331, 0, 0, 0.500331,3.82021e-06)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933333,0.0159833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67426,0.00353866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406829,-0.00183508) , 
0, 0.578011, 0, 0, 0.487022,-0.000803886) , 
0, 1.45119, 0, 0, 0.500331,4.3945e-06)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.000688509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397849,-0.00374582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12987,0.00853825) , 
2, 301.294, 0, 0, 0.339888,-0.0081108) , 
1, 0.142855, 0, 0, 0.500331,5.132e-06)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00112742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686275,-0.00802885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32282,0.0032883) , 
2, 509.06, 0, 0, 0.380655,0.00547815) , 
1, 0.238093, 0, 0, 0.500331,3.91081e-06)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747748,0.00212338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54902,-0.0170713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389546,0.000129025) , 
2, 425.497, 0, 0, 0.397183,-0.0030446) , 
2, 439.135, 0, 0, 0.500331,3.707e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654247,0.00140112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675439,-0.00943464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33011,0.000177101) , 
0, 0.801018, 0, 0, 0.377088,-0.00398957) , 
1, 0.333331, 0, 0, 0.500331,4.31639e-06)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0055791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57041,-0.00247361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391791,0.00112507) , 
0, 0.47073, 0, 0, 0.465201,-0.0015614) , 
0, 0.940472, 0, 0, 0.500331,4.67065e-06)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00109441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62234,0.007412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280353,-0.00146201) , 
0, 0.57816, 0, 0, 0.380655,0.00531955) , 
1, 0.238093, 0, 0, 0.500331,4.66754e-06)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54987,0.000680791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361022,-0.00343584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186047,0.0104698) , 
0, 0.209856, 0, 0, 0.339888,-0.0080256) , 
1, 0.142855, 0, 0, 0.500331,4.52004e-06)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863248,0.0063662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52292,0.000852766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17757,-0.00949145) , 
2, 275.82, 0, 0, 0.469828,-0.00127918) , 
2, 648.91, 0, 0, 0.500331,3.41277e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.00738373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455556,-0.00114319) , 
2, 562.522, 0, 0, 0.508197,-0.000853656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244444,0.00891977) , 
2, 229.361, 0, 0, 0.500331,1.73108e-06)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.947368,0.0242055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490405,-0.000644514) , 
2, 828.856, 0, 0, 0.508197,-0.000767195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244444,0.00795466) , 
2, 229.361, 0, 0, 0.500331,2.25917e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58871,-0.00103959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686275,-0.00842286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32282,0.00321225) , 
2, 509.06, 0, 0, 0.380655,0.00504182) , 
1, 0.238093, 0, 0, 0.500331,4.52356e-06)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
