// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Wed May  7 16:24:03 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 2753
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "2753" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
Match_ttW_SS_Bbq              Match_ttW_SS_Bbq              Match_ttW_SS_Bbq              Match_ttW_SS_Bbq                                                'F'    [-5.62501573563,2.28320336342]
Match_ttW_SS_Bbqq             Match_ttW_SS_Bbqq             Match_ttW_SS_Bbqq             Match_ttW_SS_Bbqq                                               'F'    [-13.385307312,3.12593984604]
Match_ttbar_fake_SS_Bqq       Match_ttbar_fake_SS_Bqq       Match_ttbar_fake_SS_Bqq       Match_ttbar_fake_SS_Bqq                                         'F'    [-13.9452381134,2.24645090103]
met_ld                        met_ld                        met_ld                        met_ld                                                          'F'    [0.0313147008419,3.33392071724]
jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex                                         'F'    [0.0104792993516,0.999998927116]
MT_of_everything              MT_of_everything              MT_of_everything              MT_of_everything                                                'F'    [176.496566772,2162.50683594]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Match_ttW_SS_Bbq", "Match_ttW_SS_Bbqq", "Match_ttbar_fake_SS_Bqq", "met_ld", "jets_by_CSV_2_btagCombinedSecVertex", "MT_of_everything" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -5.62501573562622;
      fVmax[0] = 2.28320336341858;
      fVmin[1] = -13.3853073120117;
      fVmax[1] = 3.12593984603882;
      fVmin[2] = -13.9452381134033;
      fVmax[2] = 2.24645090103149;
      fVmin[3] = 0.0313147008419037;
      fVmax[3] = 3.33392071723938;
      fVmin[4] = 0.010479299351573;
      fVmax[4] = 0.999998927116394;
      fVmin[5] = 176.496566772461;
      fVmax[5] = 2162.5068359375;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761337,0.0522673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623529,0.0247059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278788,-0.0442424) , 
5, 573.336, 0, 0, 0.385901,-0.114099) , 
4, 0.623039, 0, 0, 0.500182,0.00018162)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761337,0.047174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55467,0.0106963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243009,-0.0470689) , 
5, 493.968, 0, 0, 0.385901,-0.102698) , 
4, 0.623039, 0, 0, 0.500182,0.00016432)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638734,0.0244589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497573,-0.00136223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19589,-0.0532829) , 
0, -0.395925, 0, 0, 0.304729,-0.171307) , 
5, 460.212, 0, 0, 0.500182,0.000146004)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.0298435) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68125,0.0305391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263901,-0.0429092) , 
1, -0.0564631, 0, 0, 0.355816,-0.13202) , 
2, -0.83768, 1, 0, 0.500182,0.000102497)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771684,0.0422061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628433,0.0188795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283704,-0.0332055) , 
5, 573.336, 0, 0, 0.392077,-0.0823999) , 
4, 0.670159, 0, 0, 0.500182,8.07753e-05)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.0264001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68125,0.0259203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263901,-0.0377873) , 
1, -0.0564631, 0, 0, 0.355816,-0.115651) , 
2, -0.83768, 1, 0, 0.500182,8.0261e-05)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70916,0.0301263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732704,0.03069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28561,-0.0304795) , 
4, 0.814682, 0, 0, 0.36954,-0.0918825) , 
5, 554.784, 0, 0, 0.500182,5.57222e-05)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678105,0.0251598) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493381,-0.000437759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196275,-0.0440829) , 
2, -0.427239, 1, 0, 0.35775,-0.0966602) , 
4, 0.434559, 0, 0, 0.500182,5.03054e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638734,0.0179628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,-0.00788791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171233,-0.0437967) , 
0, -0.727778, 0, 0, 0.304729,-0.122284) , 
5, 460.212, 0, 0, 0.500182,1.53791e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808896,0.0396394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710914,0.0341207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356945,-0.0196314) , 
3, 0.817649, 0, 0, 0.412861,-0.0524308) , 
4, 0.811519, 0, 0, 0.500182,-2.55054e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.0214373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765,0.0336346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290503,-0.028049) , 
1, 0.398166, 0, 0, 0.355816,-0.0911921) , 
2, -0.83768, 1, 0, 0.500182,1.36547e-05)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70916,0.0239642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673077,0.0198053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286466,-0.0249431) , 
0, 0.285141, 0, 0, 0.36954,-0.0707675) , 
5, 554.784, 0, 0, 0.500182,7.14779e-06)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.0190411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68125,0.0181173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263901,-0.0276827) , 
1, -0.0564631, 0, 0, 0.355816,-0.0798825) , 
2, -0.83768, 1, 0, 0.500182,3.53656e-06)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720441,0.023443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778481,0.037407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335003,-0.0183523) , 
5, 811.44, 0, 0, 0.374929,-0.0607258) , 
4, 0.528799, 0, 0, 0.500182,-1.25297e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.0123536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646809,0.00765734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215553,-0.0337703) , 
1, -0.0564631, 0, 0, 0.320248,-0.104807) , 
2, -0.0666475, 1, 0, 0.500182,3.44159e-06)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774403,0.0371093) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614173,0.0115895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310345,-0.0229902) , 
0, -0.466282, 0, 0, 0.445026,-0.0339284) , 
3, 0.817649, 0, 0, 0.500182,-2.75383e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70916,0.0198134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732704,0.017118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28561,-0.0195464) , 
4, 0.814682, 0, 0, 0.36954,-0.0564511) , 
5, 554.784, 0, 0, 0.500182,-1.75767e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.0110099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461397,-0.0072985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139151,-0.0410716) , 
0, -0.767855, 0, 0, 0.320248,-0.0917867) , 
2, -0.0666475, 1, 0, 0.500182,-1.57443e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0338301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533726,0.00331606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207084,-0.0301958) , 
5, 414.6, 0, 0, 0.427687,-0.0310689) , 
4, 0.858639, 0, 0, 0.500182,-5.01488e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774403,0.0322608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614173,0.00945709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310345,-0.0195303) , 
0, -0.466282, 0, 0, 0.445026,-0.0283572) , 
3, 0.817649, 0, 0, 0.500182,-4.44429e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696,0.0181578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531915,0.0047968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268344,-0.024029) , 
1, -1.14849, 0, 0, 0.388477,-0.0458382) , 
2, -1.60871, 1, 0, 0.500182,-3.25826e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557212,0.00590383) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267062,-0.0203062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118519,-0.0574118) , 
5, 302.571, 0, 0, 0.224576,-0.125106) , 
5, 365.64, 0, 0, 0.500182,-3.75684e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.00943896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77551,0.0216307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268966,-0.0231847) , 
0, 0.883102, 0, 0, 0.320248,-0.0766734) , 
2, -0.0666475, 1, 0, 0.500182,-5.69572e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0294888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808036,0.0322588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385862,-0.0100887) , 
5, 811.44, 0, 0, 0.427687,-0.0257086) , 
4, 0.858639, 0, 0, 0.500182,-6.27003e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774403,0.0282384) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614173,0.00795104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310345,-0.0167828) , 
0, -0.466282, 0, 0, 0.445026,-0.0237551) , 
3, 0.817649, 0, 0, 0.500182,-2.18608e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.00846241) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722222,0.0122552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0220647) , 
1, 0.398166, 0, 0, 0.320248,-0.0675311) , 
2, -0.0666475, 1, 0, 0.500182,-1.29629e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678105,0.0129064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768657,0.0234584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31828,-0.013702) , 
5, 811.44, 0, 0, 0.35775,-0.043455) , 
4, 0.434559, 0, 0, 0.500182,-2.47538e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557212,0.00508012) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267062,-0.0168598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118519,-0.0536639) , 
5, 302.571, 0, 0, 0.224576,-0.104345) , 
5, 365.64, 0, 0, 0.500182,-1.98553e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.0048865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792453,0.020916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215347,-0.0327048) , 
1, 0.88685, 0, 0, 0.282276,-0.103461) , 
2, 0.704385, 1, 0, 0.500182,-3.83127e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68254,0.017699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626186,0.0119801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361225,-0.0136068) , 
1, -0.613098, 0, 0, 0.431147,-0.0278747) , 
3, 0.660383, 0, 0, 0.500182,-4.92482e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0247275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473044,-4.93465e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195122,-0.0321652) , 
2, 0.748377, 1, 0, 0.427687,-0.0202294) , 
4, 0.858639, 0, 0, 0.500182,-4.09224e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70916,0.012856) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382045,-0.00450727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255952,-0.0400406) , 
1, -3.9874, 0, 0, 0.36954,-0.0336931) , 
5, 554.784, 0, 0, 0.500182,-3.43031e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696,0.0130812) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531915,0.00441056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268344,-0.0184894) , 
1, -1.14849, 0, 0, 0.388477,-0.031104) , 
2, -1.60871, 1, 0, 0.500182,-2.96103e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774403,0.0225604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549286,0.00285162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258222,-0.0190404) , 
5, 414.6, 0, 0, 0.445026,-0.0177892) , 
3, 0.817649, 0, 0, 0.500182,-3.25336e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678105,0.0106626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793814,0.0238194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328212,-0.0108165) , 
5, 890.808, 0, 0, 0.35775,-0.0346055) , 
4, 0.434559, 0, 0, 0.500182,-2.97404e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.00653062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424958,-0.00541898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154667,-0.0276723) , 
1, -1.42035, 0, 0, 0.320248,-0.0500118) , 
2, -0.0666475, 1, 0, 0.500182,-2.38622e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613452,0.00985164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490566,0.00340064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329472,-0.0192762) , 
1, -1.54563, 0, 0, 0.408163,-0.0323051) , 
3, 0.503116, 0, 0, 0.500182,-3.59205e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00385654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792453,0.0170163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215347,-0.0269547) , 
1, 0.88685, 0, 0, 0.282276,-0.078802) , 
2, 0.704385, 1, 0, 0.500182,-3.59356e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0209313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482838,0.00658055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392934,-0.0108789) , 
1, -1.40413, 0, 0, 0.427687,-0.016205) , 
4, 0.858639, 0, 0, 0.500182,-4.28411e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809179,0.0216082) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502706,0.0033197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347271,-0.0159569) , 
3, 0.363881, 0, 0, 0.44549,-0.0143077) , 
5, 743.928, 0, 0, 0.500182,-2.72199e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.00852449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671053,0.02086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318985,-0.0120657) , 
3, 0.817649, 0, 0, 0.355816,-0.0312141) , 
2, -0.83768, 1, 0, 0.500182,-1.7751e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00887972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773077,0.0205596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380444,-0.0137511) , 
2, -4.75335, 1, 0, 0.44956,-0.0303033) , 
1, -1.59156, 0, 0, 0.500182,-1.71951e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557212,0.00350722) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267062,-0.00922022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118519,-0.0471024) , 
5, 302.571, 0, 0, 0.224576,-0.0681075) , 
5, 365.64, 0, 0, 0.500182,-1.24474e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00345645) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792453,0.0144798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215347,-0.0243721) , 
1, 0.88685, 0, 0, 0.282276,-0.0692911) , 
2, 0.704385, 1, 0, 0.500182,-2.57391e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678105,0.00860648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417355,-0.0229357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346542,-0.00369011) , 
1, -3.97907, 1, 0, 0.35775,-0.026997) , 
4, 0.434559, 0, 0, 0.500182,-3.18636e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.00757014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671053,0.0187714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318985,-0.010811) , 
3, 0.817649, 0, 0, 0.355816,-0.0273988) , 
2, -0.83768, 1, 0, 0.500182,-2.53034e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00825657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773077,0.0181724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380444,-0.0125617) , 
2, -4.75335, 1, 0, 0.44956,-0.0278205) , 
1, -1.59156, 0, 0, 0.500182,-2.36588e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833333,0.0176579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473044,6.63214e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195122,-0.0238287) , 
2, 0.748377, 1, 0, 0.427687,-0.0129593) , 
4, 0.858639, 0, 0, 0.500182,-1.8924e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553693,0.00465858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392473,-0.00570456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28,-0.04649) , 
1, -3.8599, 0, 0, 0.379147,-0.0409146) , 
3, 0.345849, 0, 0, 0.500182,-1.6621e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756322,0.0165274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694329,0.00851067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34232,-0.00852047) , 
2, -2.37975, 1, 0, 0.452114,-0.0117421) , 
1, -0.0190596, 0, 0, 0.500182,-1.59864e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809179,0.0177628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450677,-2.47404e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405904,-0.02312) , 
1, -3.9874, 0, 0, 0.44549,-0.0110891) , 
5, 743.928, 0, 0, 0.500182,-9.90425e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00717003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773077,0.0163638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380444,-0.0109525) , 
2, -4.75335, 1, 0, 0.44956,-0.0237511) , 
1, -1.59156, 0, 0, 0.500182,-1.20384e-06)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.0048014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354402,-0.00243046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291429,-0.016772) , 
2, 0.594239, 1, 0, 0.320248,-0.0350501) , 
2, -0.0666475, 1, 0, 0.500182,8.0922e-07)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557212,0.00290589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267062,-0.00660704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118519,-0.0436629) , 
5, 302.571, 0, 0, 0.224576,-0.0547815) , 
5, 365.64, 0, 0, 0.500182,-2.63308e-06)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.880435,0.0285659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679372,0.0129029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429581,-0.00487945) , 
1, -0.32076, 0, 0, 0.472947,-0.00663322) , 
0, 1.15346, 0, 0, 0.500182,-1.43294e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774403,0.0153934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447725,-0.000350757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420354,-0.0244734) , 
1, -4.47851, 0, 0, 0.445026,-0.0109842) , 
3, 0.817649, 0, 0, 0.500182,-1.43274e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.00647802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671053,0.0158357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318985,-0.00927392) , 
3, 0.817649, 0, 0, 0.355816,-0.0227579) , 
2, -0.83768, 1, 0, 0.500182,4.9733e-06)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00650331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773077,0.0148116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380444,-0.0099028) , 
2, -4.75335, 1, 0, 0.44956,-0.0212071) , 
1, -1.59156, 0, 0, 0.500182,3.83972e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00270019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536364,-0.0286962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201729,-0.0108711) , 
0, 0.247237, 0, 0, 0.282276,-0.0520003) , 
2, 0.704385, 1, 0, 0.500182,5.01809e-06)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519901,-0.0144824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728246,0.0159983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389027,-0.00399762) , 
2, -1.34997, 1, 0, 0.49681,0.00942876) , 
1, -3.95031, 1, 0, 0.500182,5.84272e-06)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968254,0.0511933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544189,0.00315075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36452,-0.0105104) , 
3, 0.345849, 0, 0, 0.489219,-0.00344573) , 
0, 1.53004, 0, 0, 0.500182,1.35289e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846442,0.0205055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482773,-0.000174321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118519,-0.0399775) , 
5, 302.563, 0, 0, 0.462993,-0.00705134) , 
5, 838.5, 0, 0, 0.500182,2.14034e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765766,0.0120616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47137,-0.000721566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123967,-0.0263798) , 
5, 335.232, 0, 0, 0.433121,-0.0106536) , 
0, 0.400294, 0, 0, 0.500182,1.62793e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519901,-0.0132401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728246,0.0144174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389027,-0.00348491) , 
2, -1.34997, 1, 0, 0.49681,0.00858704) , 
1, -3.95031, 1, 0, 0.500182,9.79347e-06)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00595244) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773077,0.0137828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380444,-0.00911495) , 
2, -4.75335, 1, 0, 0.44956,-0.0190848) , 
1, -1.59156, 0, 0, 0.500182,1.55928e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00238952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536364,-0.0266625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201729,-0.00894408) , 
0, 0.247237, 0, 0, 0.282276,-0.0451942) , 
2, 0.704385, 1, 0, 0.500182,1.53975e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578726,0.00360251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360825,-0.0184401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307282,-0.00241808) , 
1, -2.98484, 1, 0, 0.325527,-0.0298137) , 
4, 0.246079, 0, 0, 0.500182,1.52421e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968254,0.0486434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496462,0.00297972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473623,-0.0087763) , 
1, -2.62627, 0, 0, 0.489219,-0.00298267) , 
0, 1.53004, 0, 0, 0.500182,1.30357e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553693,0.00347586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392473,-0.00405404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28,-0.0363992) , 
1, -3.8599, 0, 0, 0.379147,-0.0291731) , 
3, 0.345849, 0, 0, 0.500182,2.12427e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.00377409) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795181,0.0108572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275706,-0.00963985) , 
1, 0.852795, 0, 0, 0.320248,-0.0265655) , 
2, -0.0666475, 1, 0, 0.500182,1.74904e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846442,0.018439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482773,-0.000208336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118519,-0.0359321) , 
5, 302.563, 0, 0, 0.462993,-0.00612929) , 
5, 838.5, 0, 0, 0.500182,1.3942e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756322,0.0118882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828283,0.0159411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396833,-0.00443393) , 
4, 0.858639, 0, 0, 0.452114,-0.00790503) , 
1, -0.0190596, 0, 0, 0.500182,1.02342e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00217947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536364,-0.0258586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201729,-0.00756195) , 
0, 0.247237, 0, 0, 0.282276,-0.0407466) , 
2, 0.704385, 1, 0, 0.500182,1.56988e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774403,0.0116645) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447725,-0.000111784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420354,-0.0192558) , 
1, -4.47851, 0, 0, 0.445026,-0.00786754) , 
3, 0.817649, 0, 0, 0.500182,1.56277e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71039,0.00762541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428871,-0.00134657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0448764) , 
1, -4.35431, 0, 0, 0.418558,-0.010866) , 
2, -2.37975, 1, 0, 0.500182,1.72928e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.880435,0.0223435) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679372,0.0105005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429581,-0.00376534) , 
1, -0.32076, 0, 0, 0.472947,-0.00456946) , 
0, 1.15346, 0, 0, 0.500182,1.23116e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.00329181) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347258,-0.000298697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302564,-0.0114676) , 
2, 0.484092, 1, 0, 0.320248,-0.0228504) , 
2, -0.0666475, 1, 0, 0.500182,1.78982e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553693,0.00298622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392473,-0.00341087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28,-0.0320224) , 
1, -3.8599, 0, 0, 0.379147,-0.0246523) , 
3, 0.345849, 0, 0, 0.500182,1.44867e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968254,0.0457053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496462,0.00253313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473623,-0.00746325) , 
1, -2.62627, 0, 0, 0.489219,-0.00249272) , 
0, 1.53004, 0, 0, 0.500182,1.15065e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78022,0.0148482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495229,0.00226063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364008,-0.0162636) , 
1, -2.96768, 0, 0, 0.469355,-0.00560464) , 
2, -4.69284, 1, 0, 0.500182,1.81832e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698113,0.0337804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49636,0.00134894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49589,-0.0129072) , 
1, -3.91919, 0, 0, 0.496296,-0.00227112) , 
0, -2.98894, 1, 0, 0.500182,1.7617e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696,0.00607396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39835,-0.00237003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0892857,-0.046011) , 
1, -4.35431, 0, 0, 0.388477,-0.0126563) , 
2, -1.60871, 1, 0, 0.500182,1.77831e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.00309206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414219,-0.00257596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.130841,-0.0174225) , 
0, -1.04301, 0, 0, 0.320248,-0.0213215) , 
2, -0.0666475, 1, 0, 0.500182,1.18881e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846442,0.0159234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482773,-9.00695e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118519,-0.0333073) , 
5, 302.563, 0, 0, 0.462993,-0.00506255) , 
5, 838.5, 0, 0, 0.500182,5.92401e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00180496) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484663,-0.0197866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170068,-0.00341937) , 
4, 0.491933, 0, 0, 0.282276,-0.03322) , 
2, 0.704385, 1, 0, 0.500182,2.79479e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756322,0.0101065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.841584,0.0178217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414934,-0.00340901) , 
4, 0.905759, 0, 0, 0.452114,-0.00656342) , 
1, -0.0190596, 0, 0, 0.500182,3.43313e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774403,0.0100895) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495217,0.00218611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371919,-0.00815302) , 
3, 0.367992, 0, 0, 0.445026,-0.00660889) , 
3, 0.817649, 0, 0, 0.500182,8.34715e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968254,0.0436423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689655,0.0295673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484802,-0.00124366) , 
0, -2.8997, 1, 0, 0.489219,-0.00218811) , 
0, 1.53004, 0, 0, 0.500182,8.66599e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578726,0.00263771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360825,-0.0136867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307282,-0.00170629) , 
1, -2.98484, 1, 0, 0.325527,-0.0210544) , 
4, 0.246079, 0, 0, 0.500182,1.55127e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78022,0.0127854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495229,0.00201458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364008,-0.0142625) , 
1, -2.96768, 0, 0, 0.469355,-0.00469301) , 
2, -4.69284, 1, 0, 0.500182,1.34552e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.00401199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671053,0.0133133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318985,-0.00622208) , 
3, 0.817649, 0, 0, 0.355816,-0.0132177) , 
2, -0.83768, 1, 0, 0.500182,1.28817e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00404808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70614,0.00557094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334966,-0.0078325) , 
2, -3.22137, 1, 0, 0.44956,-0.0124621) , 
1, -1.59156, 0, 0, 0.500182,1.14249e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00166054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536364,-0.0228643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201729,-0.00427013) , 
0, 0.247237, 0, 0, 0.282276,-0.030146) , 
2, 0.704385, 1, 0, 0.500182,9.58491e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756322,0.00909098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885417,0.02686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433393,-0.00261572) , 
4, 0.952879, 0, 0, 0.452114,-0.00581571) , 
1, -0.0190596, 0, 0, 0.500182,1.00524e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698113,0.0282457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49636,0.00135293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49589,-0.0121647) , 
1, -3.91919, 0, 0, 0.496296,-0.00180759) , 
0, -2.98894, 1, 0, 0.500182,1.43339e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.00367188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671053,0.0121356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318985,-0.0056885) , 
3, 0.817649, 0, 0, 0.355816,-0.0120249) , 
2, -0.83768, 1, 0, 0.500182,1.43873e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968254,0.0416519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693204,0.006983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44092,-0.00233401) , 
1, -0.32076, 0, 0, 0.489219,-0.00191602) , 
0, 1.53004, 0, 0, 0.500182,1.28193e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813008,0.0180827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493117,0.000906654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36875,-0.025507) , 
1, -4.79577, 0, 0, 0.485551,-0.00269387) , 
2, -6.23491, 1, 0, 0.500182,1.8046e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00155705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484663,-0.018466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170068,-0.00166165) , 
4, 0.491933, 0, 0, 0.282276,-0.02803) , 
2, 0.704385, 1, 0, 0.500182,1.78125e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846442,0.0132899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482773,2.55075e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118519,-0.0303832) , 
5, 302.563, 0, 0, 0.462993,-0.0040168) , 
5, 838.5, 0, 0, 0.500182,1.68646e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840909,0.0157909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.878788,0.0222177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455215,-0.00185671) , 
4, 0.952879, 0, 0, 0.476911,-0.00315422) , 
1, 0.76719, 0, 0, 0.500182,1.26382e-05)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553693,0.00222509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392473,-0.00232111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28,-0.0260032) , 
1, -3.8599, 0, 0, 0.379147,-0.0177724) , 
3, 0.345849, 0, 0, 0.500182,1.72967e-05)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71039,0.0054846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451064,0.000317951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260355,-0.0148084) , 
1, -2.7514, 0, 0, 0.418558,-0.00746171) , 
2, -2.37975, 1, 0, 0.500182,1.43531e-05)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.00234872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380952,-0.0111906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293769,-0.00156499) , 
3, 0.546776, 0, 0, 0.320248,-0.0157171) , 
2, -0.0666475, 1, 0, 0.500182,1.14646e-05)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698113,0.025724) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49636,0.00115099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49589,-0.0105651) , 
1, -3.91919, 0, 0, 0.496296,-0.00160303) , 
0, -2.98894, 1, 0, 0.500182,9.84048e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578726,0.00213111) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413333,0.00610762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306818,-0.00726343) , 
0, -2.03001, 1, 0, 0.325527,-0.0166727) , 
4, 0.246079, 0, 0, 0.500182,1.002e-05)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00139266) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536364,-0.0210461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201729,-0.00268268) , 
0, 0.247237, 0, 0, 0.282276,-0.0249038) , 
2, 0.704385, 1, 0, 0.500182,8.05141e-06)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840909,0.0148126) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.878788,0.0205747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455215,-0.00170317) , 
4, 0.952879, 0, 0, 0.476911,-0.0029233) , 
1, 0.76719, 0, 0, 0.500182,8.49812e-06)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68254,0.00527289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435655,-0.000478687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391089,-0.0142277) , 
1, -4.35214, 0, 0, 0.431147,-0.00677458) , 
3, 0.660383, 0, 0, 0.500182,1.27225e-05)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78022,0.0106696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495229,0.00153555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364008,-0.0113218) , 
1, -2.96768, 0, 0, 0.469355,-0.00377141) , 
2, -4.69284, 1, 0, 0.500182,1.18198e-05)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.00319526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671053,0.0108831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318985,-0.00498661) , 
3, 0.817649, 0, 0, 0.355816,-0.0102778) , 
2, -0.83768, 1, 0, 0.500182,1.11425e-05)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968254,0.0394056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689655,0.0236446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484802,-0.000960468) , 
0, -2.8997, 1, 0, 0.489219,-0.00164937) , 
0, 1.53004, 0, 0, 0.500182,9.93785e-06)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00320953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453564,-0.00424843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386364,0.0216357) , 
3, 0.176486, 0, 0, 0.44956,-0.00964825) , 
1, -1.59156, 0, 0, 0.500182,1.44254e-05)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553693,0.002052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419355,0.0060753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359292,-0.0102552) , 
3, 0.210996, 1, 0, 0.379147,-0.016219) , 
3, 0.345849, 0, 0, 0.500182,1.18701e-05)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813008,0.0155306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488381,0.000134151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0373415) , 
1, -6.0145, 0, 0, 0.485551,-0.00223026) , 
2, -6.23491, 1, 0, 0.500182,9.64673e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00128738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484663,-0.0166791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170068,-0.000114058) , 
4, 0.491933, 0, 0, 0.282276,-0.0228279) , 
2, 0.704385, 1, 0, 0.500182,1.0009e-05)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678105,0.00331696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358477,-0.000592772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350365,-0.0216512) , 
4, 0.373779, 1, 0, 0.35775,-0.00902101) , 
4, 0.434559, 0, 0, 0.500182,9.64442e-06)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557212,0.00128236) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5125,-0.0226274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165816,-0.00309754) , 
4, 0.767721, 0, 0, 0.224576,-0.0220967) , 
5, 365.64, 0, 0, 0.500182,8.26652e-06)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840909,0.0135748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.878788,0.0189435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455215,-0.00153268) , 
4, 0.952879, 0, 0, 0.476911,-0.00261633) , 
1, 0.76719, 0, 0, 0.500182,8.37181e-06)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846442,0.01108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482773,9.45625e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118519,-0.0274174) , 
5, 302.563, 0, 0, 0.462993,-0.00321569) , 
5, 838.5, 0, 0, 0.500182,1.17243e-05)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513369,0.0109799) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502216,0.00137076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477419,-0.0158566) , 
1, -3.91919, 0, 0, 0.499221,-0.00259011) , 
0, -2.23578, 1, 0, 0.500182,8.21628e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696,0.00381582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39835,-0.00143886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0892857,-0.0344226) , 
1, -4.35431, 0, 0, 0.388477,-0.00755462) , 
2, -1.60871, 1, 0, 0.500182,7.9684e-06)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578726,0.00185107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490862,-0.00819681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191083,0.000430401) , 
5, 493.968, 0, 0, 0.325527,-0.0142753) , 
4, 0.246079, 0, 0, 0.500182,4.63202e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78022,0.00911303) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495229,0.00131704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364008,-0.00967957) , 
1, -2.96768, 0, 0, 0.469355,-0.00315959) , 
2, -4.69284, 1, 0, 0.500182,4.43131e-06)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597759,0.00198284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380952,-0.010761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293769,-0.00059305) , 
3, 0.546776, 0, 0, 0.320248,-0.0130528) , 
2, -0.0666475, 1, 0, 0.500182,4.31005e-06)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,-0.0222281) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689387,0.00500035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379619,-0.00255305) , 
2, -1.3639, 1, 0, 0.497227,0.00129278) , 
1, -7.88156, 1, 0, 0.500182,3.43006e-06)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553693,0.00183122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396116,0.00134875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352584,-0.0133622) , 
3, 0.27089, 1, 0, 0.379147,-0.0143512) , 
3, 0.345849, 0, 0, 0.500182,4.7447e-06)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968254,0.0373648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693204,0.00560683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44092,-0.00185214) , 
1, -0.32076, 0, 0, 0.489219,-0.00144559) , 
0, 1.53004, 0, 0, 0.500182,3.46171e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.92,0.028294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584472,0.00311412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394817,-0.00422247) , 
3, 0.454003, 0, 0, 0.492416,-0.00125468) , 
5, 1216.79, 0, 0, 0.500182,7.64164e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543554,0.00113713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536364,-0.019478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201729,-0.00108785) , 
0, 0.247237, 0, 0, 0.282276,-0.019919) , 
2, 0.704385, 1, 0, 0.500182,8.98848e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00288942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453564,-0.00384636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386364,0.0194106) , 
3, 0.176486, 0, 0, 0.44956,-0.00858789) , 
1, -1.59156, 0, 0, 0.500182,9.14131e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513369,0.0103792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502216,0.00118418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477419,-0.0142144) , 
1, -3.91919, 0, 0, 0.499221,-0.00242728) , 
0, -2.23578, 1, 0, 0.500182,7.3571e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813008,0.0144537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488381,6.2938e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0317103) , 
1, -6.0145, 0, 0, 0.485551,-0.00203693) , 
2, -6.23491, 1, 0, 0.500182,7.02654e-06)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71039,0.00410769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846154,0.0245914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404067,-0.00239926) , 
5, 939.05, 0, 0, 0.418558,-0.00542726) , 
2, -2.37975, 1, 0, 0.500182,7.24684e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840909,0.0121143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525929,0.00066092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208543,-0.00956781) , 
2, 0.704385, 1, 0, 0.476911,-0.00227841) , 
1, 0.76719, 0, 0, 0.500182,8.77102e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,-0.0196173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689387,0.00442979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379619,-0.0022492) , 
2, -1.3639, 1, 0, 0.497227,0.00115421) , 
1, -7.88156, 1, 0, 0.500182,7.76691e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00271584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453564,-0.00355562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386364,0.0170628) , 
3, 0.176486, 0, 0, 0.44956,-0.00803156) , 
1, -1.59156, 0, 0, 0.500182,8.24259e-06)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813008,0.0132405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493117,0.000587597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36875,-0.0175508) , 
1, -4.79577, 0, 0, 0.485551,-0.00184544) , 
2, -6.23491, 1, 0, 0.500182,6.76822e-06)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553693,0.00164451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575758,-0.0116396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252918,0.00194281) , 
4, 0.481665, 0, 0, 0.379147,-0.0127767) , 
3, 0.345849, 0, 0, 0.500182,6.6816e-06)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968254,0.035751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689655,0.0201257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484802,-0.000784307) , 
0, -2.8997, 1, 0, 0.489219,-0.00129385) , 
0, 1.53004, 0, 0, 0.500182,7.08358e-06)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578726,0.00163956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326087,-0.012097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325373,-0.00114002) , 
0, -0.831671, 0, 0, 0.325527,-0.0124783) , 
4, 0.246079, 0, 0, 0.500182,1.04167e-05)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,-0.0180856) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795,0.0123351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473453,-0.000546699) , 
2, -4.97424, 1, 0, 0.497227,0.00107052) , 
1, -7.88156, 1, 0, 0.500182,8.69655e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756322,0.00574176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922078,0.0292917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435966,-0.00170148) , 
0, 1.15346, 0, 0, 0.452114,-0.00346751) , 
1, -0.0190596, 0, 0, 0.500182,9.77512e-06)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513369,0.00919515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502216,0.0010738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477419,-0.0127857) , 
1, -3.91919, 0, 0, 0.499221,-0.00212972) , 
0, -2.23578, 1, 0, 0.500182,1.27263e-05)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78022,0.00771931) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975,0.0477701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461066,-0.00126769) , 
3, 1.60398, 0, 0, 0.469355,-0.0026085) , 
2, -4.69284, 1, 0, 0.500182,1.1728e-05)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557212,0.000997941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5125,-0.0197311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165816,-0.00164079) , 
4, 0.767721, 0, 0, 0.224576,-0.0168035) , 
5, 365.64, 0, 0, 0.500182,1.61995e-05)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678105,0.00257735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615132,-0.014215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293878,0.00141709) , 
5, 652.704, 0, 0, 0.35775,-0.0068153) , 
4, 0.434559, 0, 0, 0.500182,1.52727e-05)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809179,0.00655108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502706,0.00197407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347271,-0.00642968) , 
3, 0.363881, 0, 0, 0.44549,-0.00328085) , 
5, 743.928, 0, 0, 0.500182,1.61952e-05)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558777,0.00235808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453564,-0.00318585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386364,0.0164076) , 
3, 0.176486, 0, 0, 0.44956,-0.00692455) , 
1, -1.59156, 0, 0, 0.500182,1.47148e-05)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.00228511) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671053,0.00996173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318985,-0.00385206) , 
3, 0.817649, 0, 0, 0.355816,-0.00714528) , 
2, -0.83768, 1, 0, 0.500182,1.26301e-05)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
