/**
This Macro
Prepares the rootplas to be used in the TTHLep analysis, reading as input the BSM3G nutplas

Need to specify
0. See Declare constants
*/
/////
//   To run: root -b -q -l Rootplizer_TTHLep_DataMc.cc+'("/afs/cern.ch/user/b/binghuan/public/TTHLep/TestingRootFiles/TT_1.root","OutTree_1_rootplas.root")'
/////
/////
//   Prepare Root and Roofit
/////
#include "TFile.h"
#include "TObject.h"
#include "TTree.h"
#include "TTreePlayer.h"
#include <fstream>
#include <iostream>
#include <iomanip>
#include <iostream>
#include <TLorentzVector.h>
#include <cmath>
#include "TMath.h"
#include "TMVA/Reader.h"
#include "TH1F.h"
#include "TH2F.h"
#include "THStack.h"
#include "TLegend.h"
#include "TStyle.h"
#include "TGaxis.h"
#include "TCanvas.h"
#include "TGraphErrors.h"
#include "TGraphAsymmErrors.h"
#include "TEfficiency.h"
using namespace std;
////
//   Declare constants
/////
const int nentries = -1;//-1 is all entries  51 for first DiMuSR
string bkg = "voila";
string wgt = "ttH";
string phase = "Inclusive";
string regwgt = "RecoOpt";
string pairwgt = "MassVar";
bool debug = 0;
double evtwgt =0.;
/////
//   Declare analysis functions 
/////
//utils
double deltaPhi(double phi1, double phi2);
double deltaEta(double eta1, double eta2);
double deltaR(double dphi, double deta);
double getMTlepmet(double phi1, double phi2, double pt1, double pt2);
//Variable handleling
void rSetBranchAddress(TTree* readingtree);
void wSetBranchAddress(TTree* newtree);
void wClearInitialization();
void rGetEntry(Long64_t tentry);
void wBranch();
void bdtJet_arrange();
void bdtJet_sel(double loose, double medium, double tight);
void bdtJetPair_sel();
void JetPair_arrange();
void HBDTsync();
//Read LepMVA
void set_wgtMVA();
double get_JetMVA(int jet_en);
double get_PairMVA(int jpair_en);
/////
//   Variables to be read
/////
double rEVENT_event; TBranch* b_rEVENT_event =0;
double rEVENT_genWeight; TBranch* b_rEVENT_genWeight =0;
double rGen_type1PF_Met; TBranch* b_rGen_type1PF_Met =0;
double rnum_ishlep; TBranch* b_rnum_ishlep =0;
double rnum_Jet_matchLooseHJet; TBranch* b_rnum_Jet_matchLooseHJet =0;
double rnum_Jet_matchMediumHJet; TBranch* b_rnum_Jet_matchMediumHJet =0;
double rnum_Jet_matchTightHJet; TBranch* b_rnum_Jet_matchTightHJet =0;
double rnum_Gen_Leph; TBranch* b_rnum_Gen_Leph =0;
double rnum_Gen_Jeth; TBranch* b_rnum_Gen_Jeth =0;
double rnum_Gen_Leptop; TBranch* b_rnum_Gen_Leptop =0;
double rnum_Gen_Lvh; TBranch* b_rnum_Gen_Lvh =0;
double rnum_Gen_Lvtop; TBranch* b_rnum_Gen_Lvtop =0;
double rJet_numLoose; TBranch* b_rJet_numLoose =0;
double rMet_type1PF_pt; TBranch* b_rMet_type1PF_pt =0;
double rMet_type1PF_px; TBranch* b_rMet_type1PF_px =0;
double rMet_type1PF_py; TBranch* b_rMet_type1PF_py =0;
double rMet_type1PF_pz; TBranch* b_rMet_type1PF_pz =0;
double rMet_type1PF_phi; TBranch* b_rMet_type1PF_phi =0;
vector<double>* rFakeLep_pt; TBranch* b_rFakeLep_pt =0;
vector<double>* rFakeLep_eta; TBranch* b_rFakeLep_eta =0;
vector<double>* rFakeLep_phi; TBranch* b_rFakeLep_phi =0;
vector<double>* rFakeLep_energy; TBranch* b_rFakeLep_energy =0;
vector<double>* rcsvJet_isMediumHJet; TBranch* b_rcsvJet_isMediumHJet =0;
vector<double>* rcsvJet_partonFlavour; TBranch* b_rcsvJet_partonFlavour =0;
vector<double>* rcsvJet_pt; TBranch* b_rcsvJet_pt =0;
vector<double>* rcsvJet_eta; TBranch* b_rcsvJet_eta =0;
vector<double>* rcsvJet_phi; TBranch* b_rcsvJet_phi =0;
vector<double>* rcsvJet_energy; TBranch* b_rcsvJet_energy =0;
vector<double>* rJet_lepdrmin; TBranch* b_rJet_lepdrmin =0;
vector<double>* rJet_pt; TBranch* b_rJet_pt =0;
vector<double>* rJet_eta; TBranch* b_rJet_eta =0;
vector<double>* rJet_phi; TBranch* b_rJet_phi =0;
vector<double>* rJet_energy; TBranch* b_rJet_energy =0;
vector<double>* rJet_partonFlavour; TBranch* b_rJet_partonFlavour =0;
vector<double>* rJet_px; TBranch* b_rJet_px =0;
vector<double>* rJet_py; TBranch* b_rJet_py =0;
vector<double>* rJet_pz; TBranch* b_rJet_pz =0;
vector<double>* rJet_mass; TBranch* b_rJet_mass =0;
vector<double>* rJet_newpfCombinedInclusiveSecondaryVertexV2BJetTags; TBranch* b_rJet_newpfCombinedInclusiveSecondaryVertexV2BJetTags =0;
vector<double>* rJet_pfCombinedInclusiveSecondaryVertexV2BJetTags; TBranch* b_rJet_pfCombinedInclusiveSecondaryVertexV2BJetTags =0;
vector<double>* rJet_isLooseHJet; TBranch* b_rJet_isLooseHJet =0;
vector<double>* rJet_isMediumHJet; TBranch* b_rJet_isMediumHJet =0;
vector<double>* rJet_isTightHJet; TBranch* b_rJet_isTightHJet =0;
vector<double>* rJet_dRGenJeth; TBranch* b_rJet_dRGenJeth =0;
vector<double>* rJet_pfCombinedMVAV2BJetTags; TBranch* b_rJet_pfCombinedMVAV2BJetTags =0;
vector<double>* rJet_pfJetProbabilityBJetTags; TBranch* b_rJet_pfJetProbabilityBJetTags =0;
vector<double>* rJet_pileupId; TBranch* b_rJet_pileupId =0;
vector<double>* rJet_neutralHadEnergyFraction; TBranch* b_rJet_neutralHadEnergyFraction =0;
vector<double>* rJet_neutralEmEnergyFraction; TBranch* b_rJet_neutralEmEnergyFraction =0;
vector<double>* rJet_chargedHadronEnergyFraction; TBranch* b_rJet_chargedHadronEnergyFraction =0;
vector<double>* rJet_chargedEmEnergyFraction; TBranch* b_rJet_chargedEmEnergyFraction =0;
vector<double>* rJet_muonEnergyFraction; TBranch* b_rJet_muonEnergyFraction =0;
vector<double>* rJet_electronEnergy; TBranch* b_rJet_electronEnergy =0;
vector<double>* rJet_photonEnergy; TBranch* b_rJet_photonEnergy =0;
vector<double>* rJet_emEnergyFraction; TBranch* b_rJet_emEnergyFraction =0;
vector<double>* rJet_numberOfConstituents; TBranch* b_rJet_numberOfConstituents =0;
vector<double>* rJet_chargedMultiplicity; TBranch* b_rJet_chargedMultiplicity =0;
vector<double>* rJet_vtxMass; TBranch* b_rJet_vtxMass =0;
vector<double>* rJet_vtxNtracks; TBranch* b_rJet_vtxNtracks =0;
vector<double>* rJet_vtx3DVal; TBranch* b_rJet_vtx3DVal =0;
vector<double>* rJet_vtx3DSig; TBranch* b_rJet_vtx3DSig =0;
vector<double>* rJet_ishighestcsv; TBranch* b_rJet_ishighestcsv =0;
vector<double>* rJet_istophJet; TBranch* b_rJet_istophJet =0;
vector<double>* rJet_metptratio; TBranch* b_rJet_metptratio =0;
vector<double>* rJet_dilepmetptratio; TBranch* b_rJet_dilepmetptratio =0;
vector<double>* rJet_nonjdr; TBranch* b_rJet_nonjdr =0;
vector<double>* rJet_nonjdilepdr; TBranch* b_rJet_nonjdilepdr =0;
vector<double>* rJet_lepdrmax; TBranch* b_rJet_lepdrmax =0;
vector<double>* rJet_dilepdr; TBranch* b_rJet_dilepdr =0;
vector<double>* rJet_bjdr; TBranch* b_rJet_bjdr =0;
vector<double>* rJet_nonjdeta; TBranch* b_rJet_nonjdeta =0;
vector<double>* rJet_nonjdilepdeta; TBranch* b_rJet_nonjdilepdeta =0;
vector<double>* rJet_lepdetamin; TBranch* b_rJet_lepdetamin =0;
vector<double>* rJet_lepdetamax; TBranch* b_rJet_lepdetamax =0;
vector<double>* rJet_dilepdeta; TBranch* b_rJet_dilepdeta =0;
vector<double>* rJet_bjdeta; TBranch* b_rJet_bjdeta =0;
vector<double>* rJet_nonjdphi; TBranch* b_rJet_nonjdphi =0;
vector<double>* rJet_nonjdilepdphi; TBranch* b_rJet_nonjdilepdphi =0;
vector<double>* rJet_lepdphimin; TBranch* b_rJet_lepdphimin =0;
vector<double>* rJet_lepdphimax; TBranch* b_rJet_lepdphimax =0;
vector<double>* rJet_dilepdphi; TBranch* b_rJet_dilepdphi =0;
vector<double>* rJet_bjdphi; TBranch* b_rJet_bjdphi =0;
vector<double>* rJet_nonjptratio; TBranch* b_rJet_nonjptratio =0;
vector<double>* rJet_nonjdilepptratio; TBranch* b_rJet_nonjdilepptratio =0;
vector<double>* rJet_lepptratiomin; TBranch* b_rJet_lepptratiomin =0;
vector<double>* rJet_lepptratiomax; TBranch* b_rJet_lepptratiomax =0;
vector<double>* rJet_dilepptratio; TBranch* b_rJet_dilepptratio =0;
vector<double>* rJet_bjptratio; TBranch* b_rJet_bjptratio =0;
vector<double>* rFakeLep_ishlep; TBranch* b_rFakeLep_ishlep =0;
vector<double>* rFakeLep_ptoverlep; TBranch* b_rFakeLep_ptoverlep =0;
vector<double>* rFakeLep_ptovermetlep; TBranch* b_rFakeLep_ptovermetlep =0;
vector<double>* rFakeLep_rlepdrjet0csv; TBranch* b_rFakeLep_rlepdrjet0csv =0;
vector<double>* rFakeLep_rlepdrjet0mass; TBranch* b_rFakeLep_rlepdrjet0mass =0;
vector<double>* rFakeLep_rlepdrjet0mt; TBranch* b_rFakeLep_rlepdrjet0mt =0;
vector<double>* rFakeLep_rlepdrjet1mass; TBranch* b_rFakeLep_rlepdrjet1mass =0;
vector<double>* rFakeLep_sumjetsdphi; TBranch* b_rFakeLep_sumjetsdphi =0;
vector<double>* rFakeLep_3toncsvjetsdphi; TBranch* b_rFakeLep_3toncsvjetsdphi =0;
vector<double>* rFakeLep_csvjet2dr; TBranch* b_rFakeLep_csvjet2dr =0;
vector<double>* rFakeLep_csvjet3dr; TBranch* b_rFakeLep_csvjet3dr =0;
vector<double>* rFakeLep_metdphi; TBranch* b_rFakeLep_metdphi =0;
vector<double>* rFakeLep_metlepdphi; TBranch* b_rFakeLep_metlepdphi =0;
vector<double>* rFakeLep_minjetdr; TBranch* b_rFakeLep_minjetdr =0;
vector<double>* rFakeLep_mt; TBranch* b_rFakeLep_mt =0;
vector<double>* rFakeLep_ptovermet; TBranch* b_rFakeLep_ptovermet =0;
vector<double>* rFakeLep_rlepdrjet1mt; TBranch* b_rFakeLep_rlepdrjet1mt =0;
vector<double>* rFakeLep_sumjetsdr; TBranch* b_rFakeLep_sumjetsdr =0;
vector<double>* rFakeLep_3toncsvjetsdr; TBranch* b_rFakeLep_3toncsvjetsdr =0;
vector<double>* rFakeLep_csvjet0mass; TBranch* b_rFakeLep_csvjet0mass =0;
vector<double>* rFakeLep_csvjet1mass; TBranch* b_rFakeLep_csvjet1mass =0;
vector<double>* rFakeLep_csvjet1mt; TBranch* b_rFakeLep_csvjet1mt =0;
vector<double>* rFakeLep_csvjet2deta; TBranch* b_rFakeLep_csvjet2deta =0;
vector<double>* rFakeLep_csvjet2dphi; TBranch* b_rFakeLep_csvjet2dphi =0;
vector<double>* rFakeLep_csvjet3deta; TBranch* b_rFakeLep_csvjet3deta =0;
vector<double>* rFakeLep_csvjet3dphi; TBranch* b_rFakeLep_csvjet3dphi =0;
vector<double>* rFakeLep_metmt; TBranch* b_rFakeLep_metmt =0;
vector<double>* rFakeLep_minjetdphi; TBranch* b_rFakeLep_minjetdphi =0;
vector<double>* rJet_qg; TBranch* b_rJet_qg =0;
vector<double>* rJet_axis2; TBranch* b_rJet_axis2 =0;
vector<double>* rJet_ptD; TBranch* b_rJet_ptD =0;
vector<double>* rJet_mult; TBranch* b_rJet_mult =0;
vector<double>* rH_Gen_pt; TBranch* b_rH_Gen_pt =0;
vector<double>* rH_Gen_eta; TBranch* b_rH_Gen_eta =0;
vector<double>* rH_Gen_phi; TBranch* b_rH_Gen_phi =0;
vector<double>* rH_Gen_energy; TBranch* b_rH_Gen_energy =0;
vector<double>* rJeth_Gen_pt; TBranch* b_rJeth_Gen_pt =0;
vector<double>* rJeth_Gen_eta; TBranch* b_rJeth_Gen_eta =0;
vector<double>* rJeth_Gen_phi; TBranch* b_rJeth_Gen_phi =0;
vector<double>* rJeth_Gen_energy; TBranch* b_rJeth_Gen_energy =0;
vector<double>* rLeph_Gen_pt; TBranch* b_rLeph_Gen_pt =0;
vector<double>* rLeph_Gen_eta; TBranch* b_rLeph_Gen_eta =0;
vector<double>* rLeph_Gen_phi; TBranch* b_rLeph_Gen_phi =0;
vector<double>* rLeph_Gen_energy; TBranch* b_rLeph_Gen_energy =0;
vector<double>* rLeph_Gen_Id; TBranch* b_rLeph_Gen_Id =0;
vector<double>* rLvh_Gen_pt; TBranch* b_rLvh_Gen_pt =0;
vector<double>* rLvh_Gen_eta; TBranch* b_rLvh_Gen_eta =0;
vector<double>* rLvh_Gen_phi; TBranch* b_rLvh_Gen_phi =0;
vector<double>* rLvh_Gen_energy; TBranch* b_rLvh_Gen_energy =0;
vector<double>* rLvh_Gen_Id; TBranch* b_rLvh_Gen_Id =0;
vector<double>* rLvtop_Gen_pt; TBranch* b_rLvtop_Gen_pt =0;
vector<double>* rLvtop_Gen_eta; TBranch* b_rLvtop_Gen_eta =0;
vector<double>* rLvtop_Gen_phi; TBranch* b_rLvtop_Gen_phi =0;
vector<double>* rLvtop_Gen_energy; TBranch* b_rLvtop_Gen_energy =0;
vector<double>* rLvtop_Gen_Id; TBranch* b_rLvtop_Gen_Id =0;
vector<double>* rGen_pdg_id; TBranch* b_rGen_pdg_id =0;
vector<double>* rGen_pt; TBranch* b_rGen_pt =0;
vector<double>* rGen_eta; TBranch* b_rGen_eta =0;
vector<double>* rGen_phi; TBranch* b_rGen_phi =0;
vector<double>* rGen_energy; TBranch* b_rGen_energy =0;
vector<double>* rGen_motherpdg_id; TBranch* b_rGen_motherpdg_id =0;
vector<double>* rGen_BmotherIndex; TBranch* b_rGen_BmotherIndex =0;
vector<double>* rGen_numMother; TBranch* b_rGen_numMother =0;
//jetvariables to be written
double EVENT_event;
double EVENT_genWeight;
double EVENT_xsecWeight;
double Gen_type1PF_Met;
double num_Jet_matchLooseHJet;
double num_Jet_matchMediumHJet;
double num_Jet_matchTightHJet;
double Jet_numLoose;
double num_ishlep;
double num_ishPair;
double num_Gen_Leph;
double num_Gen_Jeth;
double num_Gen_Leptop;
double num_Gen_Lvh;
double num_Gen_Lvtop;
double Met_type1PF_pt;
double Met_type1PF_px;
double Met_type1PF_py;
double Met_type1PF_pz;
double Met_type1PF_phi;
vector<double>* FakeLep_pt = new std::vector<double>;
vector<double>* FakeLep_eta = new std::vector<double>;
vector<double>* FakeLep_phi = new std::vector<double>;
vector<double>* FakeLep_energy = new std::vector<double>;
vector<double>* csvJet_isMediumHJet = new std::vector<double>;
vector<double>* csvJet_partonFlavour = new std::vector<double>;
vector<double>* csvJet_pt = new std::vector<double>;
vector<double>* csvJet_eta = new std::vector<double>;
vector<double>* csvJet_phi = new std::vector<double>;
vector<double>* csvJet_energy = new std::vector<double>;
vector<double>* Jet_lepdrmin = new std::vector<double>;
vector<double>* Jet_pt = new std::vector<double>;
vector<double>* Jet_eta = new std::vector<double>;
vector<double>* Jet_phi = new std::vector<double>;
vector<double>* Jet_energy = new std::vector<double>;
vector<double>* Jet_partonFlavour = new std::vector<double>;
vector<double>* Jet_px = new std::vector<double>;
vector<double>* Jet_py = new std::vector<double>;
vector<double>* Jet_pz = new std::vector<double>;
vector<double>* Jet_mass = new std::vector<double>;
vector<double>* Jet_newpfCombinedInclusiveSecondaryVertexV2BJetTags = new std::vector<double>;
vector<double>* Jet_pfCombinedInclusiveSecondaryVertexV2BJetTags = new std::vector<double>;
vector<double>* Jet_isLooseHJet = new std::vector<double>;
vector<double>* Jet_isMediumHJet = new std::vector<double>;
vector<double>* Jet_isTightHJet = new std::vector<double>;
vector<double>* Jet_dRGenJeth = new std::vector<double>;
vector<double>* Jet_pfCombinedMVAV2BJetTags = new std::vector<double>;
vector<double>* Jet_pfJetProbabilityBJetTags = new std::vector<double>;
vector<double>* Jet_pileupId = new std::vector<double>;
vector<double>* Jet_neutralHadEnergyFraction = new std::vector<double>;
vector<double>* Jet_neutralEmEnergyFraction = new std::vector<double>;
vector<double>* Jet_chargedHadronEnergyFraction = new std::vector<double>;
vector<double>* Jet_chargedEmEnergyFraction = new std::vector<double>;
vector<double>* Jet_muonEnergyFraction = new std::vector<double>;
vector<double>* Jet_electronEnergy = new std::vector<double>;
vector<double>* Jet_photonEnergy = new std::vector<double>;
vector<double>* Jet_emEnergyFraction = new std::vector<double>;
vector<double>* Jet_numberOfConstituents = new std::vector<double>;
vector<double>* Jet_chargedMultiplicity = new std::vector<double>;
vector<double>* Jet_vtxMass = new std::vector<double>;
vector<double>* Jet_vtxNtracks = new std::vector<double>;
vector<double>* Jet_vtx3DVal = new std::vector<double>;
vector<double>* Jet_vtx3DSig = new std::vector<double>;
vector<double>* Jet_ishighestcsv = new std::vector<double>;
vector<double>* Jet_istophJet = new std::vector<double>;
vector<double>* Jet_metptratio = new std::vector<double>;
vector<double>* Jet_dilepmetptratio = new std::vector<double>;
vector<double>* Jet_nonjdr = new std::vector<double>;
vector<double>* Jet_nonjdilepdr = new std::vector<double>;
vector<double>* Jet_lepdrmax = new std::vector<double>;
vector<double>* Jet_dilepdr = new std::vector<double>;
vector<double>* Jet_bjdr = new std::vector<double>;
vector<double>* Jet_nonjdeta = new std::vector<double>;
vector<double>* Jet_nonjdilepdeta = new std::vector<double>;
vector<double>* Jet_lepdetamin = new std::vector<double>;
vector<double>* Jet_lepdetamax = new std::vector<double>;
vector<double>* Jet_dilepdeta = new std::vector<double>;
vector<double>* Jet_bjdeta = new std::vector<double>;
vector<double>* Jet_nonjdphi = new std::vector<double>;
vector<double>* Jet_nonjdilepdphi = new std::vector<double>;
vector<double>* Jet_lepdphimin = new std::vector<double>;
vector<double>* Jet_lepdphimax = new std::vector<double>;
vector<double>* Jet_dilepdphi = new std::vector<double>;
vector<double>* Jet_bjdphi = new std::vector<double>;
vector<double>* Jet_nonjptratio = new std::vector<double>;
vector<double>* Jet_nonjdilepptratio = new std::vector<double>;
vector<double>* Jet_lepptratiomin = new std::vector<double>;
vector<double>* Jet_lepptratiomax = new std::vector<double>;
vector<double>* Jet_dilepptratio = new std::vector<double>;
vector<double>* Jet_bjptratio = new std::vector<double>;
vector<double>* FakeLep_ishlep = new std::vector<double>;
vector<double>* FakeLep_ptoverlep = new std::vector<double>;
vector<double>* FakeLep_ptovermetlep = new std::vector<double>;
vector<double>* FakeLep_rlepdrjet0csv = new std::vector<double>;
vector<double>* FakeLep_rlepdrjet0mass = new std::vector<double>;
vector<double>* FakeLep_rlepdrjet0mt = new std::vector<double>;
vector<double>* FakeLep_rlepdrjet1mass = new std::vector<double>;
vector<double>* FakeLep_sumjetsdphi = new std::vector<double>;
vector<double>* FakeLep_3toncsvjetsdphi = new std::vector<double>;
vector<double>* FakeLep_csvjet2dr = new std::vector<double>;
vector<double>* FakeLep_csvjet3dr = new std::vector<double>;
vector<double>* FakeLep_metdphi = new std::vector<double>;
vector<double>* FakeLep_metlepdphi = new std::vector<double>;
vector<double>* FakeLep_minjetdr = new std::vector<double>;
vector<double>* FakeLep_mt = new std::vector<double>;
vector<double>* FakeLep_ptovermet = new std::vector<double>;
vector<double>* FakeLep_rlepdrjet1mt = new std::vector<double>;
vector<double>* FakeLep_sumjetsdr = new std::vector<double>;
vector<double>* FakeLep_3toncsvjetsdr = new std::vector<double>;
vector<double>* FakeLep_csvjet0mass = new std::vector<double>;
vector<double>* FakeLep_csvjet1mass = new std::vector<double>;
vector<double>* FakeLep_csvjet1mt = new std::vector<double>;
vector<double>* FakeLep_csvjet2deta = new std::vector<double>;
vector<double>* FakeLep_csvjet2dphi = new std::vector<double>;
vector<double>* FakeLep_csvjet3deta = new std::vector<double>;
vector<double>* FakeLep_csvjet3dphi = new std::vector<double>;
vector<double>* FakeLep_metmt = new std::vector<double>;
vector<double>* FakeLep_minjetdphi = new std::vector<double>;
vector<double>* Jet_qg = new std::vector<double>;
vector<double>* Jet_axis2 = new std::vector<double>;
vector<double>* Jet_ptD = new std::vector<double>;
vector<double>* Jet_mult = new std::vector<double>;

//new
vector<double>* Jet_BDT = new std::vector<double>;
vector<double>* bdtJet_BDT = new std::vector<double>;
vector<double>* bdtJet_isLooseHJet = new std::vector<double>;
vector<double>* bdtJet_isMediumHJet = new std::vector<double>;
vector<double>* bdtJet_isTightHJet = new std::vector<double>;
vector<double>* bdtJet_ishighestcsv = new std::vector<double>;
vector<double>* bdtJet_istophJet = new std::vector<double>;
vector<double>* bdtJet_pt = new std::vector<double>;
vector<double>* bdtJet_eta = new std::vector<double>;
vector<double>* bdtJet_phi = new std::vector<double>;
vector<double>* bdtJet_energy = new std::vector<double>;
vector<double>* bdtJet_qg = new std::vector<double>;
vector<double>* bdtJet_newpfCombinedInclusiveSecondaryVertexV2BJetTags = new std::vector<double>;
vector<double>* bdtJet_lepdrmin = new std::vector<double>;
vector<double>* bdtJet_pfCombinedMVAV2BJetTags = new std::vector<double>;
vector<double>* bdtJet_lepdrmax = new std::vector<double>;
//new JetPair
vector<double>* bdtJetPair_id = new std::vector<double>;
vector<double>* bdtJetPair_pt = new std::vector<double>;
vector<double>* bdtJetPair_eta = new std::vector<double>;
vector<double>* bdtJetPair_phi = new std::vector<double>;
vector<double>* bdtJetPair_energy = new std::vector<double>;
vector<double>* bdtJetPair_dr = new std::vector<double>;
vector<double>* bdtJetPair_deta = new std::vector<double>;
vector<double>* bdtJetPair_dphi = new std::vector<double>;
vector<double>* bdtJetPair_mass = new std::vector<double>;
vector<double>* bdtJetPair_higestbdt = new std::vector<double>;
vector<double>* bdtJetPair_sumcsv = new std::vector<double>;
vector<double>* bdtJetPair_sumbdt = new std::vector<double>;
vector<double>* bdtJetPair_sumqg = new std::vector<double>;
vector<double>* bdtJetPair_ptratio = new std::vector<double>;
vector<double>* bdtJetPair_WChi2 = new std::vector<double>;
vector<double>* bdtJetPair_minlepdr = new std::vector<double>;
vector<double>* bdtJetPair_minlepdeta = new std::vector<double>;
vector<double>* bdtJetPair_minlepdphi = new std::vector<double>;
vector<double>* bdtJetPair_minlepmass = new std::vector<double>;
vector<double>* bdtJetPair_minlepptratio = new std::vector<double>;
vector<double>* bdtJetPair_maxlepdr = new std::vector<double>;
vector<double>* bdtJetPair_maxlepdeta = new std::vector<double>;
vector<double>* bdtJetPair_maxlepdphi = new std::vector<double>;
vector<double>* bdtJetPair_maxlepmass = new std::vector<double>;
vector<double>* bdtJetPair_maxlepptratio = new std::vector<double>;
vector<double>* bdtJetPair_minjdr = new std::vector<double>;
vector<double>* bdtJetPair_minjdeta = new std::vector<double>;
vector<double>* bdtJetPair_minjdphi = new std::vector<double>;
vector<double>* bdtJetPair_minjmass = new std::vector<double>;
vector<double>* bdtJetPair_minjptratio = new std::vector<double>;
vector<double>* bdtJetPair_maxjdr = new std::vector<double>;
vector<double>* bdtJetPair_maxjdeta = new std::vector<double>;
vector<double>* bdtJetPair_maxjdphi = new std::vector<double>;
vector<double>* bdtJetPair_maxjmass = new std::vector<double>;
vector<double>* bdtJetPair_maxjptratio = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj0dr = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj0deta = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj0dphi = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj0mass = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj0ptratio = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj1dr = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj1deta = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj1dphi = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj1mass = new std::vector<double>;
vector<double>* bdtJetPair_remaincsvj1ptratio = new std::vector<double>;
vector<double>* bdtJetPair_minjOvermaxjdr = new std::vector<double>;
vector<double>* bdtJetPair_jTopminChi2 = new std::vector<double>;
vector<double>* bdtJetPair_TopminChi2jpt = new std::vector<double>;
vector<double>* bdtJetPair_hascsvj0 = new std::vector<double>;
vector<double>* bdtJetPair_hastophj = new std::vector<double>;
vector<double>* bdtJetPair_ishPair = new std::vector<double>;
vector<double>* bdtJetPair_j0bdt = new std::vector<double>;
vector<double>* bdtJetPair_j1bdt = new std::vector<double>;
vector<double>* bdtJetPair_BDT = new std::vector<double>;
vector<double>* bdtJetPair_ismaxBDT = new std::vector<double>;
vector<double>* bdtJetPair_minlepishlep = new std::vector<double>;
vector<double>* bdtJetPair_minleppt = new std::vector<double>;
vector<double>* bdtJetPair_minlepeta = new std::vector<double>;
vector<double>* bdtJetPair_minlepphi = new std::vector<double>;
vector<double>* bdtJetPair_minlepenergy = new std::vector<double>;
vector<double>* bdtJetPair_minlepmotherIndex = new std::vector<double>;
vector<double>* bdtJetPair_minlepmotherId = new std::vector<double>;
vector<double>* bdtJetPair_minlvpt = new std::vector<double>;
vector<double>* bdtJetPair_minlveta = new std::vector<double>;
vector<double>* bdtJetPair_minlvphi = new std::vector<double>;
vector<double>* bdtJetPair_minlvenergy = new std::vector<double>;
vector<double>* bdtJetPair_minlvmotherIndex = new std::vector<double>;
vector<double>* bdtJetPair_minlvmotherId = new std::vector<double>;
vector<double>* bdtJetPair_maxlepishlep = new std::vector<double>;
vector<double>* bdtJetPair_maxleppt = new std::vector<double>;
vector<double>* bdtJetPair_maxlepeta = new std::vector<double>;
vector<double>* bdtJetPair_maxlepphi = new std::vector<double>;
vector<double>* bdtJetPair_maxlepenergy = new std::vector<double>;
vector<double>* bdtJetPair_maxlepmotherIndex = new std::vector<double>;
vector<double>* bdtJetPair_maxlepmotherId = new std::vector<double>;
vector<double>* bdtJetPair_maxlvpt = new std::vector<double>;
vector<double>* bdtJetPair_maxlveta = new std::vector<double>;
vector<double>* bdtJetPair_maxlvphi = new std::vector<double>;
vector<double>* bdtJetPair_maxlvenergy = new std::vector<double>;
vector<double>* bdtJetPair_maxlvmotherIndex = new std::vector<double>;
vector<double>* bdtJetPair_maxlvmotherId = new std::vector<double>;

//tagJetPair
vector<double>* tagJetPair_ishPair = new std::vector<double>;
vector<double>* tagJetPair_hascsvj0 = new std::vector<double>;
vector<double>* tagJetPair_hastophj = new std::vector<double>;
vector<double>* tagJetPair_id = new std::vector<double>;
vector<double>* tagJetPair_BDT = new std::vector<double>;
vector<double>* tagJetPair_pt = new std::vector<double>;
vector<double>* tagJetPair_eta = new std::vector<double>;
vector<double>* tagJetPair_phi = new std::vector<double>;
vector<double>* tagJetPair_energy = new std::vector<double>;
vector<double>* tagJetPair_mass = new std::vector<double>;
vector<double>* tagJetPair_j0bdt = new std::vector<double>;
vector<double>* tagJetPair_j1bdt = new std::vector<double>;
vector<double>* tagJetPair_dr = new std::vector<double>;
vector<double>* tagJetPair_deta = new std::vector<double>;
vector<double>* tagJetPair_dphi = new std::vector<double>;
vector<double>* tagJetPair_ismaxBDT = new std::vector<double>;
vector<double>* tagJetPair_higestbdt = new std::vector<double>;
vector<double>* tagJetPair_sumcsv = new std::vector<double>;
vector<double>* tagJetPair_sumbdt = new std::vector<double>;
vector<double>* tagJetPair_sumqg = new std::vector<double>;
vector<double>* tagJetPair_ptratio = new std::vector<double>;
vector<double>* tagJetPair_WChi2 = new std::vector<double>;
vector<double>* tagJetPair_minlepdr = new std::vector<double>;
vector<double>* tagJetPair_minlepdeta = new std::vector<double>;
vector<double>* tagJetPair_minlepdphi = new std::vector<double>;
vector<double>* tagJetPair_minlepmass = new std::vector<double>;
vector<double>* tagJetPair_minlepptratio = new std::vector<double>;
vector<double>* tagJetPair_maxlepdr = new std::vector<double>;
vector<double>* tagJetPair_maxlepdeta = new std::vector<double>;
vector<double>* tagJetPair_maxlepdphi = new std::vector<double>;
vector<double>* tagJetPair_maxlepmass = new std::vector<double>;
vector<double>* tagJetPair_maxlepptratio = new std::vector<double>;
vector<double>* tagJetPair_minjdr = new std::vector<double>;
vector<double>* tagJetPair_minjdeta = new std::vector<double>;
vector<double>* tagJetPair_minjdphi = new std::vector<double>;
vector<double>* tagJetPair_minjmass = new std::vector<double>;
vector<double>* tagJetPair_minjptratio = new std::vector<double>;
vector<double>* tagJetPair_maxjdr = new std::vector<double>;
vector<double>* tagJetPair_maxjdeta = new std::vector<double>;
vector<double>* tagJetPair_maxjdphi = new std::vector<double>;
vector<double>* tagJetPair_maxjmass = new std::vector<double>;
vector<double>* tagJetPair_maxjptratio = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj0dr = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj0deta = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj0dphi = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj0mass = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj0ptratio = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj1dr = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj1deta = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj1dphi = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj1mass = new std::vector<double>;
vector<double>* tagJetPair_remaincsvj1ptratio = new std::vector<double>;
vector<double>* tagJetPair_minjOvermaxjdr = new std::vector<double>;
vector<double>* tagJetPair_jTopminChi2 = new std::vector<double>;
vector<double>* tagJetPair_TopminChi2jpt = new std::vector<double>;
vector<double>* tagJetPair_minlepishlep = new std::vector<double>;
vector<double>* tagJetPair_minleppt = new std::vector<double>;
vector<double>* tagJetPair_minlepeta = new std::vector<double>;
vector<double>* tagJetPair_minlepphi = new std::vector<double>;
vector<double>* tagJetPair_minlepenergy = new std::vector<double>;
vector<double>* tagJetPair_minlepmotherIndex = new std::vector<double>;
vector<double>* tagJetPair_minlepmotherId = new std::vector<double>;
vector<double>* tagJetPair_minlvpt = new std::vector<double>;
vector<double>* tagJetPair_minlveta = new std::vector<double>;
vector<double>* tagJetPair_minlvphi = new std::vector<double>;
vector<double>* tagJetPair_minlvenergy = new std::vector<double>;
vector<double>* tagJetPair_minlvmotherIndex = new std::vector<double>;
vector<double>* tagJetPair_minlvmotherId = new std::vector<double>;
vector<double>* tagJetPair_maxlepishlep = new std::vector<double>;
vector<double>* tagJetPair_maxleppt = new std::vector<double>;
vector<double>* tagJetPair_maxlepeta = new std::vector<double>;
vector<double>* tagJetPair_maxlepphi = new std::vector<double>;
vector<double>* tagJetPair_maxlepenergy = new std::vector<double>;
vector<double>* tagJetPair_maxlepmotherIndex = new std::vector<double>;
vector<double>* tagJetPair_maxlepmotherId = new std::vector<double>;
vector<double>* tagJetPair_maxlvpt = new std::vector<double>;
vector<double>* tagJetPair_maxlveta = new std::vector<double>;
vector<double>* tagJetPair_maxlvphi = new std::vector<double>;
vector<double>* tagJetPair_maxlvenergy = new std::vector<double>;
vector<double>* tagJetPair_maxlvmotherIndex = new std::vector<double>;
vector<double>* tagJetPair_maxlvmotherId = new std::vector<double>;
vector<double>* Gen_pdg_id = new std::vector<double>;
vector<double>* Gen_pt = new std::vector<double>;
vector<double>* Gen_eta = new std::vector<double>;
vector<double>* Gen_phi = new std::vector<double>;
vector<double>* Gen_energy = new std::vector<double>;
vector<double>* Gen_motherpdg_id = new std::vector<double>;
vector<double>* Gen_BmotherIndex = new std::vector<double>;
vector<double>* Gen_numMother = new std::vector<double>;

//LepTag
vector<double>* FakeLep_bdt = new std::vector<double>;
vector<double>* FakeLep_ishigherbdt = new std::vector<double>;

////Read LepMVA/////
TMVA::Reader *readerjet;

  Float_t jetvarqg;
  Float_t jetvaraxis2;
  Float_t jetvarmult;
  Float_t jetvarptD;
  Float_t jetvardilepdphi;
  Float_t jetvarlepdphimin;
  Float_t jetvarnonjdphi;
  Float_t jetvarlepdetamax;
  Float_t jetvarlepdetamin;
  Float_t jetvardilepdr;
  Float_t jetvarlepdrmax;
  Float_t jetvarmass;
  Float_t jetvarpx;
  Float_t jetvarpy;
  Float_t jetvarpz;
  Float_t jetvarenergy;
  Float_t jetvarpt;
  Float_t jetvareta;
  Float_t jetvarlepdrmin;
  Float_t jetvarbjptratio;
  Float_t jetvardilepptratio;
  Float_t jetvarnonjdilepptratio;
  Float_t jetvarnonjptratio;
  Float_t jetvarlepdphimax;
  Float_t jetvarbjdeta;
  Float_t jetvardilepdeta;
  Float_t jetvarnonjdeta;
  Float_t jetvarbjdr;
  Float_t jetvarnonjdr;
  Float_t jetvarmetptratio;
  Float_t jetvarchargedMultiplicity;
  Float_t jetvarnumberOfConstituents;
  Float_t jetvarchargedHadronEnergyFraction;
  Float_t jetvarpfCombinedMVAV2BJetTags;
  Float_t jetvarpfCombinedInclusiveSecondaryVertexV2BJetTags;

TMVA::Reader *readerlep;
  Float_t lepvarptoverlep;
  Float_t lepvarptovermetlep;
  Float_t lepvarrlepdrjet0csv;
  Float_t lepvarrlepdrjet0mass;
  Float_t lepvarrlepdrjet0mt;
  Float_t lepvarrlepdrjet1mass;
  Float_t lepvarsumjetsdphi;
  Float_t lepvar3toncsvjetsdphi;
  Float_t lepvarcsvjet2dr;
  Float_t lepvarcsvjet3dr;
  Float_t lepvarmetdphi;
  Float_t lepvarmetlepdphi;
  Float_t lepvarminjetdr;
  Float_t lepvarmt;
  Float_t lepvarptovermet;
  Float_t lepvarpt;
  Float_t lepvarrlepdrjet1mt;
  Float_t lepvarsumjetsdr;
  Float_t lepvar3toncsvjetsdr;
  Float_t lepvarcsvjet0mass;
  Float_t lepvarcsvjet1mass;
  Float_t lepvarcsvjet1mt;
  Float_t lepvarcsvjet2deta;
  Float_t lepvarcsvjet2dphi;
  Float_t lepvarcsvjet3deta;
  Float_t lepvarcsvjet3dphi;
  Float_t lepvarmetmt;
  Float_t lepvarminjetdphi;

 TMVA::Reader *readerpair;
  Float_t pairvarenergy;
  Float_t pairvardr;
  Float_t pairvardeta;
  Float_t pairvardphi;
  Float_t pairvarmass;
  Float_t pairvarhigestbdt;
  Float_t pairvarsumcsv;
  Float_t pairvarsumbdt;
  Float_t pairvarsumqg;
  Float_t pairvarptratio;
  Float_t pairvarWChi2;
  Float_t pairvarminlepdr;
  Float_t pairvarminlepdeta;
  Float_t pairvarminlepdphi;
  Float_t pairvarminlepmass;
  Float_t pairvarmaxlepdr;
  Float_t pairvarmaxlepdeta;
  Float_t pairvarmaxlepdphi;
  Float_t pairvarmaxlepmass;
  Float_t pairvarminjdr;
  Float_t pairvarminjdeta;
  Float_t pairvarminjdphi;
  Float_t pairvarminjmass;
  Float_t pairvarmaxjdr;
  Float_t pairvarmaxjmass;
  Float_t pairvarmaxjdeta;
  Float_t pairvarremaincsvj0mass;
  Float_t pairvarremaincsvj1mass;
  Float_t pairvarremaincsvj0deta;
  Float_t pairvarminjOvermaxjdr;
  Float_t pairvarjTopminChi2;
//Regression Train
Float_t H_Gen_massA;
Float_t H_Gen_massB;
Float_t H_Gen_massC;
Float_t RegLep_px;
Float_t RegLep_py;
Float_t RegLep_pz;
Float_t RegLep_eta;
Float_t RegLep_energy;
Float_t RegJetPair_px;
Float_t RegJetPair_py;
Float_t RegJetPair_pz;
Float_t RegJetPair_eta;
Float_t RegJetPair_energy;
Float_t RegHsys_px;
Float_t RegHsys_pt;
Float_t RegHsys_py;
Float_t RegHsys_pz;
Float_t RegHsys_eta;
Float_t RegHsys_energy;
Float_t RegHsys_mass;
Float_t RegMet;
Float_t RegPt_LepOverMet;
Float_t RegPt_LepOverJetPair;
Float_t RegPt_MetOverJetPair;
Float_t RegdR_LepJetPair;
Float_t Regdeta_LepJetPair;
Float_t Regdphi_LepJetPair;
Float_t GenLep_px;
Float_t GenLep_py;
Float_t GenLep_pz;
Float_t GenLep_eta;
Float_t GenLep_energy;
Float_t GenJetPair_px;
Float_t GenJetPair_py;
Float_t GenJetPair_pz;
Float_t GenJetPair_eta;
Float_t GenJetPair_energy;
Float_t GenHsys_px;
Float_t GenHsys_py;
Float_t GenHsys_pz;
Float_t GenHsys_eta;
Float_t GenHsys_energy;
Float_t GenHsys_mass;
Float_t GenMet;
Float_t GenPt_LepOverMet;
Float_t GenPt_LepOverJetPair;
Float_t GenPt_MetOverJetPair;
Float_t GendR_LepJetPair;
Float_t Gendeta_LepJetPair;
Float_t Gendphi_LepJetPair;
Float_t TargetH_mass;
Float_t TargetH_pt;
Float_t TargetH_eta;
Float_t TargetH_energy;
Float_t minHsys_pt;
Float_t minHsys_eta;
Float_t minHsys_mass;
Float_t minHsys_energy;
Float_t minHsys_pz;
Float_t minHsys_px;
Float_t minHsys_py;
Float_t maxHsys_pt;
Float_t maxHsys_eta;
Float_t maxHsys_mass;
Float_t maxHsys_energy;
Float_t maxHsys_pz;
Float_t maxHsys_px;
Float_t maxHsys_py;
Float_t minljjv_pt;
Float_t minljjv_eta;
Float_t minljjv_phi;
Float_t minljjv_energy;
Float_t minljjv_mass;
Float_t minljjv_ishpair;
Float_t minljjv_ishlep;
Float_t maxljjv_pt;
Float_t maxljjv_eta;
Float_t maxljjv_phi;
Float_t maxljjv_energy;
Float_t maxljjv_mass;
Float_t maxljjv_ishpair;
Float_t maxljjv_ishlep;
Float_t RegPt_Lep1OverMet;
Float_t RegPt_Lep2OverMet;
Float_t Regdphi_Lep1Met;
Float_t Regdphi_Lep2Met;
//Train Regress to Lv
Float_t minlep_pt;
Float_t minlep_eta;
Float_t minlep_phi;
Float_t minlep_energy;
Float_t minlep_ptratioMet;
Float_t minlep_dphiMet;
Float_t maxlep_pt;
Float_t maxlep_eta;
Float_t maxlep_phi;
Float_t maxlep_energy;
Float_t maxlep_ptratioMet;
Float_t maxlep_dphiMet;
Float_t minlv_pt;
Float_t minlv_eta;
Float_t minlv_phi;
Float_t minlv_energy;
Float_t Met_pt;
Float_t Met_phi;
//Train Regression Mass variables
Float_t jj_pt;
Float_t jj_eta;
Float_t jj_phi;
Float_t jj_energy;
Float_t jj_mass;
Float_t E_lXjj;
Float_t Pt_lXjjXmet;
Float_t ljj_cosTheta;
Float_t MT_ljjMet;
Float_t Meff_ljjMet;
Float_t Mtrue;
Float_t MTtot;
Float_t MT_lMet;
Float_t Mt_lMetOverM_jj;

//Regression 
Float_t maxRegH_pt;
Float_t maxRegH_eta;
Float_t maxRegH_energy;
Float_t maxRegH_mass;
Float_t genRegH_pt;
Float_t genRegH_eta;
Float_t genRegH_energy;
Float_t genRegH_mass;
Float_t minRegH_pt;
Float_t minRegH_eta;
Float_t minRegH_energy;
Float_t minRegH_mass;
Float_t minReglv_pt;
Float_t minReglv_eta;
Float_t minReglv_phi;
Float_t minReglv_energy;
Float_t minljjReglv_mass;


TMVA::Reader *readerreg;
Float_t regvarLep_px;
Float_t regvarLep_py;
Float_t regvarLep_pz;
Float_t regvarLep_eta;
Float_t regvarLep_energy;
Float_t regvarJetPair_px;
Float_t regvarJetPair_py;
Float_t regvarJetPair_pz;
Float_t regvarJetPair_eta;
Float_t regvarJetPair_energy;
Float_t regvarHsys_px;
Float_t regvarHsys_pt;
Float_t regvarHsys_py;
Float_t regvarHsys_pz;
Float_t regvarHsys_eta;
Float_t regvarHsys_energy;
Float_t regvarHsys_mass;
Float_t regvarMet;
Float_t regvarPt_LepOverMet;
Float_t regvarPt_LepOverJetPair;
Float_t regvarPt_MetOverJetPair;
Float_t regvardR_LepJetPair;
Float_t regvardeta_LepJetPair;
Float_t regvardphi_LepJetPair;
Float_t regvarPt_Lep1OverMet;
Float_t regvarPt_Lep2OverMet;
Float_t regvardphi_Lep1Met;
Float_t regvardphi_Lep2Met;

TMVA::Reader *readerlv;
Float_t regvarminlep_pt;
Float_t regvarminlep_eta;
Float_t regvarminlep_phi;
Float_t regvarminlep_energy;
Float_t regvarminlep_ptratioMet;
Float_t regvarminlep_dphiMet;
Float_t regvarmaxlep_pt;
Float_t regvarmaxlep_eta;
Float_t regvarmaxlep_phi;
Float_t regvarmaxlep_energy;
Float_t regvarmaxlep_ptratioMet;
Float_t regvarmaxlep_dphiMet;
Float_t regvarMet_pt;
Float_t regvarMet_phi;
